// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

// ActionsActions domain models
extension ActionsForkPrWorkflowsPrivateReposRequest {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.runWorkflowsFromForkPullRequests) else {
            throw SdkValidationError(field: "run_workflows_from_fork_pull_requests", code: "required", message: "Validation failed for 'run_workflows_from_fork_pull_requests': value is required")
        }
        self.runWorkflowsFromForkPullRequests = try container.sdkDecodeRequired(.runWorkflowsFromForkPullRequests)
        self.sendWriteTokensToWorkflows = try container.sdkDecodeIfPresent(.sendWriteTokensToWorkflows)
        self.sendSecretsAndVariables = try container.sdkDecodeIfPresent(.sendSecretsAndVariables)
        self.requireApprovalForForkPrWorkflows = try container.sdkDecodeIfPresent(.requireApprovalForForkPrWorkflows)
    }
}

extension ActionsForkPrWorkflowsPrivateReposRequest {
    public init(runWorkflowsFromForkPullRequests: Bool, sendWriteTokensToWorkflows: Bool? = nil, sendSecretsAndVariables: Bool? = nil, requireApprovalForForkPrWorkflows: Bool? = nil) {
        self.runWorkflowsFromForkPullRequests = runWorkflowsFromForkPullRequests
        self.sendWriteTokensToWorkflows = sendWriteTokensToWorkflows
        self.sendSecretsAndVariables = sendSecretsAndVariables
        self.requireApprovalForForkPrWorkflows = requireApprovalForForkPrWorkflows
    }
}

/// Typed representation of the `ActionsGetDefaultWorkflowPermissions` API schema.
public struct ActionsGetDefaultWorkflowPermissions: Codable {
    /// The default workflow permissions granted to the GITHUB_TOKEN when running workflows.
    public var defaultWorkflowPermissions: ActionsDefaultWorkflowPermissions
    /// Whether GitHub Actions can approve pull requests. Enabling this can be a security risk.
    public var canApprovePullRequestReviews: ActionsCanApprovePullRequestReviews

    enum CodingKeys: String, CodingKey {
        case defaultWorkflowPermissions = "default_workflow_permissions"
        case canApprovePullRequestReviews = "can_approve_pull_request_reviews"
    }

    private init(sdkCopy value: Self) { self = value }
}

extension ActionsGetDefaultWorkflowPermissions {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.defaultWorkflowPermissions) else {
            throw SdkValidationError(field: "default_workflow_permissions", code: "required", message: "Validation failed for 'default_workflow_permissions': value is required")
        }
        guard container.contains(.canApprovePullRequestReviews) else {
            throw SdkValidationError(field: "can_approve_pull_request_reviews", code: "required", message: "Validation failed for 'can_approve_pull_request_reviews': value is required")
        }
        self.defaultWorkflowPermissions = try container.sdkDecodeRequired(.defaultWorkflowPermissions)
        self.canApprovePullRequestReviews = try container.sdkDecodeRequired(.canApprovePullRequestReviews)
    }
}

extension ActionsGetDefaultWorkflowPermissions {
    public init(defaultWorkflowPermissions: ActionsDefaultWorkflowPermissions, canApprovePullRequestReviews: ActionsCanApprovePullRequestReviews) {
        self.defaultWorkflowPermissions = defaultWorkflowPermissions
        self.canApprovePullRequestReviews = canApprovePullRequestReviews
    }
}

/// A Github-hosted hosted runner.
public struct ActionsHostedRunner: Codable {
    /// The unique identifier of the hosted runner.
    /// - Example: 5
    public var id: Int
    /// The name of the hosted runner.
    /// - Example: "my-github-hosted-runner"
    public var name: String
    /// Provides details of a hosted runner image
    public var imageDetails: NullableActionsHostedRunnerPoolImage?
    /// Provides details of a particular machine spec.
    public var machineSizeDetails: ActionsHostedRunnerMachineSpec
    /// The status of the runner.
    /// - Example: "Ready"
    public var status: ActionsHostedRunnerStatus
    /// The operating system of the image.
    /// - Example: "linux-x64"
    public var platform: String
    /// Whether public IP is enabled for the hosted runners.
    /// - Example: true
    public var publicIpEnabled: Bool
    /// The unique identifier of the group that the hosted runner belongs to.
    /// - Example: 2
    public var runnerGroupId: Int?
    /// The maximum amount of hosted runners. Runners will not scale automatically above this number. Use this
    /// setting to limit your cost.
    /// - Example: 5
    public var maximumRunners: Int?
    /// The public IP ranges when public IP is enabled for the hosted runners.
    public var publicIps: [PublicIp]?
    /// The time at which the runner was last used, in ISO 8601 format.
    /// - Example: "2022-10-09T23:39:01Z"
    public var lastActiveOn: Date?
    /// Whether custom image generation is enabled for the hosted runners.
    public var imageGen: Bool?

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case imageDetails = "image_details"
        case machineSizeDetails = "machine_size_details"
        case status
        case platform
        case publicIpEnabled = "public_ip_enabled"
        case runnerGroupId = "runner_group_id"
        case maximumRunners = "maximum_runners"
        case publicIps = "public_ips"
        case lastActiveOn = "last_active_on"
        case imageGen = "image_gen"
    }

    private init(sdkCopy value: Self) { self = value }
}

extension ActionsHostedRunner {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(field: "id", code: "required", message: "Validation failed for 'id': value is required")
        }
        guard container.contains(.name) else {
            throw SdkValidationError(field: "name", code: "required", message: "Validation failed for 'name': value is required")
        }
        guard container.contains(.imageDetails) else {
            throw SdkValidationError(field: "image_details", code: "required", message: "Validation failed for 'image_details': value is required")
        }
        guard container.contains(.machineSizeDetails) else {
            throw SdkValidationError(field: "machine_size_details", code: "required", message: "Validation failed for 'machine_size_details': value is required")
        }
        guard container.contains(.status) else {
            throw SdkValidationError(field: "status", code: "required", message: "Validation failed for 'status': value is required")
        }
        guard container.contains(.platform) else {
            throw SdkValidationError(field: "platform", code: "required", message: "Validation failed for 'platform': value is required")
        }
        guard container.contains(.publicIpEnabled) else {
            throw SdkValidationError(field: "public_ip_enabled", code: "required", message: "Validation failed for 'public_ip_enabled': value is required")
        }
        self.id = try container.sdkDecodeRequired(.id)
        self.name = try container.sdkDecodeRequired(.name)
        self.imageDetails = try container.sdkDecodeIfPresent(.imageDetails)
        self.machineSizeDetails = try container.sdkDecodeRequired(.machineSizeDetails)
        self.status = try container.sdkDecodeRequired(.status)
        self.platform = try container.sdkDecodeRequired(.platform)
        self.publicIpEnabled = try container.sdkDecodeRequired(.publicIpEnabled)
        self.runnerGroupId = try container.sdkDecodeIfPresent(.runnerGroupId)
        self.maximumRunners = try container.sdkDecodeIfPresent(.maximumRunners)
        self.publicIps = try container.sdkDecodeIfPresent(.publicIps)
        self.lastActiveOn = try container.sdkDecodeIfPresent(.lastActiveOn)
        self.imageGen = try container.sdkDecodeIfPresent(.imageGen)
        if let value = self.lastActiveOn {
            try sdkValidateDateTime("last_active_on", sdkWireString(value))
        }
    }
}

extension ActionsHostedRunner {
    public init(id: Int, name: String, imageDetails: NullableActionsHostedRunnerPoolImage?, machineSizeDetails: ActionsHostedRunnerMachineSpec, status: ActionsHostedRunnerStatus, platform: String, publicIpEnabled: Bool, runnerGroupId: Int? = nil, maximumRunners: Int? = nil, publicIps: [PublicIp]? = nil, lastActiveOn: Date? = nil, imageGen: Bool? = nil) throws {
        (self.id, self.name) = (id, name)
        (self.imageDetails, self.machineSizeDetails) = (imageDetails, machineSizeDetails)
        (self.status, self.platform) = (status, platform)
        (self.publicIpEnabled, self.runnerGroupId) = (publicIpEnabled, runnerGroupId)
        (self.maximumRunners, self.publicIps) = (maximumRunners, publicIps)
        (self.lastActiveOn, self.imageGen) = (lastActiveOn, imageGen)
        if let value = self.lastActiveOn {
            try sdkValidateDateTime("last_active_on", sdkWireString(value))
        }
    }
}

/// Provides details of a hosted runner image
public struct ActionsHostedRunnerCuratedImage: Codable {
    /// The ID of the image. Use this ID for the `image` parameter when creating a new larger runner.
    /// - Example: "ubuntu-20.04"
    public var id: String
    /// The operating system of the image.
    /// - Example: "linux-x64"
    public var platform: String
    /// Image size in GB.
    /// - Example: 86
    public var sizeGb: Int
    /// Display name for this image.
    /// - Example: 20.04
    public var displayName: String
    /// The image provider.
    public var source: ActionsHostedRunnerCuratedImageSource

    enum CodingKeys: String, CodingKey {
        case id
        case platform
        case sizeGb = "size_gb"
        case displayName = "display_name"
        case source
    }

    private init(sdkCopy value: Self) { self = value }
}

extension ActionsHostedRunnerCuratedImage {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(field: "id", code: "required", message: "Validation failed for 'id': value is required")
        }
        guard container.contains(.platform) else {
            throw SdkValidationError(field: "platform", code: "required", message: "Validation failed for 'platform': value is required")
        }
        guard container.contains(.sizeGb) else {
            throw SdkValidationError(field: "size_gb", code: "required", message: "Validation failed for 'size_gb': value is required")
        }
        guard container.contains(.displayName) else {
            throw SdkValidationError(field: "display_name", code: "required", message: "Validation failed for 'display_name': value is required")
        }
        guard container.contains(.source) else {
            throw SdkValidationError(field: "source", code: "required", message: "Validation failed for 'source': value is required")
        }
        self.id = try container.sdkDecodeRequired(.id)
        self.platform = try container.sdkDecodeRequired(.platform)
        self.sizeGb = try container.sdkDecodeRequired(.sizeGb)
        self.displayName = try container.sdkDecodeRequired(.displayName)
        self.source = try container.sdkDecodeRequired(.source)
    }
}

extension ActionsHostedRunnerCuratedImage {
    public init(id: String, platform: String, sizeGb: Int, displayName: String, source: ActionsHostedRunnerCuratedImageSource) {
        (self.id, self.platform) = (id, platform)
        (self.sizeGb, self.displayName) = (sizeGb, displayName)
        self.source = source
    }
}

/// Provides details of a custom runner image
public struct ActionsHostedRunnerCustomImage: Codable {
    /// The ID of the image. Use this ID for the `image` parameter when creating a new larger runner.
    /// - Example: 1
    public var id: Int
    /// The operating system of the image.
    /// - Example: "linux-x64"
    public var platform: String
    /// Total size of all the image versions in GB.
    /// - Example: 200
    public var totalVersionsSize: Int
    /// Display name for this image.
    /// - Example: "CustomImage"
    public var name: String
    /// The image provider.
    /// - Example: "custom"
    public var source: String
    /// The number of image versions associated with the image.
    /// - Example: 4
    public var versionsCount: Int
    /// The latest image version associated with the image.
    /// - Example: "1.3.0"
    public var latestVersion: String
    /// The number of image versions associated with the image.
    /// - Example: "Ready"
    public var state: String

    enum CodingKeys: String, CodingKey {
        case id
        case platform
        case totalVersionsSize = "total_versions_size"
        case name
        case source
        case versionsCount = "versions_count"
        case latestVersion = "latest_version"
        case state
    }

    private init(sdkCopy value: Self) { self = value }
}

extension ActionsHostedRunnerCustomImage {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.sdkDecodeRequired(.id)
        self.platform = try container.sdkDecodeRequired(.platform)
        self.totalVersionsSize = try container.sdkDecodeRequired(.totalVersionsSize)
        self.name = try container.sdkDecodeRequired(.name)
        self.source = try container.sdkDecodeRequired(.source)
        self.versionsCount = try container.sdkDecodeRequired(.versionsCount)
        self.latestVersion = try container.sdkDecodeRequired(.latestVersion)
        self.state = try container.sdkDecodeRequired(.state)
    }
}

extension ActionsHostedRunnerCustomImage {
    public init(id: Int, platform: String, totalVersionsSize: Int, name: String, source: String, versionsCount: Int, latestVersion: String, state: String) {
        (self.id, self.platform) = (id, platform)
        (self.totalVersionsSize, self.name) = (totalVersionsSize, name)
        (self.source, self.versionsCount) = (source, versionsCount)
        (self.latestVersion, self.state) = (latestVersion, state)
    }
}

/// Provides details of a hosted runner custom image version
public struct ActionsHostedRunnerCustomImageVersion: Codable {
    /// The version of image.
    /// - Example: "1.0.0"
    public var version: String
    /// The state of image version.
    /// - Example: "Ready"
    public var state: String
    /// Image version size in GB.
    /// - Example: 30
    public var sizeGb: Int
    /// The creation date time of the image version.
    /// - Example: "2024-11-09T23:39:01Z"
    public var createdOn: String
    /// The image version status details.
    /// - Example: "None"
    public var stateDetails: String

    enum CodingKeys: String, CodingKey {
        case version
        case state
        case sizeGb = "size_gb"
        case createdOn = "created_on"
        case stateDetails = "state_details"
    }

    private init(sdkCopy value: Self) { self = value }
}

extension ActionsHostedRunnerCustomImageVersion {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.version) else {
            throw SdkValidationError(field: "version", code: "required", message: "Validation failed for 'version': value is required")
        }
        guard container.contains(.state) else {
            throw SdkValidationError(field: "state", code: "required", message: "Validation failed for 'state': value is required")
        }
        guard container.contains(.sizeGb) else {
            throw SdkValidationError(field: "size_gb", code: "required", message: "Validation failed for 'size_gb': value is required")
        }
        guard container.contains(.createdOn) else {
            throw SdkValidationError(field: "created_on", code: "required", message: "Validation failed for 'created_on': value is required")
        }
        guard container.contains(.stateDetails) else {
            throw SdkValidationError(field: "state_details", code: "required", message: "Validation failed for 'state_details': value is required")
        }
        self.version = try container.sdkDecodeRequired(.version)
        self.state = try container.sdkDecodeRequired(.state)
        self.sizeGb = try container.sdkDecodeRequired(.sizeGb)
        self.createdOn = try container.sdkDecodeRequired(.createdOn)
        self.stateDetails = try container.sdkDecodeRequired(.stateDetails)
    }
}

extension ActionsHostedRunnerCustomImageVersion {
    public init(version: String, state: String, sizeGb: Int, createdOn: String, stateDetails: String) {
        (self.version, self.state) = (version, state)
        (self.sizeGb, self.createdOn) = (sizeGb, createdOn)
        self.stateDetails = stateDetails
    }
}

/// Typed representation of the `ActionsHostedRunnerLimits` API schema.
public struct ActionsHostedRunnerLimits: Codable {
    /// Provides details of static public IP limits for GitHub-hosted Hosted Runners
    public var publicIps: ActionsHostedRunnerLimitsPublicIps

    enum CodingKeys: String, CodingKey {
        case publicIps = "public_ips"
    }

    private init(sdkCopy value: Self) { self = value }
}

extension ActionsHostedRunnerLimits {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.publicIps) else {
            throw SdkValidationError(field: "public_ips", code: "required", message: "Validation failed for 'public_ips': value is required")
        }
        self.publicIps = try container.sdkDecodeRequired(.publicIps)
    }
}

extension ActionsHostedRunnerLimits {
    public init(publicIps: ActionsHostedRunnerLimitsPublicIps) {
        self.publicIps = publicIps
    }
}

/// Provides details of static public IP limits for GitHub-hosted Hosted Runners
public struct ActionsHostedRunnerLimitsPublicIps: Codable {
    /// The maximum number of static public IP addresses that can be used for Hosted Runners.
    /// - Example: 50
    public var maximum: Int
    /// The current number of static public IP addresses in use by Hosted Runners.
    /// - Example: 17
    public var currentUsage: Int

    enum CodingKeys: String, CodingKey {
        case maximum
        case currentUsage = "current_usage"
    }

    private init(sdkCopy value: Self) { self = value }
}

extension ActionsHostedRunnerLimitsPublicIps {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.maximum) else {
            throw SdkValidationError(field: "maximum", code: "required", message: "Validation failed for 'maximum': value is required")
        }
        guard container.contains(.currentUsage) else {
            throw SdkValidationError(field: "current_usage", code: "required", message: "Validation failed for 'current_usage': value is required")
        }
        self.maximum = try container.sdkDecodeRequired(.maximum)
        self.currentUsage = try container.sdkDecodeRequired(.currentUsage)
    }
}

extension ActionsHostedRunnerLimitsPublicIps {
    public init(maximum: Int, currentUsage: Int) {
        (self.maximum, self.currentUsage) = (maximum, currentUsage)
    }
}

/// Provides details of a particular machine spec.
public struct ActionsHostedRunnerMachineSpec: Codable {
    /// The ID used for the `size` parameter when creating a new runner.
    /// - Example: "8-core"
    public var id: String
    /// The number of cores.
    /// - Example: 8
    public var cpuCores: Int
    /// The available RAM for the machine spec.
    /// - Example: 32
    public var memoryGb: Int
    /// The available SSD storage for the machine spec.
    /// - Example: 300
    public var storageGb: Int

    enum CodingKeys: String, CodingKey {
        case id
        case cpuCores = "cpu_cores"
        case memoryGb = "memory_gb"
        case storageGb = "storage_gb"
    }

    private init(sdkCopy value: Self) { self = value }
}

extension ActionsHostedRunnerMachineSpec {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(field: "id", code: "required", message: "Validation failed for 'id': value is required")
        }
        guard container.contains(.cpuCores) else {
            throw SdkValidationError(field: "cpu_cores", code: "required", message: "Validation failed for 'cpu_cores': value is required")
        }
        guard container.contains(.memoryGb) else {
            throw SdkValidationError(field: "memory_gb", code: "required", message: "Validation failed for 'memory_gb': value is required")
        }
        guard container.contains(.storageGb) else {
            throw SdkValidationError(field: "storage_gb", code: "required", message: "Validation failed for 'storage_gb': value is required")
        }
        self.id = try container.sdkDecodeRequired(.id)
        self.cpuCores = try container.sdkDecodeRequired(.cpuCores)
        self.memoryGb = try container.sdkDecodeRequired(.memoryGb)
        self.storageGb = try container.sdkDecodeRequired(.storageGb)
    }
}

extension ActionsHostedRunnerMachineSpec {
    public init(id: String, cpuCores: Int, memoryGb: Int, storageGb: Int) {
        (self.id, self.cpuCores) = (id, cpuCores)
        (self.memoryGb, self.storageGb) = (memoryGb, storageGb)
    }
}
