// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// CodeScanningCodeScanningAnalysis domain models
public typealias CodeScanningAnalysisAnalysisKey = String

public typealias CodeScanningAnalysisCategory = String

public typealias CodeScanningAnalysisCommitSha = String

public typealias CodeScanningAnalysisCreatedAt = Date

public typealias CodeScanningAnalysisEnvironment = String

public typealias CodeScanningAnalysisSarifFile = String

public typealias CodeScanningAnalysisSarifId = String

public typealias CodeScanningAnalysisToolGuid = String

public typealias CodeScanningAnalysisToolName = String

public typealias CodeScanningAnalysisToolVersion = String

public typealias CodeScanningAnalysisUrl = String

/// Typed representation of the `CodeScanningAnalysis` API schema.
public struct CodeScanningAnalysis: Codable {
    /// The Git reference, formatted as `refs/pull/<number>/merge`, `refs/pull/<number>/head`, `refs/heads/<branch
    /// name>` or simply `<branch name>`.
    public var ref: CodeScanningRef
    /// The SHA of the commit to which the analysis you are uploading relates.
    public var commitSha: CodeScanningAnalysisCommitSha
    /// Identifies the configuration under which the analysis was executed. For example, in GitHub Actions this
    /// includes the workflow filename and job name.
    public var analysisKey: CodeScanningAnalysisAnalysisKey
    /// Identifies the variable values associated with the environment in which this analysis was performed.
    public var environment: CodeScanningAnalysisEnvironment
    /// Required `string` value serialized in the `error` wire field.
    /// - Example: "error reading field xyz"
    public var error: String
    /// The time that the analysis was created in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var createdAt: CodeScanningAnalysisCreatedAt
    /// The total number of results in the analysis.
    public var resultsCount: Int
    /// The total number of rules used in the analysis.
    public var rulesCount: Int
    /// Unique identifier for this analysis.
    public var id: Int
    /// The REST API URL of the analysis resource.
    public var url: CodeScanningAnalysisUrl
    /// An identifier for the upload.
    /// - Example: "6c81cd8e-b078-4ac3-a3be-1dad7dbd0b53"
    public var sarifId: CodeScanningAnalysisSarifId
    /// Required object value serialized in the `tool` wire field.
    public var tool: CodeScanningAnalysisTool
    /// Required `boolean` value serialized in the `deletable` wire field.
    public var deletable: Bool
    /// Warning generated when processing the analysis
    /// - Example: "123 results were ignored"
    public var warning: String
    /// Identifies the configuration under which the analysis was executed. Used to distinguish between multiple
    /// analyses for the same tool and commit, but performed on different languages or different parts of the code.
    public var category: CodeScanningAnalysisCategory?

    enum CodingKeys: String, CodingKey {
        case ref
        case commitSha = "commit_sha"
        case analysisKey = "analysis_key"
        case environment
        case error
        case createdAt = "created_at"
        case resultsCount = "results_count"
        case rulesCount = "rules_count"
        case id
        case url
        case sarifId = "sarif_id"
        case tool
        case deletable
        case warning
        case category
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension CodeScanningAnalysis {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        ref = try container.sdkDecodeRequired(.ref)
        commitSha = try container.sdkDecodeRequired(.commitSha)
        analysisKey = try container.sdkDecodeRequired(.analysisKey)
        environment = try container.sdkDecodeRequired(.environment)
        error = try container.sdkDecodeRequired(.error)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        resultsCount = try container.sdkDecodeRequired(.resultsCount)
        rulesCount = try container.sdkDecodeRequired(.rulesCount)
        id = try container.sdkDecodeRequired(.id)
        url = try container.sdkDecodeRequired(.url)
        sarifId = try container.sdkDecodeRequired(.sarifId)
        tool = try container.sdkDecodeRequired(.tool)
        deletable = try container.sdkDecodeRequired(.deletable)
        warning = try container.sdkDecodeRequired(.warning)
        category = try container.sdkDecodeIfPresent(.category)
        try validateLength("commit_sha", sdkWireString(commitSha), min: 40, max: 64)
        try sdkValidatePattern("commit_sha", sdkWireString(commitSha), sdkPatternbefac02b7dfd)
        try sdkValidateDateTime("created_at", sdkWireString(createdAt))
        try sdkValidateUri("url", sdkWireString(url))
    }
}

public extension CodeScanningAnalysis {
    init(
        ref: CodeScanningRef,
        commitSha: CodeScanningAnalysisCommitSha,
        analysisKey: CodeScanningAnalysisAnalysisKey,
        environment: CodeScanningAnalysisEnvironment,
        error: String,
        createdAt: CodeScanningAnalysisCreatedAt,
        resultsCount: Int,
        rulesCount: Int,
        id: Int,
        url: CodeScanningAnalysisUrl,
        sarifId: CodeScanningAnalysisSarifId,
        tool: CodeScanningAnalysisTool,
        deletable: Bool,
        warning: String,
        category: CodeScanningAnalysisCategory? = nil
    ) throws {
        (self.ref, self.commitSha) = (ref, commitSha)
        (self.analysisKey, self.environment) = (analysisKey, environment)
        (self.error, self.createdAt) = (error, createdAt)
        (self.resultsCount, self.rulesCount) = (resultsCount, rulesCount)
        (self.id, self.url) = (id, url)
        (self.sarifId, self.tool) = (sarifId, tool)
        (self.deletable, self.warning) = (deletable, warning)
        self.category = category
        try validateLength("commit_sha", sdkWireString(self.commitSha), min: 40, max: 64)
        try sdkValidatePattern("commit_sha", sdkWireString(self.commitSha), sdkPatternbefac02b7dfd)
        try sdkValidateDateTime("created_at", sdkWireString(self.createdAt))
        try sdkValidateUri("url", sdkWireString(self.url))
    }
}

/// Successful deletion of a code scanning analysis
public struct CodeScanningAnalysisDeletion: Codable {
    /// Next deletable analysis in chain, without last analysis deletion confirmation
    public var nextAnalysisUrl: String?
    /// Next deletable analysis in chain, with last analysis deletion confirmation
    public var confirmDeleteUrl: String?

    enum CodingKeys: String, CodingKey {
        case nextAnalysisUrl = "next_analysis_url"
        case confirmDeleteUrl = "confirm_delete_url"
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension CodeScanningAnalysisDeletion {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.nextAnalysisUrl) else {
            throw SdkValidationError(
                field: "next_analysis_url",
                code: "required",
                message: "Validation failed for 'next_analysis_url': value is required"
            )
        }
        guard container.contains(.confirmDeleteUrl) else {
            throw SdkValidationError(
                field: "confirm_delete_url",
                code: "required",
                message: "Validation failed for 'confirm_delete_url': value is required"
            )
        }
        nextAnalysisUrl = try container.sdkDecodeIfPresent(.nextAnalysisUrl)
        confirmDeleteUrl = try container.sdkDecodeIfPresent(.confirmDeleteUrl)
        if let value = nextAnalysisUrl {
            try sdkValidateUri("next_analysis_url", value)
        }
        if let value = confirmDeleteUrl {
            try sdkValidateUri("confirm_delete_url", value)
        }
    }
}

public extension CodeScanningAnalysisDeletion {
    init(nextAnalysisUrl: String?, confirmDeleteUrl: String?) throws {
        (self.nextAnalysisUrl, self.confirmDeleteUrl) = (nextAnalysisUrl, confirmDeleteUrl)
        if let value = self.nextAnalysisUrl {
            try sdkValidateUri("next_analysis_url", value)
        }
        if let value = self.confirmDeleteUrl {
            try sdkValidateUri("confirm_delete_url", value)
        }
    }
}

/// Typed representation of the `CodeScanningAnalysisTool` API schema.
public struct CodeScanningAnalysisTool: Codable {
    /// The name of the tool used to generate the code scanning analysis.
    public var name: CodeScanningAnalysisToolName?
    /// The version of the tool used to generate the code scanning analysis.
    public var version: CodeScanningAnalysisToolVersion?
    /// The GUID of the tool used to generate the code scanning analysis, if provided in the uploaded SARIF data.
    public var guid: CodeScanningAnalysisToolGuid?

    enum CodingKeys: String, CodingKey {
        case name
        case version
        case guid
    }

    init() {
        (name, version, guid) = (nil, nil, nil)
    }
}

public extension CodeScanningAnalysisTool {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        name = try container.sdkDecodeIfPresent(.name)
        version = try container.sdkDecodeIfPresent(.version)
        guid = try container.sdkDecodeIfPresent(.guid)
    }
}

public extension CodeScanningAnalysisTool {
    init(
        name: CodeScanningAnalysisToolName? = nil,
        version: CodeScanningAnalysisToolVersion? = nil,
        guid: CodeScanningAnalysisToolGuid? = nil
    ) {
        self.init()
        (self.name, self.version) = (name, version)
        self.guid = guid
    }
}
