// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// CodeScanningCodeScanning domain models
public typealias CodeScanningRefFull = String

/// A CodeQL database.
public struct CodeScanningCodeqlDatabase: Codable {
    /// The ID of the CodeQL database.
    public var id: Int
    /// The name of the CodeQL database.
    public var name: String
    /// The language of the CodeQL database.
    public var language: String
    /// A GitHub user.
    public var uploader: SimpleUser
    /// The MIME type of the CodeQL database file.
    public var contentType: String
    /// The size of the CodeQL database file in bytes.
    public var size: Int
    /// The date and time at which the CodeQL database was created, in ISO 8601 format':' YYYY-MM-DDTHH:MM:SSZ.
    public var createdAt: Date
    /// The date and time at which the CodeQL database was last updated, in ISO 8601 format':' YYYY-MM-DDTHH:MM:SSZ.
    public var updatedAt: Date
    /// The URL at which to download the CodeQL database. The `Accept` header must be set to the value of the
    /// `content_type` property.
    public var url: String
    /// The commit SHA of the repository at the time the CodeQL database was created.
    public var commitOid: String?

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case language
        case uploader
        case contentType = "content_type"
        case size
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case url
        case commitOid = "commit_oid"
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension CodeScanningCodeqlDatabase {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.sdkDecodeRequired(.id)
        name = try container.sdkDecodeRequired(.name)
        language = try container.sdkDecodeRequired(.language)
        uploader = try container.sdkDecodeRequired(.uploader)
        contentType = try container.sdkDecodeRequired(.contentType)
        size = try container.sdkDecodeRequired(.size)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        updatedAt = try container.sdkDecodeRequired(.updatedAt)
        url = try container.sdkDecodeRequired(.url)
        commitOid = try container.sdkDecodeIfPresent(.commitOid)
        try sdkValidateDateTime("created_at", sdkWireString(createdAt))
        try sdkValidateDateTime("updated_at", sdkWireString(updatedAt))
        try sdkValidateUri("url", url)
    }
}

public extension CodeScanningCodeqlDatabase {
    init(
        id: Int,
        name: String,
        language: String,
        uploader: SimpleUser,
        contentType: String,
        size: Int,
        createdAt: Date,
        updatedAt: Date,
        url: String,
        commitOid: String? = nil
    ) throws {
        (self.id, self.name) = (id, name)
        (self.language, self.uploader) = (language, uploader)
        (self.contentType, self.size) = (contentType, size)
        (self.createdAt, self.updatedAt) = (createdAt, updatedAt)
        (self.url, self.commitOid) = (url, commitOid)
        try sdkValidateDateTime("created_at", sdkWireString(self.createdAt))
        try sdkValidateDateTime("updated_at", sdkWireString(self.updatedAt))
        try sdkValidateUri("url", self.url)
    }
}

/// Typed representation of the `CodeScanningOrganizationAlertItems` API schema.
public struct CodeScanningOrganizationAlertItems: Codable {
    /// The security alert number.
    public var number: AlertNumber
    /// The time that the alert was created in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var createdAt: AlertCreatedAt
    /// The REST API URL of the alert resource.
    public var url: AlertUrl
    /// The GitHub URL of the alert resource.
    public var htmlUrl: AlertHtmlUrl
    /// The REST API URL for fetching the list of instances for an alert.
    public var instancesUrl: AlertInstancesUrl
    /// State of a code scanning alert.
    public var state: CodeScanningAlertState?
    /// A GitHub user.
    public var dismissedBy: NullableSimpleUser?
    /// The time that the alert was dismissed in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var dismissedAt: AlertDismissedAt?
    /// **Required when the state is dismissed.** The reason for dismissing or closing the alert.
    public var dismissedReason: CodeScanningAlertDismissedReason?
    /// Required object value serialized in the `rule` wire field.
    public var rule: CodeScanningAlertRuleSummary
    /// Required object value serialized in the `tool` wire field.
    public var tool: CodeScanningAnalysisTool
    /// Required object value serialized in the `most_recent_instance` wire field.
    public var mostRecentInstance: CodeScanningAlertInstance
    /// A GitHub repository.
    public var repository: SimpleRepository
    /// The time that the alert was last updated in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var updatedAt: AlertUpdatedAt?
    /// The time that the alert was no longer detected and was considered fixed in ISO 8601 format:
    /// `YYYY-MM-DDTHH:MM:SSZ`.
    public var fixedAt: AlertFixedAt?
    /// The dismissal comment associated with the dismissal of the alert.
    public var dismissedComment: CodeScanningAlertDismissedComment?
    /// A GitHub user.
    public var dismissalApprovedBy: NullableSimpleUser?
    /// Optional array value serialized in the `assignees` wire field.
    public var assignees: [SimpleUser]?

    enum CodingKeys: String, CodingKey {
        case number
        case createdAt = "created_at"
        case url
        case htmlUrl = "html_url"
        case instancesUrl = "instances_url"
        case state
        case dismissedBy = "dismissed_by"
        case dismissedAt = "dismissed_at"
        case dismissedReason = "dismissed_reason"
        case rule
        case tool
        case mostRecentInstance = "most_recent_instance"
        case repository
        case updatedAt = "updated_at"
        case fixedAt = "fixed_at"
        case dismissedComment = "dismissed_comment"
        case dismissalApprovedBy = "dismissal_approved_by"
        case assignees
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension CodeScanningOrganizationAlertItems {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        number = try container.sdkDecodeRequired(.number)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        url = try container.sdkDecodeRequired(.url)
        htmlUrl = try container.sdkDecodeRequired(.htmlUrl)
        instancesUrl = try container.sdkDecodeRequired(.instancesUrl)
        state = try container.sdkDecodeIfPresent(.state)
        dismissedBy = try container.sdkDecodeIfPresent(.dismissedBy)
        dismissedAt = try container.sdkDecodeIfPresent(.dismissedAt)
        dismissedReason = try container.sdkDecodeIfPresent(.dismissedReason)
        rule = try container.sdkDecodeRequired(.rule)
        tool = try container.sdkDecodeRequired(.tool)
        mostRecentInstance = try container.sdkDecodeRequired(.mostRecentInstance)
        repository = try container.sdkDecodeRequired(.repository)
        updatedAt = try container.sdkDecodeIfPresent(.updatedAt)
        fixedAt = try container.sdkDecodeIfPresent(.fixedAt)
        dismissedComment = try container.sdkDecodeIfPresent(.dismissedComment)
        dismissalApprovedBy = try container.sdkDecodeIfPresent(.dismissalApprovedBy)
        assignees = try container.sdkDecodeIfPresent(.assignees)
        try sdkValidateConstraints()
    }
}

public extension CodeScanningOrganizationAlertItems {
    init(
        number: AlertNumber,
        createdAt: AlertCreatedAt,
        url: AlertUrl,
        htmlUrl: AlertHtmlUrl,
        instancesUrl: AlertInstancesUrl,
        state: CodeScanningAlertState?,
        dismissedBy: NullableSimpleUser?,
        dismissedAt: AlertDismissedAt?,
        dismissedReason: CodeScanningAlertDismissedReason?,
        rule: CodeScanningAlertRuleSummary,
        tool: CodeScanningAnalysisTool,
        mostRecentInstance: CodeScanningAlertInstance,
        repository: SimpleRepository,
        updatedAt: AlertUpdatedAt? = nil,
        fixedAt: AlertFixedAt? = nil,
        dismissedComment: CodeScanningAlertDismissedComment? = nil,
        dismissalApprovedBy: NullableSimpleUser? = nil,
        assignees: [SimpleUser]? = nil
    ) throws {
        (self.number, self.createdAt) = (number, createdAt)
        (self.url, self.htmlUrl) = (url, htmlUrl)
        (self.instancesUrl, self.state) = (instancesUrl, state)
        (self.dismissedBy, self.dismissedAt) = (dismissedBy, dismissedAt)
        (self.dismissedReason, self.rule) = (dismissedReason, rule)
        (self.tool, self.mostRecentInstance) = (tool, mostRecentInstance)
        (self.repository, self.updatedAt) = (repository, updatedAt)
        (self.fixedAt, self.dismissedComment) = (fixedAt, dismissedComment)
        (self.dismissalApprovedBy, self.assignees) = (dismissalApprovedBy, assignees)
        try sdkValidateConstraints()
    }
}

extension CodeScanningOrganizationAlertItems {
    func sdkValidateConstraints() throws {
        try sdkValidateDateTime("created_at", sdkWireString(createdAt))
        try sdkValidateUri("url", sdkWireString(url))
        try sdkValidateUri("html_url", sdkWireString(htmlUrl))
        try sdkValidateUri("instances_url", sdkWireString(instancesUrl))
        if let value = dismissedAt {
            try sdkValidateDateTime("dismissed_at", sdkWireString(value))
        }
        if let value = updatedAt {
            try sdkValidateDateTime("updated_at", sdkWireString(value))
        }
        if let value = fixedAt {
            try sdkValidateDateTime("fixed_at", sdkWireString(value))
        }
        if let value = dismissedComment {
            try validateLength("dismissed_comment", sdkWireString(value), min: nil, max: 280)
        }
    }
}
