// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// CodeScanningCodeScanningAlert domain models
public typealias CodeScanningAlertAssignees = [String]

public typealias CodeScanningAlertCreateRequest = Bool

public typealias CodeScanningAlertDismissedComment = String

public typealias CodeScanningAlertEnvironment = String

/// Typed representation of the `CodeScanningAlert` API schema.
public struct CodeScanningAlert: Codable {
    /// The security alert number.
    public var number: AlertNumber
    /// The time that the alert was created in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var createdAt: AlertCreatedAt
    /// The REST API URL of the alert resource.
    public var url: AlertUrl
    /// The GitHub URL of the alert resource.
    public var htmlUrl: AlertHtmlUrl
    /// The REST API URL for fetching the list of instances for an alert.
    public var instancesUrl: AlertInstancesUrl
    /// State of a code scanning alert.
    public var state: CodeScanningAlertState?
    /// A GitHub user.
    public var dismissedBy: NullableSimpleUser?
    /// The time that the alert was dismissed in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var dismissedAt: AlertDismissedAt?
    /// **Required when the state is dismissed.** The reason for dismissing or closing the alert.
    public var dismissedReason: CodeScanningAlertDismissedReason?
    /// Required object value serialized in the `rule` wire field.
    public var rule: CodeScanningAlertRule
    /// Required object value serialized in the `tool` wire field.
    public var tool: CodeScanningAnalysisTool
    /// Required object value serialized in the `most_recent_instance` wire field.
    public var mostRecentInstance: CodeScanningAlertInstance
    /// The time that the alert was last updated in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var updatedAt: AlertUpdatedAt?
    /// The time that the alert was no longer detected and was considered fixed in ISO 8601 format:
    /// `YYYY-MM-DDTHH:MM:SSZ`.
    public var fixedAt: AlertFixedAt?
    /// The dismissal comment associated with the dismissal of the alert.
    public var dismissedComment: CodeScanningAlertDismissedComment?
    /// A GitHub user.
    public var dismissalApprovedBy: NullableSimpleUser?
    /// Optional array value serialized in the `assignees` wire field.
    public var assignees: [SimpleUser]?
    /// Pull requests linked to this alert.
    public var linkedPullRequests: [PullRequestSimple]?

    enum CodingKeys: String, CodingKey {
        case number
        case createdAt = "created_at"
        case url
        case htmlUrl = "html_url"
        case instancesUrl = "instances_url"
        case state
        case dismissedBy = "dismissed_by"
        case dismissedAt = "dismissed_at"
        case dismissedReason = "dismissed_reason"
        case rule
        case tool
        case mostRecentInstance = "most_recent_instance"
        case updatedAt = "updated_at"
        case fixedAt = "fixed_at"
        case dismissedComment = "dismissed_comment"
        case dismissalApprovedBy = "dismissal_approved_by"
        case assignees
        case linkedPullRequests = "linked_pull_requests"
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension CodeScanningAlert {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        number = try container.sdkDecodeRequired(.number)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        url = try container.sdkDecodeRequired(.url)
        htmlUrl = try container.sdkDecodeRequired(.htmlUrl)
        instancesUrl = try container.sdkDecodeRequired(.instancesUrl)
        state = try container.sdkDecodeIfPresent(.state)
        dismissedBy = try container.sdkDecodeIfPresent(.dismissedBy)
        dismissedAt = try container.sdkDecodeIfPresent(.dismissedAt)
        dismissedReason = try container.sdkDecodeIfPresent(.dismissedReason)
        rule = try container.sdkDecodeRequired(.rule)
        tool = try container.sdkDecodeRequired(.tool)
        mostRecentInstance = try container.sdkDecodeRequired(.mostRecentInstance)
        updatedAt = try container.sdkDecodeIfPresent(.updatedAt)
        fixedAt = try container.sdkDecodeIfPresent(.fixedAt)
        dismissedComment = try container.sdkDecodeIfPresent(.dismissedComment)
        dismissalApprovedBy = try container.sdkDecodeIfPresent(.dismissalApprovedBy)
        assignees = try container.sdkDecodeIfPresent(.assignees)
        linkedPullRequests = try container.sdkDecodeIfPresent(.linkedPullRequests)
        try sdkValidateConstraints()
    }
}

public extension CodeScanningAlert {
    init(
        number: AlertNumber,
        createdAt: AlertCreatedAt,
        url: AlertUrl,
        htmlUrl: AlertHtmlUrl,
        instancesUrl: AlertInstancesUrl,
        state: CodeScanningAlertState?,
        dismissedBy: NullableSimpleUser?,
        dismissedAt: AlertDismissedAt?,
        dismissedReason: CodeScanningAlertDismissedReason?,
        rule: CodeScanningAlertRule,
        tool: CodeScanningAnalysisTool,
        mostRecentInstance: CodeScanningAlertInstance,
        updatedAt: AlertUpdatedAt? = nil,
        fixedAt: AlertFixedAt? = nil,
        dismissedComment: CodeScanningAlertDismissedComment? = nil,
        dismissalApprovedBy: NullableSimpleUser? = nil,
        assignees: [SimpleUser]? = nil,
        linkedPullRequests: [PullRequestSimple]? = nil
    ) throws {
        (self.number, self.createdAt) = (number, createdAt)
        (self.url, self.htmlUrl) = (url, htmlUrl)
        (self.instancesUrl, self.state) = (instancesUrl, state)
        (self.dismissedBy, self.dismissedAt) = (dismissedBy, dismissedAt)
        (self.dismissedReason, self.rule) = (dismissedReason, rule)
        (self.tool, self.mostRecentInstance) = (tool, mostRecentInstance)
        (self.updatedAt, self.fixedAt) = (updatedAt, fixedAt)
        (self.dismissedComment, self.dismissalApprovedBy) = (dismissedComment, dismissalApprovedBy)
        (self.assignees, self.linkedPullRequests) = (assignees, linkedPullRequests)
        try sdkValidateConstraints()
    }
}

extension CodeScanningAlert {
    func sdkValidateConstraints() throws {
        try sdkValidateDateTime("created_at", sdkWireString(createdAt))
        try sdkValidateUri("url", sdkWireString(url))
        try sdkValidateUri("html_url", sdkWireString(htmlUrl))
        try sdkValidateUri("instances_url", sdkWireString(instancesUrl))
        if let value = dismissedAt {
            try sdkValidateDateTime("dismissed_at", sdkWireString(value))
        }
        if let value = updatedAt {
            try sdkValidateDateTime("updated_at", sdkWireString(value))
        }
        if let value = fixedAt {
            try sdkValidateDateTime("fixed_at", sdkWireString(value))
        }
        if let value = dismissedComment {
            try validateLength("dismissed_comment", sdkWireString(value), min: nil, max: 280)
        }
    }
}

/// Typed representation of the `CodeScanningAlertInstance` API schema.
public struct CodeScanningAlertInstance: Codable {
    /// The Git reference, formatted as `refs/pull/<number>/merge`, `refs/pull/<number>/head`, `refs/heads/<branch
    /// name>` or simply `<branch name>`.
    public var ref: CodeScanningRef?
    /// Identifies the configuration under which the analysis was executed. For example, in GitHub Actions this
    /// includes the workflow filename and job name.
    public var analysisKey: CodeScanningAnalysisAnalysisKey?
    /// Identifies the variable values associated with the environment in which the analysis that generated this
    /// alert instance was performed, such as the language that was analyzed.
    public var environment: CodeScanningAlertEnvironment?
    /// Identifies the configuration under which the analysis was executed. Used to distinguish between multiple
    /// analyses for the same tool and commit, but performed on different languages or different parts of the code.
    public var category: CodeScanningAnalysisCategory?
    /// State of a code scanning alert.
    public var state: CodeScanningAlertState?
    /// Optional `string` value serialized in the `commit_sha` wire field.
    public var commitSha: String?
    /// Optional object value serialized in the `message` wire field.
    public var message: CodeScanningAlertInstanceMessage?
    /// Describe a region within a file for the alert.
    public var location: CodeScanningAlertLocation?
    /// Optional `string` value serialized in the `html_url` wire field.
    public var htmlUrl: String?
    /// Classifications that have been applied to the file that triggered the alert. For example identifying it as
    /// documentation, or a generated file.
    public var classifications: [CodeScanningAlertClassification?]?

    enum CodingKeys: String, CodingKey {
        case ref
        case analysisKey = "analysis_key"
        case environment
        case category
        case state
        case commitSha = "commit_sha"
        case message
        case location
        case htmlUrl = "html_url"
        case classifications
    }

    init() {
        (ref, analysisKey, environment, category, state) = (nil, nil, nil, nil, nil)
        (commitSha, message, location, htmlUrl, classifications) = (nil, nil, nil, nil, nil)
    }
}

public extension CodeScanningAlertInstance {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        ref = try container.sdkDecodeIfPresent(.ref)
        analysisKey = try container.sdkDecodeIfPresent(.analysisKey)
        environment = try container.sdkDecodeIfPresent(.environment)
        category = try container.sdkDecodeIfPresent(.category)
        state = try container.sdkDecodeIfPresent(.state)
        commitSha = try container.sdkDecodeIfPresent(.commitSha)
        message = try container.sdkDecodeIfPresent(.message)
        location = try container.sdkDecodeIfPresent(.location)
        htmlUrl = try container.sdkDecodeIfPresent(.htmlUrl)
        classifications = try container.sdkDecodeIfPresent(.classifications)
    }
}

public extension CodeScanningAlertInstance {
    init(
        ref: CodeScanningRef? = nil,
        analysisKey: CodeScanningAnalysisAnalysisKey? = nil,
        environment: CodeScanningAlertEnvironment? = nil,
        category: CodeScanningAnalysisCategory? = nil,
        state: CodeScanningAlertState? = nil,
        commitSha: String? = nil,
        message: CodeScanningAlertInstanceMessage? = nil,
        location: CodeScanningAlertLocation? = nil,
        htmlUrl: String? = nil,
        classifications: [CodeScanningAlertClassification?]? = nil
    ) {
        self.init()
        (self.ref, self.analysisKey) = (ref, analysisKey)
        (self.environment, self.category) = (environment, category)
        (self.state, self.commitSha) = (state, commitSha)
        (self.message, self.location) = (message, location)
        (self.htmlUrl, self.classifications) = (htmlUrl, classifications)
    }
}

/// Optional object value serialized in the `message` wire field.
public struct CodeScanningAlertInstanceMessage: Codable {
    /// Optional `string` value serialized in the `text` wire field.
    public var text: String?
    /// The message text as GitHub-flavored Markdown, with placeholder links for related locations replaced by links
    /// to the relevant code. Only populated when related locations are available for the alert instance.
    public var markdown: String?

    enum CodingKeys: String, CodingKey {
        case text
        case markdown
    }

    init() {
        (text, markdown) = (nil, nil)
    }
}

public extension CodeScanningAlertInstanceMessage {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        text = try container.sdkDecodeIfPresent(.text)
        markdown = try container.sdkDecodeIfPresent(.markdown)
    }
}

public extension CodeScanningAlertInstanceMessage {
    init(text: String? = nil, markdown: String? = nil) {
        self.init()
        (self.text, self.markdown) = (text, markdown)
    }
}

/// Typed representation of the `CodeScanningAlertInstanceList` API schema.
public struct CodeScanningAlertInstanceList: Codable {
    /// The Git reference, formatted as `refs/pull/<number>/merge`, `refs/pull/<number>/head`, `refs/heads/<branch
    /// name>` or simply `<branch name>`.
    public var ref: CodeScanningRef?
    /// Identifies the configuration under which the analysis was executed. For example, in GitHub Actions this
    /// includes the workflow filename and job name.
    public var analysisKey: CodeScanningAnalysisAnalysisKey?
    /// Identifies the variable values associated with the environment in which the analysis that generated this
    /// alert instance was performed, such as the language that was analyzed.
    public var environment: CodeScanningAlertEnvironment?
    /// Identifies the configuration under which the analysis was executed. Used to distinguish between multiple
    /// analyses for the same tool and commit, but performed on different languages or different parts of the code.
    public var category: CodeScanningAnalysisCategory?
    /// State of a code scanning alert instance.
    public var state: CodeScanningAlertInstanceState?
    /// Optional `string` value serialized in the `commit_sha` wire field.
    public var commitSha: String?
    /// Optional object value serialized in the `message` wire field.
    public var message: CodeScanningAlertInstanceListMessage?
    /// Describe a region within a file for the alert.
    public var location: CodeScanningAlertLocation?
    /// Optional `string` value serialized in the `html_url` wire field.
    public var htmlUrl: String?
    /// Classifications that have been applied to the file that triggered the alert. For example identifying it as
    /// documentation, or a generated file.
    public var classifications: [CodeScanningAlertClassification?]?

    enum CodingKeys: String, CodingKey {
        case ref
        case analysisKey = "analysis_key"
        case environment
        case category
        case state
        case commitSha = "commit_sha"
        case message
        case location
        case htmlUrl = "html_url"
        case classifications
    }

    init() {
        (ref, analysisKey, environment, category, state) = (nil, nil, nil, nil, nil)
        (commitSha, message, location, htmlUrl, classifications) = (nil, nil, nil, nil, nil)
    }
}

public extension CodeScanningAlertInstanceList {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        ref = try container.sdkDecodeIfPresent(.ref)
        analysisKey = try container.sdkDecodeIfPresent(.analysisKey)
        environment = try container.sdkDecodeIfPresent(.environment)
        category = try container.sdkDecodeIfPresent(.category)
        state = try container.sdkDecodeIfPresent(.state)
        commitSha = try container.sdkDecodeIfPresent(.commitSha)
        message = try container.sdkDecodeIfPresent(.message)
        location = try container.sdkDecodeIfPresent(.location)
        htmlUrl = try container.sdkDecodeIfPresent(.htmlUrl)
        classifications = try container.sdkDecodeIfPresent(.classifications)
    }
}

public extension CodeScanningAlertInstanceList {
    init(
        ref: CodeScanningRef? = nil,
        analysisKey: CodeScanningAnalysisAnalysisKey? = nil,
        environment: CodeScanningAlertEnvironment? = nil,
        category: CodeScanningAnalysisCategory? = nil,
        state: CodeScanningAlertInstanceState? = nil,
        commitSha: String? = nil,
        message: CodeScanningAlertInstanceListMessage? = nil,
        location: CodeScanningAlertLocation? = nil,
        htmlUrl: String? = nil,
        classifications: [CodeScanningAlertClassification?]? = nil
    ) {
        self.init()
        (self.ref, self.analysisKey) = (ref, analysisKey)
        (self.environment, self.category) = (environment, category)
        (self.state, self.commitSha) = (state, commitSha)
        (self.message, self.location) = (message, location)
        (self.htmlUrl, self.classifications) = (htmlUrl, classifications)
    }
}

/// Optional object value serialized in the `message` wire field.
public struct CodeScanningAlertInstanceListMessage: Codable {
    /// Optional `string` value serialized in the `text` wire field.
    public var text: String?

    enum CodingKeys: String, CodingKey {
        case text
    }

    init() {
        text = nil
    }
}

public extension CodeScanningAlertInstanceListMessage {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        text = try container.sdkDecodeIfPresent(.text)
    }
}

public extension CodeScanningAlertInstanceListMessage {
    init(text: String? = nil) {
        self.init()
        self.text = text
    }
}

/// Typed representation of the `CodeScanningAlertItems` API schema.
public struct CodeScanningAlertItems: Codable {
    /// The security alert number.
    public var number: AlertNumber
    /// The time that the alert was created in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var createdAt: AlertCreatedAt
    /// The REST API URL of the alert resource.
    public var url: AlertUrl
    /// The GitHub URL of the alert resource.
    public var htmlUrl: AlertHtmlUrl
    /// The REST API URL for fetching the list of instances for an alert.
    public var instancesUrl: AlertInstancesUrl
    /// State of a code scanning alert.
    public var state: CodeScanningAlertState?
    /// A GitHub user.
    public var dismissedBy: NullableSimpleUser?
    /// The time that the alert was dismissed in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var dismissedAt: AlertDismissedAt?
    /// **Required when the state is dismissed.** The reason for dismissing or closing the alert.
    public var dismissedReason: CodeScanningAlertDismissedReason?
    /// Required object value serialized in the `rule` wire field.
    public var rule: CodeScanningAlertRuleSummary
    /// Required object value serialized in the `tool` wire field.
    public var tool: CodeScanningAnalysisTool
    /// Required object value serialized in the `most_recent_instance` wire field.
    public var mostRecentInstance: CodeScanningAlertInstance
    /// The time that the alert was last updated in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var updatedAt: AlertUpdatedAt?
    /// The time that the alert was no longer detected and was considered fixed in ISO 8601 format:
    /// `YYYY-MM-DDTHH:MM:SSZ`.
    public var fixedAt: AlertFixedAt?
    /// The dismissal comment associated with the dismissal of the alert.
    public var dismissedComment: CodeScanningAlertDismissedComment?
    /// A GitHub user.
    public var dismissalApprovedBy: NullableSimpleUser?
    /// Optional array value serialized in the `assignees` wire field.
    public var assignees: [SimpleUser]?

    enum CodingKeys: String, CodingKey {
        case number
        case createdAt = "created_at"
        case url
        case htmlUrl = "html_url"
        case instancesUrl = "instances_url"
        case state
        case dismissedBy = "dismissed_by"
        case dismissedAt = "dismissed_at"
        case dismissedReason = "dismissed_reason"
        case rule
        case tool
        case mostRecentInstance = "most_recent_instance"
        case updatedAt = "updated_at"
        case fixedAt = "fixed_at"
        case dismissedComment = "dismissed_comment"
        case dismissalApprovedBy = "dismissal_approved_by"
        case assignees
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension CodeScanningAlertItems {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        number = try container.sdkDecodeRequired(.number)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        url = try container.sdkDecodeRequired(.url)
        htmlUrl = try container.sdkDecodeRequired(.htmlUrl)
        instancesUrl = try container.sdkDecodeRequired(.instancesUrl)
        state = try container.sdkDecodeIfPresent(.state)
        dismissedBy = try container.sdkDecodeIfPresent(.dismissedBy)
        dismissedAt = try container.sdkDecodeIfPresent(.dismissedAt)
        dismissedReason = try container.sdkDecodeIfPresent(.dismissedReason)
        rule = try container.sdkDecodeRequired(.rule)
        tool = try container.sdkDecodeRequired(.tool)
        mostRecentInstance = try container.sdkDecodeRequired(.mostRecentInstance)
        updatedAt = try container.sdkDecodeIfPresent(.updatedAt)
        fixedAt = try container.sdkDecodeIfPresent(.fixedAt)
        dismissedComment = try container.sdkDecodeIfPresent(.dismissedComment)
        dismissalApprovedBy = try container.sdkDecodeIfPresent(.dismissalApprovedBy)
        assignees = try container.sdkDecodeIfPresent(.assignees)
        try sdkValidateConstraints()
    }
}

public extension CodeScanningAlertItems {
    init(
        number: AlertNumber,
        createdAt: AlertCreatedAt,
        url: AlertUrl,
        htmlUrl: AlertHtmlUrl,
        instancesUrl: AlertInstancesUrl,
        state: CodeScanningAlertState?,
        dismissedBy: NullableSimpleUser?,
        dismissedAt: AlertDismissedAt?,
        dismissedReason: CodeScanningAlertDismissedReason?,
        rule: CodeScanningAlertRuleSummary,
        tool: CodeScanningAnalysisTool,
        mostRecentInstance: CodeScanningAlertInstance,
        updatedAt: AlertUpdatedAt? = nil,
        fixedAt: AlertFixedAt? = nil,
        dismissedComment: CodeScanningAlertDismissedComment? = nil,
        dismissalApprovedBy: NullableSimpleUser? = nil,
        assignees: [SimpleUser]? = nil
    ) throws {
        (self.number, self.createdAt) = (number, createdAt)
        (self.url, self.htmlUrl) = (url, htmlUrl)
        (self.instancesUrl, self.state) = (instancesUrl, state)
        (self.dismissedBy, self.dismissedAt) = (dismissedBy, dismissedAt)
        (self.dismissedReason, self.rule) = (dismissedReason, rule)
        (self.tool, self.mostRecentInstance) = (tool, mostRecentInstance)
        (self.updatedAt, self.fixedAt) = (updatedAt, fixedAt)
        (self.dismissedComment, self.dismissalApprovedBy) = (dismissedComment, dismissalApprovedBy)
        self.assignees = assignees
        try sdkValidateConstraints()
    }
}

extension CodeScanningAlertItems {
    func sdkValidateConstraints() throws {
        try sdkValidateDateTime("created_at", sdkWireString(createdAt))
        try sdkValidateUri("url", sdkWireString(url))
        try sdkValidateUri("html_url", sdkWireString(htmlUrl))
        try sdkValidateUri("instances_url", sdkWireString(instancesUrl))
        if let value = dismissedAt {
            try sdkValidateDateTime("dismissed_at", sdkWireString(value))
        }
        if let value = updatedAt {
            try sdkValidateDateTime("updated_at", sdkWireString(value))
        }
        if let value = fixedAt {
            try sdkValidateDateTime("fixed_at", sdkWireString(value))
        }
        if let value = dismissedComment {
            try validateLength("dismissed_comment", sdkWireString(value), min: nil, max: 280)
        }
    }
}

/// Describe a region within a file for the alert.
public struct CodeScanningAlertLocation: Codable {
    /// Optional `string` value serialized in the `path` wire field.
    public var path: String?
    /// Optional `integer` value serialized in the `start_line` wire field.
    public var startLine: Int?
    /// Optional `integer` value serialized in the `end_line` wire field.
    public var endLine: Int?
    /// Optional `integer` value serialized in the `start_column` wire field.
    public var startColumn: Int?
    /// Optional `integer` value serialized in the `end_column` wire field.
    public var endColumn: Int?

    enum CodingKeys: String, CodingKey {
        case path
        case startLine = "start_line"
        case endLine = "end_line"
        case startColumn = "start_column"
        case endColumn = "end_column"
    }

    init() {
        (path, startLine, endLine, startColumn, endColumn) = (nil, nil, nil, nil, nil)
    }
}

public extension CodeScanningAlertLocation {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        path = try container.sdkDecodeIfPresent(.path)
        startLine = try container.sdkDecodeIfPresent(.startLine)
        endLine = try container.sdkDecodeIfPresent(.endLine)
        startColumn = try container.sdkDecodeIfPresent(.startColumn)
        endColumn = try container.sdkDecodeIfPresent(.endColumn)
    }
}

public extension CodeScanningAlertLocation {
    init(
        path: String? = nil,
        startLine: Int? = nil,
        endLine: Int? = nil,
        startColumn: Int? = nil,
        endColumn: Int? = nil
    ) {
        self.init()
        (self.path, self.startLine) = (path, startLine)
        (self.endLine, self.startColumn) = (endLine, startColumn)
        self.endColumn = endColumn
    }
}

/// Typed representation of the `CodeScanningAlertRule` API schema.
public struct CodeScanningAlertRule: Codable {
    /// A unique identifier for the rule used to detect the alert.
    public var id: String?
    /// The name of the rule used to detect the alert.
    public var name: String?
    /// The severity of the alert.
    public var severity: CodeScanningAlertRuleSeverity?
    /// The security severity of the alert.
    public var securitySeverityLevel: CodeScanningAlertRuleSecuritySeverityLevel?
    /// A short description of the rule used to detect the alert.
    public var description: String?
    /// A description of the rule used to detect the alert.
    public var fullDescription: String?
    /// A set of tags applicable for the rule.
    public var tags: [String]?
    /// Detailed documentation for the rule as GitHub Flavored Markdown.
    public var help: String?
    /// A link to the documentation for the rule used to detect the alert.
    public var helpUri: String?

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case severity
        case securitySeverityLevel = "security_severity_level"
        case description
        case fullDescription = "full_description"
        case tags
        case help
        case helpUri = "help_uri"
    }

    init() {
        (id, name, severity, securitySeverityLevel, description) = (nil, nil, nil, nil, nil)
        (fullDescription, tags, help, helpUri) = (nil, nil, nil, nil)
    }
}
