// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

// Dependabot domain models
public extension DependabotAlertSecurityAdvisoryReferencesItem {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.url) else {
            throw SdkValidationError(field: "url", code: "required", message: "Validation failed for 'url': value is required")
        }
        self.url = try container.sdkDecodeRequired(.url)
            try sdkValidateUri("url", self.url)
    }
}

public extension DependabotAlertSecurityAdvisoryReferencesItem {
    public init(url: String) throws {
        self.url = url
            try sdkValidateUri("url", self.url)
    }
}

/// Details pertaining to one vulnerable version range for the advisory.
public struct DependabotAlertSecurityVulnerability: Codable {
    /// Details for the vulnerable package.
    public var package: DependabotAlertPackage
    /// The severity of the vulnerability.
    public var severity: DependabotAlertSecurityVulnerabilitySeverity
    /// Conditions that identify vulnerable versions of this vulnerability's package.
    public var vulnerableVersionRange: String
    /// Details pertaining to the package version that patches this vulnerability.
    public var firstPatchedVersion: DependabotAlertSecurityVulnerabilityFirstPatchedVersion?

    enum CodingKeys: String, CodingKey {
        case package
        case severity
        case vulnerableVersionRange = "vulnerable_version_range"
        case firstPatchedVersion = "first_patched_version"
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension DependabotAlertSecurityVulnerability {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.package) else {
            throw SdkValidationError(field: "package", code: "required", message: "Validation failed for 'package': value is required")
        }
        guard container.contains(.severity) else {
            throw SdkValidationError(field: "severity", code: "required", message: "Validation failed for 'severity': value is required")
        }
        guard container.contains(.vulnerableVersionRange) else {
            throw SdkValidationError(field: "vulnerable_version_range", code: "required", message: "Validation failed for 'vulnerable_version_range': value is required")
        }
        guard container.contains(.firstPatchedVersion) else {
            throw SdkValidationError(field: "first_patched_version", code: "required", message: "Validation failed for 'first_patched_version': value is required")
        }
        self.package = try container.sdkDecodeRequired(.package)
        self.severity = try container.sdkDecodeRequired(.severity)
        self.vulnerableVersionRange = try container.sdkDecodeRequired(.vulnerableVersionRange)
        self.firstPatchedVersion = try container.sdkDecodeIfPresent(.firstPatchedVersion)
    }
}

public extension DependabotAlertSecurityVulnerability {
    public init(package: DependabotAlertPackage, severity: DependabotAlertSecurityVulnerabilitySeverity, vulnerableVersionRange: String, firstPatchedVersion: DependabotAlertSecurityVulnerabilityFirstPatchedVersion?) {
        (self.package, self.severity) = (package, severity)
        self.vulnerableVersionRange = vulnerableVersionRange
        self.firstPatchedVersion = firstPatchedVersion
    }
}

/// Details pertaining to the package version that patches this vulnerability.
public struct DependabotAlertSecurityVulnerabilityFirstPatchedVersion: Codable {
    /// The package version that patches this vulnerability.
    public var identifier: String

    enum CodingKeys: String, CodingKey {
        case identifier
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension DependabotAlertSecurityVulnerabilityFirstPatchedVersion {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.identifier) else {
            throw SdkValidationError(field: "identifier", code: "required", message: "Validation failed for 'identifier': value is required")
        }
        self.identifier = try container.sdkDecodeRequired(.identifier)
    }
}

public extension DependabotAlertSecurityVulnerabilityFirstPatchedVersion {
    public init(identifier: String) {
        self.identifier = identifier
    }
}

/// A Dependabot alert.
public struct DependabotAlertWithRepository: Codable {
    /// The security alert number.
    public var number: AlertNumber
    /// The state of the Dependabot alert.
    public var state: DependabotAlertWithRepositoryState
    /// Details for the vulnerable dependency.
    public var dependency: DependabotAlertWithRepositoryDependency
    /// Details for the GitHub Security Advisory.
    public var securityAdvisory: DependabotAlertSecurityAdvisory
    /// Details pertaining to one vulnerable version range for the advisory.
    public var securityVulnerability: DependabotAlertSecurityVulnerability
    /// The REST API URL of the alert resource.
    public var url: AlertUrl
    /// The GitHub URL of the alert resource.
    public var htmlUrl: AlertHtmlUrl
    /// The time that the alert was created in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var createdAt: AlertCreatedAt
    /// The time that the alert was last updated in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var updatedAt: AlertUpdatedAt
    /// The time that the alert was dismissed in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var dismissedAt: AlertDismissedAt?
    /// A GitHub user.
    public var dismissedBy: NullableSimpleUser?
    /// The reason that the alert was dismissed.
    public var dismissedReason: DependabotAlertWithRepositoryDismissedReason?
    /// An optional comment associated with the alert's dismissal.
    public var dismissedComment: String?
    /// The time that the alert was no longer detected and was considered fixed in ISO 8601 format:
    /// `YYYY-MM-DDTHH:MM:SSZ`.
    public var fixedAt: AlertFixedAt?
    /// A GitHub repository.
    public var repository: SimpleRepository
    /// The time that the alert was auto-dismissed in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
    public var autoDismissedAt: AlertAutoDismissedAt?
    /// Information about an active dismissal request for this Dependabot alert.
    public var dismissalRequest: DependabotAlertDismissalRequestSimple?
    /// The users assigned to this alert.
    public var assignees: [SimpleUser]?

    enum CodingKeys: String, CodingKey {
        case number
        case state
        case dependency
        case securityAdvisory = "security_advisory"
        case securityVulnerability = "security_vulnerability"
        case url
        case htmlUrl = "html_url"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case dismissedAt = "dismissed_at"
        case dismissedBy = "dismissed_by"
        case dismissedReason = "dismissed_reason"
        case dismissedComment = "dismissed_comment"
        case fixedAt = "fixed_at"
        case repository
        case autoDismissedAt = "auto_dismissed_at"
        case dismissalRequest = "dismissal_request"
        case assignees
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension DependabotAlertWithRepository {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.number = try container.sdkDecodeRequired(.number)
        self.state = try container.sdkDecodeRequired(.state)
        self.dependency = try container.sdkDecodeRequired(.dependency)
        self.securityAdvisory = try container.sdkDecodeRequired(.securityAdvisory)
        self.securityVulnerability = try container.sdkDecodeRequired(.securityVulnerability)
        self.url = try container.sdkDecodeRequired(.url)
        self.htmlUrl = try container.sdkDecodeRequired(.htmlUrl)
        self.createdAt = try container.sdkDecodeRequired(.createdAt)
        self.updatedAt = try container.sdkDecodeRequired(.updatedAt)
        self.dismissedAt = try container.sdkDecodeIfPresent(.dismissedAt)
        self.dismissedBy = try container.sdkDecodeIfPresent(.dismissedBy)
        self.dismissedReason = try container.sdkDecodeIfPresent(.dismissedReason)
        self.dismissedComment = try container.sdkDecodeIfPresent(.dismissedComment)
        self.fixedAt = try container.sdkDecodeIfPresent(.fixedAt)
        self.repository = try container.sdkDecodeRequired(.repository)
        self.autoDismissedAt = try container.sdkDecodeIfPresent(.autoDismissedAt)
        self.dismissalRequest = try container.sdkDecodeIfPresent(.dismissalRequest)
        self.assignees = try container.sdkDecodeIfPresent(.assignees)
        try sdkValidateConstraints()
    }
}

public extension DependabotAlertWithRepository {
    public init(number: AlertNumber, state: DependabotAlertWithRepositoryState, dependency: DependabotAlertWithRepositoryDependency, securityAdvisory: DependabotAlertSecurityAdvisory, securityVulnerability: DependabotAlertSecurityVulnerability, url: AlertUrl, htmlUrl: AlertHtmlUrl, createdAt: AlertCreatedAt, updatedAt: AlertUpdatedAt, dismissedAt: AlertDismissedAt?, dismissedBy: NullableSimpleUser?, dismissedReason: DependabotAlertWithRepositoryDismissedReason?, dismissedComment: String?, fixedAt: AlertFixedAt?, repository: SimpleRepository, autoDismissedAt: AlertAutoDismissedAt? = nil, dismissalRequest: DependabotAlertDismissalRequestSimple? = nil, assignees: [SimpleUser]? = nil) throws {
        (self.number, self.state) = (number, state)
        (self.dependency, self.securityAdvisory) = (dependency, securityAdvisory)
        (self.securityVulnerability, self.url) = (securityVulnerability, url)
        (self.htmlUrl, self.createdAt) = (htmlUrl, createdAt)
        (self.updatedAt, self.dismissedAt) = (updatedAt, dismissedAt)
        (self.dismissedBy, self.dismissedReason) = (dismissedBy, dismissedReason)
        (self.dismissedComment, self.fixedAt) = (dismissedComment, fixedAt)
        (self.repository, self.autoDismissedAt) = (repository, autoDismissedAt)
        (self.dismissalRequest, self.assignees) = (dismissalRequest, assignees)
        try sdkValidateConstraints()
    }
}

extension DependabotAlertWithRepository {
    func sdkValidateConstraints() throws {
            try sdkValidateUri("url", sdkWireString(self.url))
            try sdkValidateUri("html_url", sdkWireString(self.htmlUrl))
            try sdkValidateDateTime("created_at", sdkWireString(self.createdAt))
            try sdkValidateDateTime("updated_at", sdkWireString(self.updatedAt))
        if let value = self.dismissedAt {
            try sdkValidateDateTime("dismissed_at", sdkWireString(value))
        }
        if let value = self.dismissedComment {
            try validateLength("dismissed_comment", value, min: nil, max: 280)
        }
        if let value = self.fixedAt {
            try sdkValidateDateTime("fixed_at", sdkWireString(value))
        }
        if let value = self.autoDismissedAt {
            try sdkValidateDateTime("auto_dismissed_at", sdkWireString(value))
        }
    }
}

/// Details for the vulnerable dependency.
public struct DependabotAlertWithRepositoryDependency: Codable {
    /// Details for the vulnerable package.
    public var package: DependabotAlertPackage?
    /// The full path to the dependency manifest file, relative to the root of the repository.
    public var manifestPath: String?
    /// The execution scope of the vulnerable dependency.
    public var scope: DependabotAlertWithRepositoryDependencyScope?
    /// The vulnerable dependency's relationship to your project. > [!NOTE] > We are rolling out support for
    /// dependency relationship across ecosystems. This value will be "unknown" for all dependencies in unsupported
    /// ecosystems.
    public var relationship: DependabotAlertWithRepositoryDependencyRelationship?

    enum CodingKeys: String, CodingKey {
        case package
        case manifestPath = "manifest_path"
        case scope
        case relationship
    }

    init() {
        (self.package, self.manifestPath, self.scope, self.relationship) = (nil, nil, nil, nil)
    }
}

public extension DependabotAlertWithRepositoryDependency {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.package = try container.sdkDecodeIfPresent(.package)
        self.manifestPath = try container.sdkDecodeIfPresent(.manifestPath)
        self.scope = try container.sdkDecodeIfPresent(.scope)
        self.relationship = try container.sdkDecodeIfPresent(.relationship)
    }
}

public extension DependabotAlertWithRepositoryDependency {
    public init(package: DependabotAlertPackage? = nil, manifestPath: String? = nil, scope: DependabotAlertWithRepositoryDependencyScope? = nil, relationship: DependabotAlertWithRepositoryDependencyRelationship? = nil) {
        self.init()
        (self.package, self.manifestPath) = (package, manifestPath)
        (self.scope, self.relationship) = (scope, relationship)
    }
}

/// The public key used for setting Dependabot Secrets.
public struct DependabotPublicKey: Codable {
    /// The identifier for the key.
    /// - Example: "1234567"
    public var keyId: String
    /// The Base64 encoded public key.
    /// - Example: "hBT5WZEj8ZoOv6TYJsfWq7MxTEQopZO5/IT3ZCVQPzs="
    public var key: String

    enum CodingKeys: String, CodingKey {
        case keyId = "key_id"
        case key
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension DependabotPublicKey {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.keyId) else {
            throw SdkValidationError(field: "key_id", code: "required", message: "Validation failed for 'key_id': value is required")
        }
        guard container.contains(.key) else {
            throw SdkValidationError(field: "key", code: "required", message: "Validation failed for 'key': value is required")
        }
        self.keyId = try container.sdkDecodeRequired(.keyId)
        self.key = try container.sdkDecodeRequired(.key)
    }
}

public extension DependabotPublicKey {
    public init(keyId: String, key: String) {
        (self.keyId, self.key) = (keyId, key)
    }
}

/// Information about repositories that Dependabot is able to access in an organization
public struct DependabotRepositoryAccessDetails: Codable {
    /// The default repository access level for Dependabot updates.
    /// - Example: "internal"
    public var defaultLevel: DependabotRepositoryAccessDetailsDefaultLevel?
    /// Optional array value serialized in the `accessible_repositories` wire field.
    public var accessibleRepositories: [NullableSimpleRepository?]?

    enum CodingKeys: String, CodingKey {
        case defaultLevel = "default_level"
        case accessibleRepositories = "accessible_repositories"
    }

    init() {
        (self.defaultLevel, self.accessibleRepositories) = (nil, nil)
    }
}

public extension DependabotRepositoryAccessDetails {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.defaultLevel = try container.sdkDecodeIfPresent(.defaultLevel)
        self.accessibleRepositories = try container.sdkDecodeIfPresent(.accessibleRepositories)
    }
}

public extension DependabotRepositoryAccessDetails {
    public init(defaultLevel: DependabotRepositoryAccessDetailsDefaultLevel? = nil, accessibleRepositories: [NullableSimpleRepository?]? = nil) {
        self.init()
        (self.defaultLevel, self.accessibleRepositories) = (defaultLevel, accessibleRepositories)
    }
}

/// Set secrets for Dependabot.
public struct DependabotSecret: Codable {
    /// The name of the secret.
    /// - Example: "MY_ARTIFACTORY_PASSWORD"
    public var name: String
    /// Required `date-time`-formatted value serialized in the `created_at` wire field.
    public var createdAt: Date
    /// Required `date-time`-formatted value serialized in the `updated_at` wire field.
    public var updatedAt: Date

    enum CodingKeys: String, CodingKey {
        case name
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension DependabotSecret {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.name) else {
            throw SdkValidationError(field: "name", code: "required", message: "Validation failed for 'name': value is required")
        }
        guard container.contains(.createdAt) else {
            throw SdkValidationError(field: "created_at", code: "required", message: "Validation failed for 'created_at': value is required")
        }
        guard container.contains(.updatedAt) else {
            throw SdkValidationError(field: "updated_at", code: "required", message: "Validation failed for 'updated_at': value is required")
        }
        self.name = try container.sdkDecodeRequired(.name)
        self.createdAt = try container.sdkDecodeRequired(.createdAt)
        self.updatedAt = try container.sdkDecodeRequired(.updatedAt)
            try sdkValidateDateTime("created_at", sdkWireString(self.createdAt))
            try sdkValidateDateTime("updated_at", sdkWireString(self.updatedAt))
    }
}

public extension DependabotSecret {
    public init(name: String, createdAt: Date, updatedAt: Date) throws {
        (self.name, self.createdAt) = (name, createdAt)
        self.updatedAt = updatedAt
            try sdkValidateDateTime("created_at", sdkWireString(self.createdAt))
            try sdkValidateDateTime("updated_at", sdkWireString(self.updatedAt))
    }
}
