// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// IssuesIssue domain models
public extension IssueEventRename {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.from) else {
            throw SdkValidationError(
                field: "from",
                code: "required",
                message: "Validation failed for 'from': value is required"
            )
        }
        guard container.contains(.to) else {
            throw SdkValidationError(
                field: "to",
                code: "required",
                message: "Validation failed for 'to': value is required"
            )
        }
        from = try container.sdkDecodeRequired(.from)
        to = try container.sdkDecodeRequired(.to)
    }
}

public extension IssueEventRename {
    init(from: String, to: String) {
        (self.from, self.to) = (from, to)
    }
}

/// An agent-proposed change to an issue that a maintainer can approve or dismiss.
public struct IssueSuggestion: Codable {
    /// The unique identifier of the suggestion.
    public var id: Int
    /// The unique identifier of the issue the suggestion applies to.
    public var issueId: Int
    /// The kind of change proposed.
    public var action: IssueSuggestionAction
    /// The suggestion's lifecycle state.
    public var state: IssueSuggestionState
    /// The identifier of the target the change applies to (issue type, label, field, assignee, or duplicate issue),
    /// when applicable.
    public var targetId: Int?
    /// The proposed value, when applicable. An array for multi-select field suggestions.
    public var targetValue: IssueSuggestionTargetValue?
    /// The rationale the actor provided for the suggestion.
    public var rationale: String?
    /// The actor's confidence level in the suggestion.
    public var confidence: IssueSuggestionConfidence?
    /// The unique identifier of the actor that proposed the suggestion.
    public var actorId: Int?
    /// The identifier of the timeline event created when the suggestion was approved, when applicable.
    public var issueEventId: Int?
    /// The unique identifier of the user who approved or dismissed the suggestion.
    public var resolvedBy: Int?
    /// The time the suggestion was created.
    public var createdAt: Date
    /// The time the suggestion was last updated.
    public var updatedAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case issueId = "issue_id"
        case action
        case state
        case targetId = "target_id"
        case targetValue = "target_value"
        case rationale
        case confidence
        case actorId = "actor_id"
        case issueEventId = "issue_event_id"
        case resolvedBy = "resolved_by"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension IssueSuggestion {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.sdkDecodeRequired(.id)
        issueId = try container.sdkDecodeRequired(.issueId)
        action = try container.sdkDecodeRequired(.action)
        state = try container.sdkDecodeRequired(.state)
        targetId = try container.sdkDecodeIfPresent(.targetId)
        targetValue = try container.sdkDecodeIfPresent(.targetValue)
        rationale = try container.sdkDecodeIfPresent(.rationale)
        confidence = try container.sdkDecodeIfPresent(.confidence)
        actorId = try container.sdkDecodeIfPresent(.actorId)
        issueEventId = try container.sdkDecodeIfPresent(.issueEventId)
        resolvedBy = try container.sdkDecodeIfPresent(.resolvedBy)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        updatedAt = try container.sdkDecodeRequired(.updatedAt)
        try sdkValidateDateTime("created_at", sdkWireString(createdAt))
        try sdkValidateDateTime("updated_at", sdkWireString(updatedAt))
    }
}

public extension IssueSuggestion {
    init(
        id: Int,
        issueId: Int,
        action: IssueSuggestionAction,
        state: IssueSuggestionState,
        targetId: Int?,
        targetValue: IssueSuggestionTargetValue?,
        rationale: String?,
        confidence: IssueSuggestionConfidence?,
        actorId: Int?,
        issueEventId: Int?,
        resolvedBy: Int?,
        createdAt: Date,
        updatedAt: Date
    ) throws {
        (self.id, self.issueId) = (id, issueId)
        (self.action, self.state) = (action, state)
        (self.targetId, self.targetValue) = (targetId, targetValue)
        (self.rationale, self.confidence) = (rationale, confidence)
        (self.actorId, self.issueEventId) = (actorId, issueEventId)
        (self.resolvedBy, self.createdAt) = (resolvedBy, createdAt)
        self.updatedAt = updatedAt
        try sdkValidateDateTime("created_at", sdkWireString(self.createdAt))
        try sdkValidateDateTime("updated_at", sdkWireString(self.updatedAt))
    }
}

public enum IssueSuggestionTargetValue {
    case stringValue(String)
    case doubleValue(Double)
    case boolValue(Bool)
    case stringList([String])
}

extension IssueSuggestionTargetValue: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for IssueSuggestionTargetValue"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        if let value = try? container.decode(Double.self) {
            return .doubleValue(value)
        }
        if let value = try? container.decode(Bool.self) {
            return .boolValue(value)
        }
        if let value = try? container.decode([String].self) {
            return .stringList(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .doubleValue(value): try container.encode(value); return true
        case let .boolValue(value): try container.encode(value); return true
        case let .stringList(value): try container.encode(value); return true
        }
    }
}

/// Issue Type Added Issue Event
public struct IssueTypeAddedIssueEvent: Codable {
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Required `string` value serialized in the `url` wire field.
    public var url: String
    /// A GitHub user.
    public var actor: SimpleUser
    /// Required `string` value serialized in the `event` wire field.
    public var event: String
    /// Required `string` value serialized in the `commit_id` wire field.
    public var commitId: String?
    /// Required `string` value serialized in the `commit_url` wire field.
    public var commitUrl: String?
    /// Required `string` value serialized in the `created_at` wire field.
    public var createdAt: String
    /// GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user
    /// accounts and granted access to specific repositories. They come with granular permissions and built-in
    /// webhooks. GitHub apps are first class actors within GitHub.
    public var performedViaGithubApp: NullableIntegration?
    /// The type of issue.
    public var issueType: IssueTypeWebhook?
    /// The intent behind an agent's action on an issue, including the rationale and confidence. Present (and `null`
    /// when the event carried no agent intent) on supported event types while the issue suggestions feature is
    /// enabled for the repository; the property is omitted entirely when the feature is disabled or the event type
    /// does not support intent.
    public var intent: NullableIssueEventIntent?

    enum CodingKeys: String, CodingKey {
        case id
        case nodeId = "node_id"
        case url
        case actor
        case event
        case commitId = "commit_id"
        case commitUrl = "commit_url"
        case createdAt = "created_at"
        case performedViaGithubApp = "performed_via_github_app"
        case issueType = "issue_type"
        case intent
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension IssueTypeAddedIssueEvent {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.sdkDecodeRequired(.id)
        nodeId = try container.sdkDecodeRequired(.nodeId)
        url = try container.sdkDecodeRequired(.url)
        actor = try container.sdkDecodeRequired(.actor)
        event = try container.sdkDecodeRequired(.event)
        commitId = try container.sdkDecodeIfPresent(.commitId)
        commitUrl = try container.sdkDecodeIfPresent(.commitUrl)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        performedViaGithubApp = try container.sdkDecodeIfPresent(.performedViaGithubApp)
        issueType = try container.sdkDecodeIfPresent(.issueType)
        intent = try container.sdkDecodeIfPresent(.intent)
    }
}

public extension IssueTypeAddedIssueEvent {
    init(
        id: Int,
        nodeId: String,
        url: String,
        actor: SimpleUser,
        event: String,
        commitId: String?,
        commitUrl: String?,
        createdAt: String,
        performedViaGithubApp: NullableIntegration?,
        issueType: IssueTypeWebhook?,
        intent: NullableIssueEventIntent? = nil
    ) {
        (self.id, self.nodeId) = (id, nodeId)
        (self.url, self.actor) = (url, actor)
        (self.event, self.commitId) = (event, commitId)
        (self.commitUrl, self.createdAt) = (commitUrl, createdAt)
        (self.performedViaGithubApp, self.issueType) = (performedViaGithubApp, issueType)
        self.intent = intent
    }
}

/// Issue Type Changed Issue Event
public struct IssueTypeChangedIssueEvent: Codable {
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Required `string` value serialized in the `url` wire field.
    public var url: String
    /// A GitHub user.
    public var actor: SimpleUser
    /// Required `string` value serialized in the `event` wire field.
    public var event: String
    /// Required `string` value serialized in the `commit_id` wire field.
    public var commitId: String?
    /// Required `string` value serialized in the `commit_url` wire field.
    public var commitUrl: String?
    /// Required `string` value serialized in the `created_at` wire field.
    public var createdAt: String
    /// GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user
    /// accounts and granted access to specific repositories. They come with granular permissions and built-in
    /// webhooks. GitHub apps are first class actors within GitHub.
    public var performedViaGithubApp: NullableIntegration?
    /// The type of issue.
    public var issueType: IssueTypeWebhook?
    /// The type of issue.
    public var prevIssueType: IssueTypeWebhook?
    /// The intent behind an agent's action on an issue, including the rationale and confidence. Present (and `null`
    /// when the event carried no agent intent) on supported event types while the issue suggestions feature is
    /// enabled for the repository; the property is omitted entirely when the feature is disabled or the event type
    /// does not support intent.
    public var intent: NullableIssueEventIntent?

    enum CodingKeys: String, CodingKey {
        case id
        case nodeId = "node_id"
        case url
        case actor
        case event
        case commitId = "commit_id"
        case commitUrl = "commit_url"
        case createdAt = "created_at"
        case performedViaGithubApp = "performed_via_github_app"
        case issueType = "issue_type"
        case prevIssueType = "prev_issue_type"
        case intent
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension IssueTypeChangedIssueEvent {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.sdkDecodeRequired(.id)
        nodeId = try container.sdkDecodeRequired(.nodeId)
        url = try container.sdkDecodeRequired(.url)
        actor = try container.sdkDecodeRequired(.actor)
        event = try container.sdkDecodeRequired(.event)
        commitId = try container.sdkDecodeIfPresent(.commitId)
        commitUrl = try container.sdkDecodeIfPresent(.commitUrl)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        performedViaGithubApp = try container.sdkDecodeIfPresent(.performedViaGithubApp)
        issueType = try container.sdkDecodeIfPresent(.issueType)
        prevIssueType = try container.sdkDecodeIfPresent(.prevIssueType)
        intent = try container.sdkDecodeIfPresent(.intent)
    }
}

public extension IssueTypeChangedIssueEvent {
    init(
        id: Int,
        nodeId: String,
        url: String,
        actor: SimpleUser,
        event: String,
        commitId: String?,
        commitUrl: String?,
        createdAt: String,
        performedViaGithubApp: NullableIntegration?,
        issueType: IssueTypeWebhook?,
        prevIssueType: IssueTypeWebhook?,
        intent: NullableIssueEventIntent? = nil
    ) {
        (self.id, self.nodeId) = (id, nodeId)
        (self.url, self.actor) = (url, actor)
        (self.event, self.commitId) = (event, commitId)
        (self.commitUrl, self.createdAt) = (commitUrl, createdAt)
        (self.performedViaGithubApp, self.issueType) = (performedViaGithubApp, issueType)
        (self.prevIssueType, self.intent) = (prevIssueType, intent)
    }
}

/// Issue Type Removed Issue Event
public struct IssueTypeRemovedIssueEvent: Codable {
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Required `string` value serialized in the `url` wire field.
    public var url: String
    /// A GitHub user.
    public var actor: SimpleUser
    /// Required `string` value serialized in the `event` wire field.
    public var event: String
    /// Required `string` value serialized in the `commit_id` wire field.
    public var commitId: String?
    /// Required `string` value serialized in the `commit_url` wire field.
    public var commitUrl: String?
    /// Required `string` value serialized in the `created_at` wire field.
    public var createdAt: String
    /// GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user
    /// accounts and granted access to specific repositories. They come with granular permissions and built-in
    /// webhooks. GitHub apps are first class actors within GitHub.
    public var performedViaGithubApp: NullableIntegration?
    /// The type of issue.
    public var prevIssueType: IssueTypeWebhook?
    /// The intent behind an agent's action on an issue, including the rationale and confidence. Present (and `null`
    /// when the event carried no agent intent) on supported event types while the issue suggestions feature is
    /// enabled for the repository; the property is omitted entirely when the feature is disabled or the event type
    /// does not support intent.
    public var intent: NullableIssueEventIntent?

    enum CodingKeys: String, CodingKey {
        case id
        case nodeId = "node_id"
        case url
        case actor
        case event
        case commitId = "commit_id"
        case commitUrl = "commit_url"
        case createdAt = "created_at"
        case performedViaGithubApp = "performed_via_github_app"
        case prevIssueType = "prev_issue_type"
        case intent
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension IssueTypeRemovedIssueEvent {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.sdkDecodeRequired(.id)
        nodeId = try container.sdkDecodeRequired(.nodeId)
        url = try container.sdkDecodeRequired(.url)
        actor = try container.sdkDecodeRequired(.actor)
        event = try container.sdkDecodeRequired(.event)
        commitId = try container.sdkDecodeIfPresent(.commitId)
        commitUrl = try container.sdkDecodeIfPresent(.commitUrl)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        performedViaGithubApp = try container.sdkDecodeIfPresent(.performedViaGithubApp)
        prevIssueType = try container.sdkDecodeIfPresent(.prevIssueType)
        intent = try container.sdkDecodeIfPresent(.intent)
    }
}

public extension IssueTypeRemovedIssueEvent {
    init(
        id: Int,
        nodeId: String,
        url: String,
        actor: SimpleUser,
        event: String,
        commitId: String?,
        commitUrl: String?,
        createdAt: String,
        performedViaGithubApp: NullableIntegration?,
        prevIssueType: IssueTypeWebhook?,
        intent: NullableIssueEventIntent? = nil
    ) {
        (self.id, self.nodeId) = (id, nodeId)
        (self.url, self.actor) = (url, actor)
        (self.event, self.commitId) = (event, commitId)
        (self.commitUrl, self.createdAt) = (commitUrl, createdAt)
        (self.performedViaGithubApp, self.prevIssueType) = (performedViaGithubApp, prevIssueType)
        self.intent = intent
    }
}

/// The type of issue.
public struct IssueTypeWebhook: Codable {
    /// The unique identifier of the issue type.
    public var id: Int
    /// The name of the issue type.
    public var name: String
    /// The color of the issue type.
    public var color: IssueTypeWebhookColor?

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case color
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension IssueTypeWebhook {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(
                field: "id",
                code: "required",
                message: "Validation failed for 'id': value is required"
            )
        }
        guard container.contains(.name) else {
            throw SdkValidationError(
                field: "name",
                code: "required",
                message: "Validation failed for 'name': value is required"
            )
        }
        id = try container.sdkDecodeRequired(.id)
        name = try container.sdkDecodeRequired(.name)
        color = try container.sdkDecodeIfPresent(.color)
    }
}

public extension IssueTypeWebhook {
    init(id: Int, name: String, color: IssueTypeWebhookColor? = nil) {
        (self.id, self.name) = (id, name)
        self.color = color
    }
}

/// The suggestion's lifecycle state.
public struct IssueSuggestionState: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let pending = IssueSuggestionState(rawValue: "pending")
    public static let applied = IssueSuggestionState(rawValue: "applied")
    public static let approved = IssueSuggestionState(rawValue: "approved")
    public static let dismissed = IssueSuggestionState(rawValue: "dismissed")
    public static let replaced = IssueSuggestionState(rawValue: "replaced")
    public static let invalidated = IssueSuggestionState(rawValue: "invalidated")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// The color of the issue type.
public struct IssueTypeWebhookColor: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let gray = IssueTypeWebhookColor(rawValue: "gray")
    public static let blue = IssueTypeWebhookColor(rawValue: "blue")
    public static let green = IssueTypeWebhookColor(rawValue: "green")
    public static let yellow = IssueTypeWebhookColor(rawValue: "yellow")
    public static let orange = IssueTypeWebhookColor(rawValue: "orange")
    public static let red = IssueTypeWebhookColor(rawValue: "red")
    public static let pink = IssueTypeWebhookColor(rawValue: "pink")
    public static let purple = IssueTypeWebhookColor(rawValue: "purple")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// The actor's confidence level in the suggestion.
public struct IssueSuggestionConfidence: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let low = IssueSuggestionConfidence(rawValue: "LOW")
    public static let medium = IssueSuggestionConfidence(rawValue: "MEDIUM")
    public static let high = IssueSuggestionConfidence(rawValue: "HIGH")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// The kind of change proposed.
public struct IssueSuggestionAction: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let setType = IssueSuggestionAction(rawValue: "set_type")
    public static let addLabel = IssueSuggestionAction(rawValue: "add_label")
    public static let addField = IssueSuggestionAction(rawValue: "add_field")
    public static let addAssignee = IssueSuggestionAction(rawValue: "add_assignee")
    public static let closeIssue = IssueSuggestionAction(rawValue: "close_issue")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
