// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

// Issues domain models
public extension LabeledIssueEvent {
    public init(id: Int, nodeId: String, url: String, actor: SimpleUser, event: String, commitId: String?, commitUrl: String?, createdAt: String, performedViaGithubApp: NullableIntegration?, label: LabeledIssueEventLabel, intent: NullableIssueEventIntent? = nil) {
        (self.id, self.nodeId) = (id, nodeId)
        (self.url, self.actor) = (url, actor)
        (self.event, self.commitId) = (event, commitId)
        (self.commitUrl, self.createdAt) = (commitUrl, createdAt)
        (self.performedViaGithubApp, self.label) = (performedViaGithubApp, label)
        self.intent = intent
    }
}

/// Required object value serialized in the `label` wire field.
public struct LabeledIssueEventLabel: Codable {
    /// Required `string` value serialized in the `name` wire field.
    public var name: String
    /// Required `string` value serialized in the `color` wire field.
    public var color: String

    enum CodingKeys: String, CodingKey {
        case name
        case color
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension LabeledIssueEventLabel {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.name) else {
            throw SdkValidationError(field: "name", code: "required", message: "Validation failed for 'name': value is required")
        }
        guard container.contains(.color) else {
            throw SdkValidationError(field: "color", code: "required", message: "Validation failed for 'color': value is required")
        }
        self.name = try container.sdkDecodeRequired(.name)
        self.color = try container.sdkDecodeRequired(.color)
    }
}

public extension LabeledIssueEventLabel {
    public init(name: String, color: String) {
        (self.name, self.color) = (name, color)
    }
}

/// Locked Issue Event
public struct LockedIssueEvent: Codable {
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Required `string` value serialized in the `url` wire field.
    public var url: String
    /// A GitHub user.
    public var actor: SimpleUser
    /// Required `string` value serialized in the `event` wire field.
    public var event: String
    /// Required `string` value serialized in the `commit_id` wire field.
    public var commitId: String?
    /// Required `string` value serialized in the `commit_url` wire field.
    public var commitUrl: String?
    /// Required `string` value serialized in the `created_at` wire field.
    public var createdAt: String
    /// GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user
    /// accounts and granted access to specific repositories. They come with granular permissions and built-in
    /// webhooks. GitHub apps are first class actors within GitHub.
    public var performedViaGithubApp: NullableIntegration?
    /// Required `string` value serialized in the `lock_reason` wire field.
    /// - Example: "\"off-topic\""
    public var lockReason: String?

    enum CodingKeys: String, CodingKey {
        case id
        case nodeId = "node_id"
        case url
        case actor
        case event
        case commitId = "commit_id"
        case commitUrl = "commit_url"
        case createdAt = "created_at"
        case performedViaGithubApp = "performed_via_github_app"
        case lockReason = "lock_reason"
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension LockedIssueEvent {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.sdkDecodeRequired(.id)
        self.nodeId = try container.sdkDecodeRequired(.nodeId)
        self.url = try container.sdkDecodeRequired(.url)
        self.actor = try container.sdkDecodeRequired(.actor)
        self.event = try container.sdkDecodeRequired(.event)
        self.commitId = try container.sdkDecodeIfPresent(.commitId)
        self.commitUrl = try container.sdkDecodeIfPresent(.commitUrl)
        self.createdAt = try container.sdkDecodeRequired(.createdAt)
        self.performedViaGithubApp = try container.sdkDecodeIfPresent(.performedViaGithubApp)
        self.lockReason = try container.sdkDecodeIfPresent(.lockReason)
    }
}

public extension LockedIssueEvent {
    public init(id: Int, nodeId: String, url: String, actor: SimpleUser, event: String, commitId: String?, commitUrl: String?, createdAt: String, performedViaGithubApp: NullableIntegration?, lockReason: String?) {
        (self.id, self.nodeId) = (id, nodeId)
        (self.url, self.actor) = (url, actor)
        (self.event, self.commitId) = (event, commitId)
        (self.commitUrl, self.createdAt) = (commitUrl, createdAt)
        (self.performedViaGithubApp, self.lockReason) = (performedViaGithubApp, lockReason)
    }
}

/// A collection of related issues and pull requests.
public struct Milestone: Codable {
    /// Required `uri`-formatted value serialized in the `url` wire field.
    /// - Example: "https://api.github.com/repos/octocat/Hello-World/milestones/1"
    public var url: String
    /// Required `uri`-formatted value serialized in the `html_url` wire field.
    /// - Example: "https://github.com/octocat/Hello-World/milestones/v1.0"
    public var htmlUrl: String
    /// Required `uri`-formatted value serialized in the `labels_url` wire field.
    /// - Example: "https://api.github.com/repos/octocat/Hello-World/milestones/1/labels"
    public var labelsUrl: String
    /// Required `integer` value serialized in the `id` wire field.
    /// - Example: 1002604
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    /// - Example: "MDk6TWlsZXN0b25lMTAwMjYwNA=="
    public var nodeId: String
    /// The number of the milestone.
    /// - Example: 42
    public var number: Int
    /// The state of the milestone.
    /// - Example: "open"
    public var state: MilestoneState
    /// The title of the milestone.
    /// - Example: "v1.0"
    public var title: String
    /// Required `string` value serialized in the `description` wire field.
    /// - Example: "Tracking milestone for version 1.0"
    public var description: String?
    /// A GitHub user.
    public var creator: NullableSimpleUser?
    /// Required `integer` value serialized in the `open_issues` wire field.
    /// - Example: 4
    public var openIssues: Int
    /// Required `integer` value serialized in the `closed_issues` wire field.
    /// - Example: 8
    public var closedIssues: Int
    /// Required `date-time`-formatted value serialized in the `created_at` wire field.
    /// - Example: "2011-04-10T20:09:31Z"
    public var createdAt: Date
    /// Required `date-time`-formatted value serialized in the `updated_at` wire field.
    /// - Example: "2014-03-03T18:58:10Z"
    public var updatedAt: Date
    /// Required `date-time`-formatted value serialized in the `closed_at` wire field.
    /// - Example: "2013-02-12T13:22:01Z"
    public var closedAt: Date?
    /// Required `date-time`-formatted value serialized in the `due_on` wire field.
    /// - Example: "2012-10-09T23:39:01Z"
    public var dueOn: Date?

    enum CodingKeys: String, CodingKey {
        case url
        case htmlUrl = "html_url"
        case labelsUrl = "labels_url"
        case id
        case nodeId = "node_id"
        case number
        case state
        case title
        case description
        case creator
        case openIssues = "open_issues"
        case closedIssues = "closed_issues"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case closedAt = "closed_at"
        case dueOn = "due_on"
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension Milestone {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.url = try container.sdkDecodeRequired(.url)
        self.htmlUrl = try container.sdkDecodeRequired(.htmlUrl)
        self.labelsUrl = try container.sdkDecodeRequired(.labelsUrl)
        self.id = try container.sdkDecodeRequired(.id)
        self.nodeId = try container.sdkDecodeRequired(.nodeId)
        self.number = try container.sdkDecodeRequired(.number)
        self.state = try container.sdkDecodeRequired(.state)
        self.title = try container.sdkDecodeRequired(.title)
        self.description = try container.sdkDecodeIfPresent(.description)
        self.creator = try container.sdkDecodeIfPresent(.creator)
        self.openIssues = try container.sdkDecodeRequired(.openIssues)
        self.closedIssues = try container.sdkDecodeRequired(.closedIssues)
        self.createdAt = try container.sdkDecodeRequired(.createdAt)
        self.updatedAt = try container.sdkDecodeRequired(.updatedAt)
        self.closedAt = try container.sdkDecodeIfPresent(.closedAt)
        self.dueOn = try container.sdkDecodeIfPresent(.dueOn)
        try sdkValidateConstraints()
    }
}

public extension Milestone {
    public init(url: String, htmlUrl: String, labelsUrl: String, id: Int, nodeId: String, number: Int, state: MilestoneState, title: String, description: String?, creator: NullableSimpleUser?, openIssues: Int, closedIssues: Int, createdAt: Date, updatedAt: Date, closedAt: Date?, dueOn: Date?) throws {
        (self.url, self.htmlUrl) = (url, htmlUrl)
        (self.labelsUrl, self.id) = (labelsUrl, id)
        (self.nodeId, self.number) = (nodeId, number)
        (self.state, self.title) = (state, title)
        (self.description, self.creator) = (description, creator)
        (self.openIssues, self.closedIssues) = (openIssues, closedIssues)
        (self.createdAt, self.updatedAt) = (createdAt, updatedAt)
        (self.closedAt, self.dueOn) = (closedAt, dueOn)
        try sdkValidateConstraints()
    }
}

extension Milestone {
    func sdkValidateConstraints() throws {
            try sdkValidateUri("url", self.url)
            try sdkValidateUri("html_url", self.htmlUrl)
            try sdkValidateUri("labels_url", self.labelsUrl)
            try sdkValidateDateTime("created_at", sdkWireString(self.createdAt))
            try sdkValidateDateTime("updated_at", sdkWireString(self.updatedAt))
        if let value = self.closedAt {
            try sdkValidateDateTime("closed_at", sdkWireString(value))
        }
        if let value = self.dueOn {
            try sdkValidateDateTime("due_on", sdkWireString(value))
        }
    }
}

/// Milestoned Issue Event
public struct MilestonedIssueEvent: Codable {
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Required `string` value serialized in the `url` wire field.
    public var url: String
    /// A GitHub user.
    public var actor: SimpleUser
    /// Required `string` value serialized in the `event` wire field.
    public var event: String
    /// Required `string` value serialized in the `commit_id` wire field.
    public var commitId: String?
    /// Required `string` value serialized in the `commit_url` wire field.
    public var commitUrl: String?
    /// Required `string` value serialized in the `created_at` wire field.
    public var createdAt: String
    /// GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user
    /// accounts and granted access to specific repositories. They come with granular permissions and built-in
    /// webhooks. GitHub apps are first class actors within GitHub.
    public var performedViaGithubApp: NullableIntegration?
    /// Required object value serialized in the `milestone` wire field.
    public var milestone: MilestonedIssueEventMilestone

    enum CodingKeys: String, CodingKey {
        case id
        case nodeId = "node_id"
        case url
        case actor
        case event
        case commitId = "commit_id"
        case commitUrl = "commit_url"
        case createdAt = "created_at"
        case performedViaGithubApp = "performed_via_github_app"
        case milestone
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension MilestonedIssueEvent {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.sdkDecodeRequired(.id)
        self.nodeId = try container.sdkDecodeRequired(.nodeId)
        self.url = try container.sdkDecodeRequired(.url)
        self.actor = try container.sdkDecodeRequired(.actor)
        self.event = try container.sdkDecodeRequired(.event)
        self.commitId = try container.sdkDecodeIfPresent(.commitId)
        self.commitUrl = try container.sdkDecodeIfPresent(.commitUrl)
        self.createdAt = try container.sdkDecodeRequired(.createdAt)
        self.performedViaGithubApp = try container.sdkDecodeIfPresent(.performedViaGithubApp)
        self.milestone = try container.sdkDecodeRequired(.milestone)
    }
}

public extension MilestonedIssueEvent {
    public init(id: Int, nodeId: String, url: String, actor: SimpleUser, event: String, commitId: String?, commitUrl: String?, createdAt: String, performedViaGithubApp: NullableIntegration?, milestone: MilestonedIssueEventMilestone) {
        (self.id, self.nodeId) = (id, nodeId)
        (self.url, self.actor) = (url, actor)
        (self.event, self.commitId) = (event, commitId)
        (self.commitUrl, self.createdAt) = (commitUrl, createdAt)
        (self.performedViaGithubApp, self.milestone) = (performedViaGithubApp, milestone)
    }
}

/// Required object value serialized in the `milestone` wire field.
public struct MilestonedIssueEventMilestone: Codable {
    /// Required `string` value serialized in the `title` wire field.
    public var title: String

    enum CodingKeys: String, CodingKey {
        case title
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension MilestonedIssueEventMilestone {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.title) else {
            throw SdkValidationError(field: "title", code: "required", message: "Validation failed for 'title': value is required")
        }
        self.title = try container.sdkDecodeRequired(.title)
    }
}

public extension MilestonedIssueEventMilestone {
    public init(title: String) {
        self.title = title
    }
}

/// Moved Column in Project Issue Event
public struct MovedColumnInProjectIssueEvent: Codable {
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Required `string` value serialized in the `url` wire field.
    public var url: String
    /// A GitHub user.
    public var actor: SimpleUser
    /// Required `string` value serialized in the `event` wire field.
    public var event: String
    /// Required `string` value serialized in the `commit_id` wire field.
    public var commitId: String?
    /// Required `string` value serialized in the `commit_url` wire field.
    public var commitUrl: String?
    /// Required `string` value serialized in the `created_at` wire field.
    public var createdAt: String
    /// GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user
    /// accounts and granted access to specific repositories. They come with granular permissions and built-in
    /// webhooks. GitHub apps are first class actors within GitHub.
    public var performedViaGithubApp: NullableIntegration?
    /// Optional object value serialized in the `project_card` wire field.
    public var projectCard: MovedColumnInProjectIssueEventProjectCard?

    enum CodingKeys: String, CodingKey {
        case id
        case nodeId = "node_id"
        case url
        case actor
        case event
        case commitId = "commit_id"
        case commitUrl = "commit_url"
        case createdAt = "created_at"
        case performedViaGithubApp = "performed_via_github_app"
        case projectCard = "project_card"
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension MovedColumnInProjectIssueEvent {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.sdkDecodeRequired(.id)
        self.nodeId = try container.sdkDecodeRequired(.nodeId)
        self.url = try container.sdkDecodeRequired(.url)
        self.actor = try container.sdkDecodeRequired(.actor)
        self.event = try container.sdkDecodeRequired(.event)
        self.commitId = try container.sdkDecodeIfPresent(.commitId)
        self.commitUrl = try container.sdkDecodeIfPresent(.commitUrl)
        self.createdAt = try container.sdkDecodeRequired(.createdAt)
        self.performedViaGithubApp = try container.sdkDecodeIfPresent(.performedViaGithubApp)
        self.projectCard = try container.sdkDecodeIfPresent(.projectCard)
    }
}

public extension MovedColumnInProjectIssueEvent {
    public init(id: Int, nodeId: String, url: String, actor: SimpleUser, event: String, commitId: String?, commitUrl: String?, createdAt: String, performedViaGithubApp: NullableIntegration?, projectCard: MovedColumnInProjectIssueEventProjectCard? = nil) {
        (self.id, self.nodeId) = (id, nodeId)
        (self.url, self.actor) = (url, actor)
        (self.event, self.commitId) = (event, commitId)
        (self.commitUrl, self.createdAt) = (commitUrl, createdAt)
        (self.performedViaGithubApp, self.projectCard) = (performedViaGithubApp, projectCard)
    }
}

/// Optional object value serialized in the `project_card` wire field.
public struct MovedColumnInProjectIssueEventProjectCard: Codable {
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `uri`-formatted value serialized in the `url` wire field.
    public var url: String
    /// Required `integer` value serialized in the `project_id` wire field.
    public var projectId: Int
    /// Required `uri`-formatted value serialized in the `project_url` wire field.
    public var projectUrl: String
    /// Required `string` value serialized in the `column_name` wire field.
    public var columnName: String
    /// Optional `string` value serialized in the `previous_column_name` wire field.
    public var previousColumnName: String?

    enum CodingKeys: String, CodingKey {
        case id
        case url
        case projectId = "project_id"
        case projectUrl = "project_url"
        case columnName = "column_name"
        case previousColumnName = "previous_column_name"
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension MovedColumnInProjectIssueEventProjectCard {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(field: "id", code: "required", message: "Validation failed for 'id': value is required")
        }
        guard container.contains(.url) else {
            throw SdkValidationError(field: "url", code: "required", message: "Validation failed for 'url': value is required")
        }
        guard container.contains(.projectId) else {
            throw SdkValidationError(field: "project_id", code: "required", message: "Validation failed for 'project_id': value is required")
        }
        guard container.contains(.projectUrl) else {
            throw SdkValidationError(field: "project_url", code: "required", message: "Validation failed for 'project_url': value is required")
        }
        guard container.contains(.columnName) else {
            throw SdkValidationError(field: "column_name", code: "required", message: "Validation failed for 'column_name': value is required")
        }
        self.id = try container.sdkDecodeRequired(.id)
        self.url = try container.sdkDecodeRequired(.url)
        self.projectId = try container.sdkDecodeRequired(.projectId)
        self.projectUrl = try container.sdkDecodeRequired(.projectUrl)
        self.columnName = try container.sdkDecodeRequired(.columnName)
        self.previousColumnName = try container.sdkDecodeIfPresent(.previousColumnName)
            try sdkValidateUri("url", self.url)
            try sdkValidateUri("project_url", self.projectUrl)
    }
}

public extension MovedColumnInProjectIssueEventProjectCard {
    public init(id: Int, url: String, projectId: Int, projectUrl: String, columnName: String, previousColumnName: String? = nil) throws {
        (self.id, self.url) = (id, url)
        (self.projectId, self.projectUrl) = (projectId, projectUrl)
        (self.columnName, self.previousColumnName) = (columnName, previousColumnName)
            try sdkValidateUri("url", self.url)
            try sdkValidateUri("project_url", self.projectUrl)
    }
}

/// Removed from Project Issue Event
public struct RemovedFromProjectIssueEvent: Codable {
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Required `string` value serialized in the `url` wire field.
    public var url: String
    /// A GitHub user.
    public var actor: SimpleUser
    /// Required `string` value serialized in the `event` wire field.
    public var event: String
    /// Required `string` value serialized in the `commit_id` wire field.
    public var commitId: String?
    /// Required `string` value serialized in the `commit_url` wire field.
    public var commitUrl: String?
    /// Required `string` value serialized in the `created_at` wire field.
    public var createdAt: String
    /// GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user
    /// accounts and granted access to specific repositories. They come with granular permissions and built-in
    /// webhooks. GitHub apps are first class actors within GitHub.
    public var performedViaGithubApp: NullableIntegration?
    /// Optional object value serialized in the `project_card` wire field.
    public var projectCard: RemovedFromProjectIssueEventProjectCard?

    enum CodingKeys: String, CodingKey {
        case id
        case nodeId = "node_id"
        case url
        case actor
        case event
        case commitId = "commit_id"
        case commitUrl = "commit_url"
        case createdAt = "created_at"
        case performedViaGithubApp = "performed_via_github_app"
        case projectCard = "project_card"
    }

    private init(sdkCopy value: Self) { self = value }
}
