// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// IssuesTimeline domain models
/// Timeline Reviewed Event
public struct TimelineReviewedEvent: Codable {
    /// Required `string` value serialized in the `event` wire field.
    public var event: String
    /// Unique identifier of the review
    /// - Example: 42
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    /// - Example: "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3ODA="
    public var nodeId: String
    /// A GitHub user.
    public var user: SimpleUser
    /// The text of the review.
    /// - Example: "This looks great."
    public var body: String?
    /// Required `string` value serialized in the `state` wire field.
    /// - Example: "CHANGES_REQUESTED"
    public var state: String
    /// Required `uri`-formatted value serialized in the `html_url` wire field.
    /// - Example: "https://github.com/octocat/Hello-World/pull/12#pullrequestreview-80"
    public var htmlUrl: String
    /// Required `uri`-formatted value serialized in the `pull_request_url` wire field.
    /// - Example: "https://api.github.com/repos/octocat/Hello-World/pulls/12"
    public var pullRequestUrl: String
    /// Required object value serialized in the `_links` wire field.
    public var links: TimelineReviewedEventLinks
    /// A commit SHA for the review.
    /// - Example: "54bb654c9e6025347f57900a4a5c2313a96b8035"
    public var commitId: String
    /// How the author is associated with the repository.
    /// - Example: "OWNER"
    public var authorAssociation: AuthorAssociation
    /// Optional `date-time`-formatted value serialized in the `submitted_at` wire field.
    public var submittedAt: Date?
    /// Optional `date-time`-formatted value serialized in the `updated_at` wire field.
    public var updatedAt: Date?
    /// Optional `string` value serialized in the `body_html` wire field.
    public var bodyHtml: String?
    /// Optional `string` value serialized in the `body_text` wire field.
    public var bodyText: String?

    enum CodingKeys: String, CodingKey {
        case event
        case id
        case nodeId = "node_id"
        case user
        case body
        case state
        case htmlUrl = "html_url"
        case pullRequestUrl = "pull_request_url"
        case links = "_links"
        case commitId = "commit_id"
        case authorAssociation = "author_association"
        case submittedAt = "submitted_at"
        case updatedAt = "updated_at"
        case bodyHtml = "body_html"
        case bodyText = "body_text"
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension TimelineReviewedEvent {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        event = try container.sdkDecodeRequired(.event)
        id = try container.sdkDecodeRequired(.id)
        nodeId = try container.sdkDecodeRequired(.nodeId)
        user = try container.sdkDecodeRequired(.user)
        body = try container.sdkDecodeIfPresent(.body)
        state = try container.sdkDecodeRequired(.state)
        htmlUrl = try container.sdkDecodeRequired(.htmlUrl)
        pullRequestUrl = try container.sdkDecodeRequired(.pullRequestUrl)
        links = try container.sdkDecodeRequired(.links)
        commitId = try container.sdkDecodeRequired(.commitId)
        authorAssociation = try container.sdkDecodeRequired(.authorAssociation)
        submittedAt = try container.sdkDecodeIfPresent(.submittedAt)
        updatedAt = try container.sdkDecodeIfPresent(.updatedAt)
        bodyHtml = try container.sdkDecodeIfPresent(.bodyHtml)
        bodyText = try container.sdkDecodeIfPresent(.bodyText)
        try sdkValidateUri("html_url", htmlUrl)
        try sdkValidateUri("pull_request_url", pullRequestUrl)
        if let value = submittedAt {
            try sdkValidateDateTime("submitted_at", sdkWireString(value))
        }
        if let value = updatedAt {
            try sdkValidateDateTime("updated_at", sdkWireString(value))
        }
    }
}

public extension TimelineReviewedEvent {
    init(
        event: String,
        id: Int,
        nodeId: String,
        user: SimpleUser,
        body: String?,
        state: String,
        htmlUrl: String,
        pullRequestUrl: String,
        links: TimelineReviewedEventLinks,
        commitId: String,
        authorAssociation: AuthorAssociation,
        submittedAt: Date? = nil,
        updatedAt: Date? = nil,
        bodyHtml: String? = nil,
        bodyText: String? = nil
    ) throws {
        (self.event, self.id) = (event, id)
        (self.nodeId, self.user) = (nodeId, user)
        (self.body, self.state) = (body, state)
        (self.htmlUrl, self.pullRequestUrl) = (htmlUrl, pullRequestUrl)
        (self.links, self.commitId) = (links, commitId)
        (self.authorAssociation, self.submittedAt) = (authorAssociation, submittedAt)
        (self.updatedAt, self.bodyHtml) = (updatedAt, bodyHtml)
        self.bodyText = bodyText
        try sdkValidateUri("html_url", self.htmlUrl)
        try sdkValidateUri("pull_request_url", self.pullRequestUrl)
        if let value = self.submittedAt {
            try sdkValidateDateTime("submitted_at", sdkWireString(value))
        }
        if let value = self.updatedAt {
            try sdkValidateDateTime("updated_at", sdkWireString(value))
        }
    }
}

/// Required object value serialized in the `_links` wire field.
public struct TimelineReviewedEventLinks: Codable {
    /// Required object value serialized in the `html` wire field.
    public var html: TimelineReviewedEventLinksHtml
    /// Required object value serialized in the `pull_request` wire field.
    public var pullRequest: TimelineReviewedEventLinksPullRequest

    enum CodingKeys: String, CodingKey {
        case html
        case pullRequest = "pull_request"
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension TimelineReviewedEventLinks {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.html) else {
            throw SdkValidationError(
                field: "html",
                code: "required",
                message: "Validation failed for 'html': value is required"
            )
        }
        guard container.contains(.pullRequest) else {
            throw SdkValidationError(
                field: "pull_request",
                code: "required",
                message: "Validation failed for 'pull_request': value is required"
            )
        }
        html = try container.sdkDecodeRequired(.html)
        pullRequest = try container.sdkDecodeRequired(.pullRequest)
    }
}

public extension TimelineReviewedEventLinks {
    init(html: TimelineReviewedEventLinksHtml, pullRequest: TimelineReviewedEventLinksPullRequest) {
        (self.html, self.pullRequest) = (html, pullRequest)
    }
}

/// Required object value serialized in the `html` wire field.
public struct TimelineReviewedEventLinksHtml: Codable {
    /// Required `string` value serialized in the `href` wire field.
    public var href: String

    enum CodingKeys: String, CodingKey {
        case href
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension TimelineReviewedEventLinksHtml {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.href) else {
            throw SdkValidationError(
                field: "href",
                code: "required",
                message: "Validation failed for 'href': value is required"
            )
        }
        href = try container.sdkDecodeRequired(.href)
    }
}

public extension TimelineReviewedEventLinksHtml {
    init(href: String) {
        self.href = href
    }
}

/// Required object value serialized in the `pull_request` wire field.
public struct TimelineReviewedEventLinksPullRequest: Codable {
    /// Required `string` value serialized in the `href` wire field.
    public var href: String

    enum CodingKeys: String, CodingKey {
        case href
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension TimelineReviewedEventLinksPullRequest {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.href) else {
            throw SdkValidationError(
                field: "href",
                code: "required",
                message: "Validation failed for 'href': value is required"
            )
        }
        href = try container.sdkDecodeRequired(.href)
    }
}

public extension TimelineReviewedEventLinksPullRequest {
    init(href: String) {
        self.href = href
    }
}

/// Timeline Unassigned Issue Event
public struct TimelineUnassignedIssueEvent: Codable {
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Required `string` value serialized in the `url` wire field.
    public var url: String
    /// A GitHub user.
    public var actor: SimpleUser
    /// Required `string` value serialized in the `event` wire field.
    public var event: String
    /// Required `string` value serialized in the `commit_id` wire field.
    public var commitId: String?
    /// Required `string` value serialized in the `commit_url` wire field.
    public var commitUrl: String?
    /// Required `string` value serialized in the `created_at` wire field.
    public var createdAt: String
    /// GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user
    /// accounts and granted access to specific repositories. They come with granular permissions and built-in
    /// webhooks. GitHub apps are first class actors within GitHub.
    public var performedViaGithubApp: NullableIntegration?
    /// A GitHub user.
    public var assignee: SimpleUser

    enum CodingKeys: String, CodingKey {
        case id
        case nodeId = "node_id"
        case url
        case actor
        case event
        case commitId = "commit_id"
        case commitUrl = "commit_url"
        case createdAt = "created_at"
        case performedViaGithubApp = "performed_via_github_app"
        case assignee
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension TimelineUnassignedIssueEvent {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.sdkDecodeRequired(.id)
        nodeId = try container.sdkDecodeRequired(.nodeId)
        url = try container.sdkDecodeRequired(.url)
        actor = try container.sdkDecodeRequired(.actor)
        event = try container.sdkDecodeRequired(.event)
        commitId = try container.sdkDecodeIfPresent(.commitId)
        commitUrl = try container.sdkDecodeIfPresent(.commitUrl)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        performedViaGithubApp = try container.sdkDecodeIfPresent(.performedViaGithubApp)
        assignee = try container.sdkDecodeRequired(.assignee)
    }
}

public extension TimelineUnassignedIssueEvent {
    init(
        id: Int,
        nodeId: String,
        url: String,
        actor: SimpleUser,
        event: String,
        commitId: String?,
        commitUrl: String?,
        createdAt: String,
        performedViaGithubApp: NullableIntegration?,
        assignee: SimpleUser
    ) {
        (self.id, self.nodeId) = (id, nodeId)
        (self.url, self.actor) = (url, actor)
        (self.event, self.commitId) = (event, commitId)
        (self.commitUrl, self.createdAt) = (commitUrl, createdAt)
        (self.performedViaGithubApp, self.assignee) = (performedViaGithubApp, assignee)
    }
}
