// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// Pulls domain models
/// Pull requests let you tell others about changes you've pushed to a repository on GitHub. Once a pull request is
/// sent, interested parties can review the set of changes, discuss potential modifications, and even push follow-up
/// commits if necessary.
public struct PullRequest: Codable {
    /// Required `uri`-formatted value serialized in the `url` wire field.
    /// - Example: "https://api.github.com/repos/octocat/Hello-World/pulls/1347"
    public var url: String
    /// Required `int64`-formatted value serialized in the `id` wire field.
    /// - Example: 1
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    /// - Example: "MDExOlB1bGxSZXF1ZXN0MQ=="
    public var nodeId: String
    /// Required `uri`-formatted value serialized in the `html_url` wire field.
    /// - Example: "https://github.com/octocat/Hello-World/pull/1347"
    public var htmlUrl: String
    /// Required `uri`-formatted value serialized in the `diff_url` wire field.
    /// - Example: "https://github.com/octocat/Hello-World/pull/1347.diff"
    public var diffUrl: String
    /// Required `uri`-formatted value serialized in the `patch_url` wire field.
    /// - Example: "https://github.com/octocat/Hello-World/pull/1347.patch"
    public var patchUrl: String
    /// Required `uri`-formatted value serialized in the `issue_url` wire field.
    /// - Example: "https://api.github.com/repos/octocat/Hello-World/issues/1347"
    public var issueUrl: String
    /// Required `uri`-formatted value serialized in the `commits_url` wire field.
    /// - Example: "https://api.github.com/repos/octocat/Hello-World/pulls/1347/commits"
    public var commitsUrl: String
    /// Required `uri`-formatted value serialized in the `review_comments_url` wire field.
    /// - Example: "https://api.github.com/repos/octocat/Hello-World/pulls/1347/comments"
    public var reviewCommentsUrl: String
    /// Required `string` value serialized in the `review_comment_url` wire field.
    /// - Example: "https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}"
    public var reviewCommentUrl: String
    /// Required `uri`-formatted value serialized in the `comments_url` wire field.
    /// - Example: "https://api.github.com/repos/octocat/Hello-World/issues/1347/comments"
    public var commentsUrl: String
    /// Required `uri`-formatted value serialized in the `statuses_url` wire field.
    /// - Example:
    /// "https://api.github.com/repos/octocat/Hello-World/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e"
    public var statusesUrl: String
    /// Number uniquely identifying the pull request within its repository.
    /// - Example: 42
    public var number: Int
    /// State of this Pull Request. Either `open` or `closed`.
    /// - Example: "open"
    public var state: PullRequestState
    /// Required `boolean` value serialized in the `locked` wire field.
    /// - Example: true
    public var locked: Bool
    /// The title of the pull request.
    /// - Example: "Amazing new feature"
    public var title: String
    /// A GitHub user.
    public var user: SimpleUser
    /// Required `string` value serialized in the `body` wire field.
    /// - Example: "Please pull these awesome changes"
    public var body: String?
    /// Required array value serialized in the `labels` wire field.
    public var labels: [PullRequestLabelsItem]
    /// A collection of related issues and pull requests.
    public var milestone: NullableMilestone?
    /// Required `date-time`-formatted value serialized in the `created_at` wire field.
    /// - Example: "2011-01-26T19:01:12Z"
    public var createdAt: Date
    /// Required `date-time`-formatted value serialized in the `updated_at` wire field.
    /// - Example: "2011-01-26T19:01:12Z"
    public var updatedAt: Date
    /// Required `date-time`-formatted value serialized in the `closed_at` wire field.
    /// - Example: "2011-01-26T19:01:12Z"
    public var closedAt: Date?
    /// Required `date-time`-formatted value serialized in the `merged_at` wire field.
    /// - Example: "2011-01-26T19:01:12Z"
    public var mergedAt: Date?
    /// Required `string` value serialized in the `merge_commit_sha` wire field.
    /// - Example: "e5bd3914e2e596debea16f433f57875b5b90bcd6"
    public var mergeCommitSha: String?
    /// A GitHub user.
    public var assignee: NullableSimpleUser?
    /// Required object value serialized in the `head` wire field.
    public var head: PullRequestHead
    /// Required object value serialized in the `base` wire field.
    public var base: PullRequestBase
    /// Required object value serialized in the `_links` wire field.
    public var links: PullRequestLinks
    /// How the author is associated with the repository.
    /// - Example: "OWNER"
    public var authorAssociation: AuthorAssociation
    /// The status of auto merging a pull request.
    public var autoMerge: AutoMerge?
    /// Required `boolean` value serialized in the `merged` wire field.
    public var merged: Bool
    /// Required `boolean` value serialized in the `mergeable` wire field.
    /// - Example: true
    public var mergeable: Bool?
    /// Required `string` value serialized in the `mergeable_state` wire field.
    /// - Example: "clean"
    public var mergeableState: String
    /// A GitHub user.
    public var mergedBy: NullableSimpleUser?
    /// Required `integer` value serialized in the `comments` wire field.
    /// - Example: 10
    public var comments: Int
    /// Required `integer` value serialized in the `review_comments` wire field.
    public var reviewComments: Int
    /// Indicates whether maintainers can modify the pull request.
    /// - Example: true
    public var maintainerCanModify: Bool
    /// Required `integer` value serialized in the `commits` wire field.
    /// - Example: 3
    public var commits: Int
    /// Required `integer` value serialized in the `additions` wire field.
    /// - Example: 100
    public var additions: Int
    /// Required `integer` value serialized in the `deletions` wire field.
    /// - Example: 3
    public var deletions: Int
    /// Required `integer` value serialized in the `changed_files` wire field.
    /// - Example: 5
    public var changedFiles: Int
    /// Optional `string` value serialized in the `active_lock_reason` wire field.
    /// - Example: "too heated"
    public var activeLockReason: String?
    /// Optional array value serialized in the `assignees` wire field.
    public var assignees: [SimpleUser]?
    /// Optional array value serialized in the `requested_reviewers` wire field.
    public var requestedReviewers: [SimpleUser]?
    /// Optional array value serialized in the `requested_teams` wire field.
    public var requestedTeams: [TeamSimple]?
    /// The stack information associated with a pull request.
    public var stack: PullRequestStack?
    /// Indicates whether or not the pull request is a draft.
    public var draft: Bool?
    /// Optional `boolean` value serialized in the `rebaseable` wire field.
    /// - Example: true
    public var rebaseable: Bool?

    enum CodingKeys: String, CodingKey {
        case url
        case id
        case nodeId = "node_id"
        case htmlUrl = "html_url"
        case diffUrl = "diff_url"
        case patchUrl = "patch_url"
        case issueUrl = "issue_url"
        case commitsUrl = "commits_url"
        case reviewCommentsUrl = "review_comments_url"
        case reviewCommentUrl = "review_comment_url"
        case commentsUrl = "comments_url"
        case statusesUrl = "statuses_url"
        case number
        case state
        case locked
        case title
        case user
        case body
        case labels
        case milestone
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case closedAt = "closed_at"
        case mergedAt = "merged_at"
        case mergeCommitSha = "merge_commit_sha"
        case assignee
        case head
        case base
        case links = "_links"
        case authorAssociation = "author_association"
        case autoMerge = "auto_merge"
        case merged
        case mergeable
        case mergeableState = "mergeable_state"
        case mergedBy = "merged_by"
        case comments
        case reviewComments = "review_comments"
        case maintainerCanModify = "maintainer_can_modify"
        case commits
        case additions
        case deletions
        case changedFiles = "changed_files"
        case activeLockReason = "active_lock_reason"
        case assignees
        case requestedReviewers = "requested_reviewers"
        case requestedTeams = "requested_teams"
        case stack
        case draft
        case rebaseable
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension PullRequest {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        url = try container.sdkDecodeRequired(.url)
        id = try container.sdkDecodeRequired(.id)
        nodeId = try container.sdkDecodeRequired(.nodeId)
        htmlUrl = try container.sdkDecodeRequired(.htmlUrl)
        diffUrl = try container.sdkDecodeRequired(.diffUrl)
        patchUrl = try container.sdkDecodeRequired(.patchUrl)
        issueUrl = try container.sdkDecodeRequired(.issueUrl)
        commitsUrl = try container.sdkDecodeRequired(.commitsUrl)
        reviewCommentsUrl = try container.sdkDecodeRequired(.reviewCommentsUrl)
        reviewCommentUrl = try container.sdkDecodeRequired(.reviewCommentUrl)
        commentsUrl = try container.sdkDecodeRequired(.commentsUrl)
        statusesUrl = try container.sdkDecodeRequired(.statusesUrl)
        number = try container.sdkDecodeRequired(.number)
        state = try container.sdkDecodeRequired(.state)
        locked = try container.sdkDecodeRequired(.locked)
        title = try container.sdkDecodeRequired(.title)
        user = try container.sdkDecodeRequired(.user)
        body = try container.sdkDecodeIfPresent(.body)
        labels = try container.sdkDecodeRequired(.labels)
        milestone = try container.sdkDecodeIfPresent(.milestone)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        updatedAt = try container.sdkDecodeRequired(.updatedAt)
        closedAt = try container.sdkDecodeIfPresent(.closedAt)
        mergedAt = try container.sdkDecodeIfPresent(.mergedAt)
        mergeCommitSha = try container.sdkDecodeIfPresent(.mergeCommitSha)
        assignee = try container.sdkDecodeIfPresent(.assignee)
        head = try container.sdkDecodeRequired(.head)
        base = try container.sdkDecodeRequired(.base)
        links = try container.sdkDecodeRequired(.links)
        authorAssociation = try container.sdkDecodeRequired(.authorAssociation)
        autoMerge = try container.sdkDecodeIfPresent(.autoMerge)
        merged = try container.sdkDecodeRequired(.merged)
        mergeable = try container.sdkDecodeIfPresent(.mergeable)
        mergeableState = try container.sdkDecodeRequired(.mergeableState)
        mergedBy = try container.sdkDecodeIfPresent(.mergedBy)
        comments = try container.sdkDecodeRequired(.comments)
        reviewComments = try container.sdkDecodeRequired(.reviewComments)
        maintainerCanModify = try container.sdkDecodeRequired(.maintainerCanModify)
        commits = try container.sdkDecodeRequired(.commits)
        additions = try container.sdkDecodeRequired(.additions)
        deletions = try container.sdkDecodeRequired(.deletions)
        changedFiles = try container.sdkDecodeRequired(.changedFiles)
        activeLockReason = try container.sdkDecodeIfPresent(.activeLockReason)
        assignees = try container.sdkDecodeIfPresent(.assignees)
        requestedReviewers = try container.sdkDecodeIfPresent(.requestedReviewers)
        requestedTeams = try container.sdkDecodeIfPresent(.requestedTeams)
        stack = try container.sdkDecodeIfPresent(.stack)
        draft = try container.sdkDecodeIfPresent(.draft)
        rebaseable = try container.sdkDecodeIfPresent(.rebaseable)
        try sdkValidateConstraintsPart1()
        try sdkValidateConstraintsPart2()
    }
}

public extension PullRequest {
    init(
        url: String,
        id: Int,
        nodeId: String,
        htmlUrl: String,
        diffUrl: String,
        patchUrl: String,
        issueUrl: String,
        commitsUrl: String,
        reviewCommentsUrl: String,
        reviewCommentUrl: String,
        commentsUrl: String,
        statusesUrl: String,
        number: Int,
        state: PullRequestState,
        locked: Bool,
        title: String,
        user: SimpleUser,
        body: String?,
        labels: [PullRequestLabelsItem],
        milestone: NullableMilestone?,
        createdAt: Date,
        updatedAt: Date,
        closedAt: Date?,
        mergedAt: Date?,
        mergeCommitSha: String?,
        assignee: NullableSimpleUser?,
        head: PullRequestHead,
        base: PullRequestBase,
        links: PullRequestLinks,
        authorAssociation: AuthorAssociation,
        autoMerge: AutoMerge?,
        merged: Bool,
        mergeable: Bool?,
        mergeableState: String,
        mergedBy: NullableSimpleUser?,
        comments: Int,
        reviewComments: Int,
        maintainerCanModify: Bool,
        commits: Int,
        additions: Int,
        deletions: Int,
        changedFiles: Int,
        activeLockReason: String? = nil,
        assignees: [SimpleUser]? = nil,
        requestedReviewers: [SimpleUser]? = nil,
        requestedTeams: [TeamSimple]? = nil,
        stack: PullRequestStack? = nil,
        draft: Bool? = nil,
        rebaseable: Bool? = nil
    ) throws {
        (self.url, self.id) = (url, id)
        (self.nodeId, self.htmlUrl) = (nodeId, htmlUrl)
        (self.diffUrl, self.patchUrl) = (diffUrl, patchUrl)
        (self.issueUrl, self.commitsUrl) = (issueUrl, commitsUrl)
        (self.reviewCommentsUrl, self.reviewCommentUrl) = (reviewCommentsUrl, reviewCommentUrl)
        (self.commentsUrl, self.statusesUrl) = (commentsUrl, statusesUrl)
        (self.number, self.state) = (number, state)
        (self.locked, self.title) = (locked, title)
        (self.user, self.body) = (user, body)
        (self.labels, self.milestone) = (labels, milestone)
        (self.createdAt, self.updatedAt) = (createdAt, updatedAt)
        (self.closedAt, self.mergedAt) = (closedAt, mergedAt)
        (self.mergeCommitSha, self.assignee) = (mergeCommitSha, assignee)
        (self.head, self.base) = (head, base)
        (self.links, self.authorAssociation) = (links, authorAssociation)
        (self.autoMerge, self.merged) = (autoMerge, merged)
        (self.mergeable, self.mergeableState) = (mergeable, mergeableState)
        (self.mergedBy, self.comments) = (mergedBy, comments)
        (self.reviewComments, self.maintainerCanModify) = (reviewComments, maintainerCanModify)
        (self.commits, self.additions) = (commits, additions)
        (self.deletions, self.changedFiles) = (deletions, changedFiles)
        (self.activeLockReason, self.assignees) = (activeLockReason, assignees)
        (self.requestedReviewers, self.requestedTeams) = (requestedReviewers, requestedTeams)
        (self.stack, self.draft) = (stack, draft)
        self.rebaseable = rebaseable
        try sdkValidateConstraintsPart1()
        try sdkValidateConstraintsPart2()
    }
}

extension PullRequest {
    func sdkValidateConstraintsPart1() throws {
        try sdkValidateUri("url", url)
        try sdkValidateUri("html_url", htmlUrl)
        try sdkValidateUri("diff_url", diffUrl)
        try sdkValidateUri("patch_url", patchUrl)
        try sdkValidateUri("issue_url", issueUrl)
        try sdkValidateUri("commits_url", commitsUrl)
        try sdkValidateUri("review_comments_url", reviewCommentsUrl)
        try sdkValidateUri("comments_url", commentsUrl)
        try sdkValidateUri("statuses_url", statusesUrl)
        try sdkValidateDateTime("created_at", sdkWireString(createdAt))
        try sdkValidateDateTime("updated_at", sdkWireString(updatedAt))
        if let value = closedAt {
            try sdkValidateDateTime("closed_at", sdkWireString(value))
        }
    }
}

extension PullRequest {
    func sdkValidateConstraintsPart2() throws {
        if let value = mergedAt {
            try sdkValidateDateTime("merged_at", sdkWireString(value))
        }
    }
}

/// Required object value serialized in the `_links` wire field.
public struct PullRequestLinks: Codable {
    /// Hypermedia Link
    public var comments: Link
    /// Hypermedia Link
    public var commits: Link
    /// Hypermedia Link
    public var statuses: Link
    /// Hypermedia Link
    public var html: Link
    /// Hypermedia Link
    public var issue: Link
    /// Hypermedia Link
    public var reviewComments: Link
    /// Hypermedia Link
    public var reviewComment: Link
    /// Hypermedia Link
    public var `self`: Link

    enum CodingKeys: String, CodingKey {
        case comments
        case commits
        case statuses
        case html
        case issue
        case reviewComments = "review_comments"
        case reviewComment = "review_comment"
        case `self`
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension PullRequestLinks {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        comments = try container.sdkDecodeRequired(.comments)
        commits = try container.sdkDecodeRequired(.commits)
        statuses = try container.sdkDecodeRequired(.statuses)
        html = try container.sdkDecodeRequired(.html)
        issue = try container.sdkDecodeRequired(.issue)
        reviewComments = try container.sdkDecodeRequired(.reviewComments)
        reviewComment = try container.sdkDecodeRequired(.reviewComment)
        self.`self` = try container.sdkDecodeRequired(.`self`)
    }
}

public extension PullRequestLinks {
    init(
        comments: Link,
        commits: Link,
        statuses: Link,
        html: Link,
        issue: Link,
        reviewComments: Link,
        reviewComment: Link,
        self selfValue: Link
    ) {
        (self.comments, self.commits) = (comments, commits)
        (self.statuses, self.html) = (statuses, html)
        (self.issue, self.reviewComments) = (issue, reviewComments)
        (self.reviewComment, self.`self`) = (reviewComment, selfValue)
    }
}

/// Required object value serialized in the `base` wire field.
public struct PullRequestBase: Codable {
    /// Required `string` value serialized in the `label` wire field.
    public var label: String
    /// Required `string` value serialized in the `ref` wire field.
    public var ref: String
    /// A repository on GitHub.
    public var repo: Repository
    /// Required `string` value serialized in the `sha` wire field.
    public var sha: String
    /// A GitHub user.
    public var user: SimpleUser

    enum CodingKeys: String, CodingKey {
        case label
        case ref
        case repo
        case sha
        case user
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension PullRequestBase {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.label) else {
            throw SdkValidationError(
                field: "label",
                code: "required",
                message: "Validation failed for 'label': value is required"
            )
        }
        guard container.contains(.ref) else {
            throw SdkValidationError(
                field: "ref",
                code: "required",
                message: "Validation failed for 'ref': value is required"
            )
        }
        guard container.contains(.repo) else {
            throw SdkValidationError(
                field: "repo",
                code: "required",
                message: "Validation failed for 'repo': value is required"
            )
        }
        guard container.contains(.sha) else {
            throw SdkValidationError(
                field: "sha",
                code: "required",
                message: "Validation failed for 'sha': value is required"
            )
        }
        guard container.contains(.user) else {
            throw SdkValidationError(
                field: "user",
                code: "required",
                message: "Validation failed for 'user': value is required"
            )
        }
        label = try container.sdkDecodeRequired(.label)
        ref = try container.sdkDecodeRequired(.ref)
        repo = try container.sdkDecodeRequired(.repo)
        sha = try container.sdkDecodeRequired(.sha)
        user = try container.sdkDecodeRequired(.user)
    }
}

public extension PullRequestBase {
    init(label: String, ref: String, repo: Repository, sha: String, user: SimpleUser) {
        (self.label, self.ref) = (label, ref)
        (self.repo, self.sha) = (repo, sha)
        self.user = user
    }
}

/// Required object value serialized in the `head` wire field.
public struct PullRequestHead: Codable {
    /// Required `string` value serialized in the `label` wire field.
    public var label: String
    /// Required `string` value serialized in the `ref` wire field.
    public var ref: String
    /// A repository on GitHub.
    public var repo: Repository
    /// Required `string` value serialized in the `sha` wire field.
    public var sha: String
    /// A GitHub user.
    public var user: SimpleUser

    enum CodingKeys: String, CodingKey {
        case label
        case ref
        case repo
        case sha
        case user
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension PullRequestHead {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.label) else {
            throw SdkValidationError(
                field: "label",
                code: "required",
                message: "Validation failed for 'label': value is required"
            )
        }
        guard container.contains(.ref) else {
            throw SdkValidationError(
                field: "ref",
                code: "required",
                message: "Validation failed for 'ref': value is required"
            )
        }
        guard container.contains(.repo) else {
            throw SdkValidationError(
                field: "repo",
                code: "required",
                message: "Validation failed for 'repo': value is required"
            )
        }
        guard container.contains(.sha) else {
            throw SdkValidationError(
                field: "sha",
                code: "required",
                message: "Validation failed for 'sha': value is required"
            )
        }
        guard container.contains(.user) else {
            throw SdkValidationError(
                field: "user",
                code: "required",
                message: "Validation failed for 'user': value is required"
            )
        }
        label = try container.sdkDecodeRequired(.label)
        ref = try container.sdkDecodeRequired(.ref)
        repo = try container.sdkDecodeRequired(.repo)
        sha = try container.sdkDecodeRequired(.sha)
        user = try container.sdkDecodeRequired(.user)
    }
}

public extension PullRequestHead {
    init(label: String, ref: String, repo: Repository, sha: String, user: SimpleUser) {
        (self.label, self.ref) = (label, ref)
        (self.repo, self.sha) = (repo, sha)
        self.user = user
    }
}

/// Required object value serialized in the `labels[]` wire field.
public struct PullRequestLabelsItem: Codable {
    /// Required `int64`-formatted value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Required `string` value serialized in the `url` wire field.
    public var url: String
    /// Required `string` value serialized in the `name` wire field.
    public var name: String
    /// Required `string` value serialized in the `description` wire field.
    public var description: String?
    /// Required `string` value serialized in the `color` wire field.
    public var color: String
    /// Required `boolean` value serialized in the `default` wire field.
    public var `default`: Bool
    /// The user who archived the label, or `null` if it has not been archived.
    public var archivedBy: PullRequestLabelsItemArchivedBy?

    enum CodingKeys: String, CodingKey {
        case id
        case nodeId = "node_id"
        case url
        case name
        case description
        case color
        case `default`
        case archivedBy = "archived_by"
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}
