// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

// Webhooks domain models
extension WebhooksPullRequest5RequestedReviewersItemVariant1 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(field: "id", code: "required", message: "Validation failed for 'id': value is required")
        }
        guard container.contains(.name) else {
            throw SdkValidationError(field: "name", code: "required", message: "Validation failed for 'name': value is required")
        }
        self.id = try container.sdkDecodeRequired(.id)
        self.name = try container.sdkDecodeRequired(.name)
        self.deleted = try container.sdkDecodeIfPresent(.deleted)
        self.description = try container.sdkDecodeIfPresent(.description)
        self.htmlUrl = try container.sdkDecodeIfPresent(.htmlUrl)
        self.membersUrl = try container.sdkDecodeIfPresent(.membersUrl)
        self.nodeId = try container.sdkDecodeIfPresent(.nodeId)
        self.parent = try container.sdkDecodeIfPresent(.parent)
        self.permission = try container.sdkDecodeIfPresent(.permission)
        self.privacy = try container.sdkDecodeIfPresent(.privacy)
        self.repositoriesUrl = try container.sdkDecodeIfPresent(.repositoriesUrl)
        self.slug = try container.sdkDecodeIfPresent(.slug)
        self.url = try container.sdkDecodeIfPresent(.url)
        if let value = self.htmlUrl {
            try sdkValidateUri("html_url", value)
        }
        if let value = self.repositoriesUrl {
            try sdkValidateUri("repositories_url", value)
        }
        if let value = self.url {
            try sdkValidateUri("url", value)
        }
    }
}

extension WebhooksPullRequest5RequestedReviewersItemVariant1 {
    public init(id: Int, name: String, deleted: Bool? = nil, description: String? = nil, htmlUrl: String? = nil, membersUrl: String? = nil, nodeId: String? = nil, parent: WebhooksPullRequest5RequestedReviewersItemVariant1Parent? = nil, permission: String? = nil, privacy: WebhooksPullRequest5RequestedReviewersItemVariant1Privacy? = nil, repositoriesUrl: String? = nil, slug: String? = nil, url: String? = nil) throws {
        (self.id, self.name) = (id, name)
        (self.deleted, self.description) = (deleted, description)
        (self.htmlUrl, self.membersUrl) = (htmlUrl, membersUrl)
        (self.nodeId, self.parent) = (nodeId, parent)
        (self.permission, self.privacy) = (permission, privacy)
        (self.repositoriesUrl, self.slug) = (repositoriesUrl, slug)
        self.url = url
        if let value = self.htmlUrl {
            try sdkValidateUri("html_url", value)
        }
        if let value = self.repositoriesUrl {
            try sdkValidateUri("repositories_url", value)
        }
        if let value = self.url {
            try sdkValidateUri("url", value)
        }
    }
}

/// Optional object value serialized in the `parent` wire field.
public struct WebhooksPullRequest5RequestedReviewersItemVariant1Parent: Codable {
    /// Description of the team
    public var description: String?
    /// Required `uri`-formatted value serialized in the `html_url` wire field.
    public var htmlUrl: String
    /// Unique identifier of the team
    public var id: Int
    /// Required `uri-template`-formatted value serialized in the `members_url` wire field.
    public var membersUrl: String
    /// Name of the team
    public var name: String
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Permission that the team will have for its repositories
    public var permission: String
    /// Required enumerated value serialized in the `privacy` wire field.
    public var privacy: WebhooksPullRequest5RequestedReviewersItemVariant1ParentPrivacy
    /// Required `uri`-formatted value serialized in the `repositories_url` wire field.
    public var repositoriesUrl: String
    /// Required `string` value serialized in the `slug` wire field.
    public var slug: String
    /// URL for the team
    public var url: String

    enum CodingKeys: String, CodingKey {
        case description
        case htmlUrl = "html_url"
        case id
        case membersUrl = "members_url"
        case name
        case nodeId = "node_id"
        case permission
        case privacy
        case repositoriesUrl = "repositories_url"
        case slug
        case url
    }

    private init(sdkCopy value: Self) { self = value }
}

extension WebhooksPullRequest5RequestedReviewersItemVariant1Parent {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.description = try container.sdkDecodeIfPresent(.description)
        self.htmlUrl = try container.sdkDecodeRequired(.htmlUrl)
        self.id = try container.sdkDecodeRequired(.id)
        self.membersUrl = try container.sdkDecodeRequired(.membersUrl)
        self.name = try container.sdkDecodeRequired(.name)
        self.nodeId = try container.sdkDecodeRequired(.nodeId)
        self.permission = try container.sdkDecodeRequired(.permission)
        self.privacy = try container.sdkDecodeRequired(.privacy)
        self.repositoriesUrl = try container.sdkDecodeRequired(.repositoriesUrl)
        self.slug = try container.sdkDecodeRequired(.slug)
        self.url = try container.sdkDecodeRequired(.url)
            try sdkValidateUri("html_url", self.htmlUrl)
            try sdkValidateUri("repositories_url", self.repositoriesUrl)
            try sdkValidateUri("url", self.url)
    }
}

extension WebhooksPullRequest5RequestedReviewersItemVariant1Parent {
    public init(description: String?, htmlUrl: String, id: Int, membersUrl: String, name: String, nodeId: String, permission: String, privacy: WebhooksPullRequest5RequestedReviewersItemVariant1ParentPrivacy, repositoriesUrl: String, slug: String, url: String) throws {
        (self.description, self.htmlUrl) = (description, htmlUrl)
        (self.id, self.membersUrl) = (id, membersUrl)
        (self.name, self.nodeId) = (name, nodeId)
        (self.permission, self.privacy) = (permission, privacy)
        (self.repositoriesUrl, self.slug) = (repositoriesUrl, slug)
        self.url = url
            try sdkValidateUri("html_url", self.htmlUrl)
            try sdkValidateUri("repositories_url", self.repositoriesUrl)
            try sdkValidateUri("url", self.url)
    }
}

/// Groups of organization members that gives permissions on specified repositories.
public struct WebhooksPullRequest5RequestedTeamsItem: Codable {
    /// Unique identifier of the team
    public var id: Int
    /// Name of the team
    public var name: String
    /// Optional `boolean` value serialized in the `deleted` wire field.
    public var deleted: Bool?
    /// Description of the team
    public var description: String?
    /// Optional `uri`-formatted value serialized in the `html_url` wire field.
    public var htmlUrl: String?
    /// Optional `uri-template`-formatted value serialized in the `members_url` wire field.
    public var membersUrl: String?
    /// Optional `string` value serialized in the `node_id` wire field.
    public var nodeId: String?
    /// Optional object value serialized in the `parent` wire field.
    public var parent: WebhooksPullRequest5RequestedTeamsItemParent?
    /// Permission that the team will have for its repositories
    public var permission: String?
    /// Optional enumerated value serialized in the `privacy` wire field.
    public var privacy: WebhooksPullRequest5RequestedTeamsItemPrivacy?
    /// Optional `uri`-formatted value serialized in the `repositories_url` wire field.
    public var repositoriesUrl: String?
    /// Optional `string` value serialized in the `slug` wire field.
    public var slug: String?
    /// URL for the team
    public var url: String?

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case deleted
        case description
        case htmlUrl = "html_url"
        case membersUrl = "members_url"
        case nodeId = "node_id"
        case parent
        case permission
        case privacy
        case repositoriesUrl = "repositories_url"
        case slug
        case url
    }

    private init(sdkCopy value: Self) { self = value }
}

extension WebhooksPullRequest5RequestedTeamsItem {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(field: "id", code: "required", message: "Validation failed for 'id': value is required")
        }
        guard container.contains(.name) else {
            throw SdkValidationError(field: "name", code: "required", message: "Validation failed for 'name': value is required")
        }
        self.id = try container.sdkDecodeRequired(.id)
        self.name = try container.sdkDecodeRequired(.name)
        self.deleted = try container.sdkDecodeIfPresent(.deleted)
        self.description = try container.sdkDecodeIfPresent(.description)
        self.htmlUrl = try container.sdkDecodeIfPresent(.htmlUrl)
        self.membersUrl = try container.sdkDecodeIfPresent(.membersUrl)
        self.nodeId = try container.sdkDecodeIfPresent(.nodeId)
        self.parent = try container.sdkDecodeIfPresent(.parent)
        self.permission = try container.sdkDecodeIfPresent(.permission)
        self.privacy = try container.sdkDecodeIfPresent(.privacy)
        self.repositoriesUrl = try container.sdkDecodeIfPresent(.repositoriesUrl)
        self.slug = try container.sdkDecodeIfPresent(.slug)
        self.url = try container.sdkDecodeIfPresent(.url)
        if let value = self.htmlUrl {
            try sdkValidateUri("html_url", value)
        }
        if let value = self.repositoriesUrl {
            try sdkValidateUri("repositories_url", value)
        }
        if let value = self.url {
            try sdkValidateUri("url", value)
        }
    }
}

extension WebhooksPullRequest5RequestedTeamsItem {
    public init(id: Int, name: String, deleted: Bool? = nil, description: String? = nil, htmlUrl: String? = nil, membersUrl: String? = nil, nodeId: String? = nil, parent: WebhooksPullRequest5RequestedTeamsItemParent? = nil, permission: String? = nil, privacy: WebhooksPullRequest5RequestedTeamsItemPrivacy? = nil, repositoriesUrl: String? = nil, slug: String? = nil, url: String? = nil) throws {
        (self.id, self.name) = (id, name)
        (self.deleted, self.description) = (deleted, description)
        (self.htmlUrl, self.membersUrl) = (htmlUrl, membersUrl)
        (self.nodeId, self.parent) = (nodeId, parent)
        (self.permission, self.privacy) = (permission, privacy)
        (self.repositoriesUrl, self.slug) = (repositoriesUrl, slug)
        self.url = url
        if let value = self.htmlUrl {
            try sdkValidateUri("html_url", value)
        }
        if let value = self.repositoriesUrl {
            try sdkValidateUri("repositories_url", value)
        }
        if let value = self.url {
            try sdkValidateUri("url", value)
        }
    }
}

/// Optional object value serialized in the `parent` wire field.
public struct WebhooksPullRequest5RequestedTeamsItemParent: Codable {
    /// Description of the team
    public var description: String?
    /// Required `uri`-formatted value serialized in the `html_url` wire field.
    public var htmlUrl: String
    /// Unique identifier of the team
    public var id: Int
    /// Required `uri-template`-formatted value serialized in the `members_url` wire field.
    public var membersUrl: String
    /// Name of the team
    public var name: String
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Permission that the team will have for its repositories
    public var permission: String
    /// Required enumerated value serialized in the `privacy` wire field.
    public var privacy: WebhooksPullRequest5RequestedTeamsItemParentPrivacy
    /// Required `uri`-formatted value serialized in the `repositories_url` wire field.
    public var repositoriesUrl: String
    /// Required `string` value serialized in the `slug` wire field.
    public var slug: String
    /// URL for the team
    public var url: String

    enum CodingKeys: String, CodingKey {
        case description
        case htmlUrl = "html_url"
        case id
        case membersUrl = "members_url"
        case name
        case nodeId = "node_id"
        case permission
        case privacy
        case repositoriesUrl = "repositories_url"
        case slug
        case url
    }

    private init(sdkCopy value: Self) { self = value }
}

extension WebhooksPullRequest5RequestedTeamsItemParent {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.description = try container.sdkDecodeIfPresent(.description)
        self.htmlUrl = try container.sdkDecodeRequired(.htmlUrl)
        self.id = try container.sdkDecodeRequired(.id)
        self.membersUrl = try container.sdkDecodeRequired(.membersUrl)
        self.name = try container.sdkDecodeRequired(.name)
        self.nodeId = try container.sdkDecodeRequired(.nodeId)
        self.permission = try container.sdkDecodeRequired(.permission)
        self.privacy = try container.sdkDecodeRequired(.privacy)
        self.repositoriesUrl = try container.sdkDecodeRequired(.repositoriesUrl)
        self.slug = try container.sdkDecodeRequired(.slug)
        self.url = try container.sdkDecodeRequired(.url)
            try sdkValidateUri("html_url", self.htmlUrl)
            try sdkValidateUri("repositories_url", self.repositoriesUrl)
            try sdkValidateUri("url", self.url)
    }
}

extension WebhooksPullRequest5RequestedTeamsItemParent {
    public init(description: String?, htmlUrl: String, id: Int, membersUrl: String, name: String, nodeId: String, permission: String, privacy: WebhooksPullRequest5RequestedTeamsItemParentPrivacy, repositoriesUrl: String, slug: String, url: String) throws {
        (self.description, self.htmlUrl) = (description, htmlUrl)
        (self.id, self.membersUrl) = (id, membersUrl)
        (self.name, self.nodeId) = (name, nodeId)
        (self.permission, self.privacy) = (permission, privacy)
        (self.repositoriesUrl, self.slug) = (repositoriesUrl, slug)
        self.url = url
            try sdkValidateUri("html_url", self.htmlUrl)
            try sdkValidateUri("repositories_url", self.repositoriesUrl)
            try sdkValidateUri("url", self.url)
    }
}

/// Required object value serialized in the `user` wire field.
public struct WebhooksPullRequest5User: Codable {
    /// Required `int64`-formatted value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `login` wire field.
    public var login: String
    /// Optional `uri`-formatted value serialized in the `avatar_url` wire field.
    public var avatarUrl: String?
    /// Optional `boolean` value serialized in the `deleted` wire field.
    public var deleted: Bool?
    /// Optional `string` value serialized in the `email` wire field.
    public var email: String?
    /// Optional `uri-template`-formatted value serialized in the `events_url` wire field.
    public var eventsUrl: String?
    /// Optional `uri`-formatted value serialized in the `followers_url` wire field.
    public var followersUrl: String?
    /// Optional `uri-template`-formatted value serialized in the `following_url` wire field.
    public var followingUrl: String?
    /// Optional `uri-template`-formatted value serialized in the `gists_url` wire field.
    public var gistsUrl: String?
    /// Optional `string` value serialized in the `gravatar_id` wire field.
    public var gravatarId: String?
    /// Optional `uri`-formatted value serialized in the `html_url` wire field.
    public var htmlUrl: String?
    /// Optional `string` value serialized in the `name` wire field.
    public var name: String?
    /// Optional `string` value serialized in the `node_id` wire field.
    public var nodeId: String?
    /// Optional `uri`-formatted value serialized in the `organizations_url` wire field.
    public var organizationsUrl: String?
    /// Optional `uri`-formatted value serialized in the `received_events_url` wire field.
    public var receivedEventsUrl: String?
    /// Optional `uri`-formatted value serialized in the `repos_url` wire field.
    public var reposUrl: String?
    /// Optional `boolean` value serialized in the `site_admin` wire field.
    public var siteAdmin: Bool?
    /// Optional `uri-template`-formatted value serialized in the `starred_url` wire field.
    public var starredUrl: String?
    /// Optional `uri`-formatted value serialized in the `subscriptions_url` wire field.
    public var subscriptionsUrl: String?
    /// Optional enumerated value serialized in the `type` wire field.
    public var type: WebhooksPullRequest5UserType?
    /// Optional `uri`-formatted value serialized in the `url` wire field.
    public var url: String?
    /// Optional `string` value serialized in the `user_view_type` wire field.
    public var userViewType: String?

    enum CodingKeys: String, CodingKey {
        case id
        case login
        case avatarUrl = "avatar_url"
        case deleted
        case email
        case eventsUrl = "events_url"
        case followersUrl = "followers_url"
        case followingUrl = "following_url"
        case gistsUrl = "gists_url"
        case gravatarId = "gravatar_id"
        case htmlUrl = "html_url"
        case name
        case nodeId = "node_id"
        case organizationsUrl = "organizations_url"
        case receivedEventsUrl = "received_events_url"
        case reposUrl = "repos_url"
        case siteAdmin = "site_admin"
        case starredUrl = "starred_url"
        case subscriptionsUrl = "subscriptions_url"
        case type
        case url
        case userViewType = "user_view_type"
    }

    private init(sdkCopy value: Self) { self = value }
}

extension WebhooksPullRequest5User {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(field: "id", code: "required", message: "Validation failed for 'id': value is required")
        }
        guard container.contains(.login) else {
            throw SdkValidationError(field: "login", code: "required", message: "Validation failed for 'login': value is required")
        }
        self.id = try container.sdkDecodeRequired(.id)
        self.login = try container.sdkDecodeRequired(.login)
        self.avatarUrl = try container.sdkDecodeIfPresent(.avatarUrl)
        self.deleted = try container.sdkDecodeIfPresent(.deleted)
        self.email = try container.sdkDecodeIfPresent(.email)
        self.eventsUrl = try container.sdkDecodeIfPresent(.eventsUrl)
        self.followersUrl = try container.sdkDecodeIfPresent(.followersUrl)
        self.followingUrl = try container.sdkDecodeIfPresent(.followingUrl)
        self.gistsUrl = try container.sdkDecodeIfPresent(.gistsUrl)
        self.gravatarId = try container.sdkDecodeIfPresent(.gravatarId)
        self.htmlUrl = try container.sdkDecodeIfPresent(.htmlUrl)
        self.name = try container.sdkDecodeIfPresent(.name)
        self.nodeId = try container.sdkDecodeIfPresent(.nodeId)
        self.organizationsUrl = try container.sdkDecodeIfPresent(.organizationsUrl)
        self.receivedEventsUrl = try container.sdkDecodeIfPresent(.receivedEventsUrl)
        self.reposUrl = try container.sdkDecodeIfPresent(.reposUrl)
        self.siteAdmin = try container.sdkDecodeIfPresent(.siteAdmin)
        self.starredUrl = try container.sdkDecodeIfPresent(.starredUrl)
        self.subscriptionsUrl = try container.sdkDecodeIfPresent(.subscriptionsUrl)
        self.type = try container.sdkDecodeIfPresent(.type)
        self.url = try container.sdkDecodeIfPresent(.url)
        self.userViewType = try container.sdkDecodeIfPresent(.userViewType)
        try sdkValidateConstraints()
    }
}

extension WebhooksPullRequest5User {
    public init(id: Int, login: String, avatarUrl: String? = nil, deleted: Bool? = nil, email: String? = nil, eventsUrl: String? = nil, followersUrl: String? = nil, followingUrl: String? = nil, gistsUrl: String? = nil, gravatarId: String? = nil, htmlUrl: String? = nil, name: String? = nil, nodeId: String? = nil, organizationsUrl: String? = nil, receivedEventsUrl: String? = nil, reposUrl: String? = nil, siteAdmin: Bool? = nil, starredUrl: String? = nil, subscriptionsUrl: String? = nil, type: WebhooksPullRequest5UserType? = nil, url: String? = nil, userViewType: String? = nil) throws {
        (self.id, self.login) = (id, login)
        (self.avatarUrl, self.deleted) = (avatarUrl, deleted)
        (self.email, self.eventsUrl) = (email, eventsUrl)
        (self.followersUrl, self.followingUrl) = (followersUrl, followingUrl)
        (self.gistsUrl, self.gravatarId) = (gistsUrl, gravatarId)
        (self.htmlUrl, self.name) = (htmlUrl, name)
        (self.nodeId, self.organizationsUrl) = (nodeId, organizationsUrl)
        (self.receivedEventsUrl, self.reposUrl) = (receivedEventsUrl, reposUrl)
        (self.siteAdmin, self.starredUrl) = (siteAdmin, starredUrl)
        (self.subscriptionsUrl, self.type) = (subscriptionsUrl, type)
        (self.url, self.userViewType) = (url, userViewType)
        try sdkValidateConstraints()
    }
}

extension WebhooksPullRequest5User {
    func sdkValidateConstraints() throws {
        if let value = self.avatarUrl {
            try sdkValidateUri("avatar_url", value)
        }
        if let value = self.followersUrl {
            try sdkValidateUri("followers_url", value)
        }
        if let value = self.htmlUrl {
            try sdkValidateUri("html_url", value)
        }
        if let value = self.organizationsUrl {
            try sdkValidateUri("organizations_url", value)
        }
        if let value = self.receivedEventsUrl {
            try sdkValidateUri("received_events_url", value)
        }
        if let value = self.reposUrl {
            try sdkValidateUri("repos_url", value)
        }
        if let value = self.subscriptionsUrl {
            try sdkValidateUri("subscriptions_url", value)
        }
        if let value = self.url {
            try sdkValidateUri("url", value)
        }
    }
}
