// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// Webhooks domain models
public typealias WebhooksEffectiveDate = String

public typealias WebhooksNullableString = String

public typealias WebhooksNumber = Int

public typealias WebhooksRef0 = String

public typealias WebhooksReviewers = [WebhooksReviewersItem]

/// The security alert of the vulnerable dependency.
public struct WebhooksAlert: Codable {
    /// Required `string` value serialized in the `affected_package_name` wire field.
    public var affectedPackageName: String
    /// Required `string` value serialized in the `affected_range` wire field.
    public var affectedRange: String
    /// Required `string` value serialized in the `created_at` wire field.
    public var createdAt: String
    /// Required `string` value serialized in the `external_identifier` wire field.
    public var externalIdentifier: String
    /// Required `uri`-formatted value serialized in the `external_reference` wire field.
    public var externalReference: String?
    /// Required `string` value serialized in the `ghsa_id` wire field.
    public var ghsaId: String
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Required `integer` value serialized in the `number` wire field.
    public var number: Int
    /// Required `string` value serialized in the `severity` wire field.
    public var severity: String
    /// Required enumerated value serialized in the `state` wire field.
    public var state: WebhooksAlertState
    /// Optional `string` value serialized in the `dismiss_reason` wire field.
    public var dismissReason: String?
    /// Optional `string` value serialized in the `dismissed_at` wire field.
    public var dismissedAt: String?
    /// Optional object value serialized in the `dismisser` wire field.
    public var dismisser: WebhooksAlertDismisser?
    /// Optional `string` value serialized in the `fix_reason` wire field.
    public var fixReason: String?
    /// Optional `date-time`-formatted value serialized in the `fixed_at` wire field.
    public var fixedAt: Date?
    /// Optional `string` value serialized in the `fixed_in` wire field.
    public var fixedIn: String?

    enum CodingKeys: String, CodingKey {
        case affectedPackageName = "affected_package_name"
        case affectedRange = "affected_range"
        case createdAt = "created_at"
        case externalIdentifier = "external_identifier"
        case externalReference = "external_reference"
        case ghsaId = "ghsa_id"
        case id
        case nodeId = "node_id"
        case number
        case severity
        case state
        case dismissReason = "dismiss_reason"
        case dismissedAt = "dismissed_at"
        case dismisser
        case fixReason = "fix_reason"
        case fixedAt = "fixed_at"
        case fixedIn = "fixed_in"
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhooksAlert {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        affectedPackageName = try container.sdkDecodeRequired(.affectedPackageName)
        affectedRange = try container.sdkDecodeRequired(.affectedRange)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        externalIdentifier = try container.sdkDecodeRequired(.externalIdentifier)
        externalReference = try container.sdkDecodeIfPresent(.externalReference)
        ghsaId = try container.sdkDecodeRequired(.ghsaId)
        id = try container.sdkDecodeRequired(.id)
        nodeId = try container.sdkDecodeRequired(.nodeId)
        number = try container.sdkDecodeRequired(.number)
        severity = try container.sdkDecodeRequired(.severity)
        state = try container.sdkDecodeRequired(.state)
        dismissReason = try container.sdkDecodeIfPresent(.dismissReason)
        dismissedAt = try container.sdkDecodeIfPresent(.dismissedAt)
        dismisser = try container.sdkDecodeIfPresent(.dismisser)
        fixReason = try container.sdkDecodeIfPresent(.fixReason)
        fixedAt = try container.sdkDecodeIfPresent(.fixedAt)
        fixedIn = try container.sdkDecodeIfPresent(.fixedIn)
        if let value = externalReference {
            try sdkValidateUri("external_reference", value)
        }
        if let value = fixedAt {
            try sdkValidateDateTime("fixed_at", sdkWireString(value))
        }
    }
}

public extension WebhooksAlert {
    init(
        affectedPackageName: String,
        affectedRange: String,
        createdAt: String,
        externalIdentifier: String,
        externalReference: String?,
        ghsaId: String,
        id: Int,
        nodeId: String,
        number: Int,
        severity: String,
        state: WebhooksAlertState,
        dismissReason: String? = nil,
        dismissedAt: String? = nil,
        dismisser: WebhooksAlertDismisser? = nil,
        fixReason: String? = nil,
        fixedAt: Date? = nil,
        fixedIn: String? = nil
    ) throws {
        (self.affectedPackageName, self.affectedRange) = (affectedPackageName, affectedRange)
        (self.createdAt, self.externalIdentifier) = (createdAt, externalIdentifier)
        (self.externalReference, self.ghsaId) = (externalReference, ghsaId)
        (self.id, self.nodeId) = (id, nodeId)
        (self.number, self.severity) = (number, severity)
        (self.state, self.dismissReason) = (state, dismissReason)
        (self.dismissedAt, self.dismisser) = (dismissedAt, dismisser)
        (self.fixReason, self.fixedAt) = (fixReason, fixedAt)
        self.fixedIn = fixedIn
        if let value = self.externalReference {
            try sdkValidateUri("external_reference", value)
        }
        if let value = self.fixedAt {
            try sdkValidateDateTime("fixed_at", sdkWireString(value))
        }
    }
}

/// Optional object value serialized in the `dismisser` wire field.
public struct WebhooksAlertDismisser: Codable {
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `login` wire field.
    public var login: String
    /// Optional `uri`-formatted value serialized in the `avatar_url` wire field.
    public var avatarUrl: String?
    /// Optional `boolean` value serialized in the `deleted` wire field.
    public var deleted: Bool?
    /// Optional `string` value serialized in the `email` wire field.
    public var email: String?
    /// Optional `uri-template`-formatted value serialized in the `events_url` wire field.
    public var eventsUrl: String?
    /// Optional `uri`-formatted value serialized in the `followers_url` wire field.
    public var followersUrl: String?
    /// Optional `uri-template`-formatted value serialized in the `following_url` wire field.
    public var followingUrl: String?
    /// Optional `uri-template`-formatted value serialized in the `gists_url` wire field.
    public var gistsUrl: String?
    /// Optional `string` value serialized in the `gravatar_id` wire field.
    public var gravatarId: String?
    /// Optional `uri`-formatted value serialized in the `html_url` wire field.
    public var htmlUrl: String?
    /// Optional `string` value serialized in the `name` wire field.
    public var name: String?
    /// Optional `string` value serialized in the `node_id` wire field.
    public var nodeId: String?
    /// Optional `uri`-formatted value serialized in the `organizations_url` wire field.
    public var organizationsUrl: String?
    /// Optional `uri`-formatted value serialized in the `received_events_url` wire field.
    public var receivedEventsUrl: String?
    /// Optional `uri`-formatted value serialized in the `repos_url` wire field.
    public var reposUrl: String?
    /// Optional `boolean` value serialized in the `site_admin` wire field.
    public var siteAdmin: Bool?
    /// Optional `uri-template`-formatted value serialized in the `starred_url` wire field.
    public var starredUrl: String?
    /// Optional `uri`-formatted value serialized in the `subscriptions_url` wire field.
    public var subscriptionsUrl: String?
    /// Optional enumerated value serialized in the `type` wire field.
    public var type: WebhooksAlertDismisserType?
    /// Optional `uri`-formatted value serialized in the `url` wire field.
    public var url: String?

    enum CodingKeys: String, CodingKey {
        case id
        case login
        case avatarUrl = "avatar_url"
        case deleted
        case email
        case eventsUrl = "events_url"
        case followersUrl = "followers_url"
        case followingUrl = "following_url"
        case gistsUrl = "gists_url"
        case gravatarId = "gravatar_id"
        case htmlUrl = "html_url"
        case name
        case nodeId = "node_id"
        case organizationsUrl = "organizations_url"
        case receivedEventsUrl = "received_events_url"
        case reposUrl = "repos_url"
        case siteAdmin = "site_admin"
        case starredUrl = "starred_url"
        case subscriptionsUrl = "subscriptions_url"
        case type
        case url
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhooksAlertDismisser {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(
                field: "id",
                code: "required",
                message: "Validation failed for 'id': value is required"
            )
        }
        guard container.contains(.login) else {
            throw SdkValidationError(
                field: "login",
                code: "required",
                message: "Validation failed for 'login': value is required"
            )
        }
        id = try container.sdkDecodeRequired(.id)
        login = try container.sdkDecodeRequired(.login)
        avatarUrl = try container.sdkDecodeIfPresent(.avatarUrl)
        deleted = try container.sdkDecodeIfPresent(.deleted)
        email = try container.sdkDecodeIfPresent(.email)
        eventsUrl = try container.sdkDecodeIfPresent(.eventsUrl)
        followersUrl = try container.sdkDecodeIfPresent(.followersUrl)
        followingUrl = try container.sdkDecodeIfPresent(.followingUrl)
        gistsUrl = try container.sdkDecodeIfPresent(.gistsUrl)
        gravatarId = try container.sdkDecodeIfPresent(.gravatarId)
        htmlUrl = try container.sdkDecodeIfPresent(.htmlUrl)
        name = try container.sdkDecodeIfPresent(.name)
        nodeId = try container.sdkDecodeIfPresent(.nodeId)
        organizationsUrl = try container.sdkDecodeIfPresent(.organizationsUrl)
        receivedEventsUrl = try container.sdkDecodeIfPresent(.receivedEventsUrl)
        reposUrl = try container.sdkDecodeIfPresent(.reposUrl)
        siteAdmin = try container.sdkDecodeIfPresent(.siteAdmin)
        starredUrl = try container.sdkDecodeIfPresent(.starredUrl)
        subscriptionsUrl = try container.sdkDecodeIfPresent(.subscriptionsUrl)
        type = try container.sdkDecodeIfPresent(.type)
        url = try container.sdkDecodeIfPresent(.url)
        try sdkValidateConstraints()
    }
}

public extension WebhooksAlertDismisser {
    init(
        id: Int,
        login: String,
        avatarUrl: String? = nil,
        deleted: Bool? = nil,
        email: String? = nil,
        eventsUrl: String? = nil,
        followersUrl: String? = nil,
        followingUrl: String? = nil,
        gistsUrl: String? = nil,
        gravatarId: String? = nil,
        htmlUrl: String? = nil,
        name: String? = nil,
        nodeId: String? = nil,
        organizationsUrl: String? = nil,
        receivedEventsUrl: String? = nil,
        reposUrl: String? = nil,
        siteAdmin: Bool? = nil,
        starredUrl: String? = nil,
        subscriptionsUrl: String? = nil,
        type: WebhooksAlertDismisserType? = nil,
        url: String? = nil
    ) throws {
        (self.id, self.login) = (id, login)
        (self.avatarUrl, self.deleted) = (avatarUrl, deleted)
        (self.email, self.eventsUrl) = (email, eventsUrl)
        (self.followersUrl, self.followingUrl) = (followersUrl, followingUrl)
        (self.gistsUrl, self.gravatarId) = (gistsUrl, gravatarId)
        (self.htmlUrl, self.name) = (htmlUrl, name)
        (self.nodeId, self.organizationsUrl) = (nodeId, organizationsUrl)
        (self.receivedEventsUrl, self.reposUrl) = (receivedEventsUrl, reposUrl)
        (self.siteAdmin, self.starredUrl) = (siteAdmin, starredUrl)
        (self.subscriptionsUrl, self.type) = (subscriptionsUrl, type)
        self.url = url
        try sdkValidateConstraints()
    }
}

extension WebhooksAlertDismisser {
    func sdkValidateConstraints() throws {
        if let value = avatarUrl {
            try sdkValidateUri("avatar_url", value)
        }
        if let value = followersUrl {
            try sdkValidateUri("followers_url", value)
        }
        if let value = htmlUrl {
            try sdkValidateUri("html_url", value)
        }
        if let value = organizationsUrl {
            try sdkValidateUri("organizations_url", value)
        }
        if let value = receivedEventsUrl {
            try sdkValidateUri("received_events_url", value)
        }
        if let value = reposUrl {
            try sdkValidateUri("repos_url", value)
        }
        if let value = subscriptionsUrl {
            try sdkValidateUri("subscriptions_url", value)
        }
        if let value = url {
            try sdkValidateUri("url", value)
        }
    }
}

/// Typed representation of the `WebhooksAnswer` API schema.
public struct WebhooksAnswer: Codable {
    /// How the author is associated with the repository.
    public var authorAssociation: WebhooksAnswerAuthorAssociation
    /// Required `string` value serialized in the `body` wire field.
    public var body: String
    /// Required `integer` value serialized in the `child_comment_count` wire field.
    public var childCommentCount: Int
    /// Required `date-time`-formatted value serialized in the `created_at` wire field.
    public var createdAt: Date
    /// Required `integer` value serialized in the `discussion_id` wire field.
    public var discussionId: Int
    /// Required `string` value serialized in the `html_url` wire field.
    public var htmlUrl: String
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `node_id` wire field.
    public var nodeId: String
    /// Required API value serialized in the `parent_id` wire field.
    public var parentId: JSONValue?
    /// Required `string` value serialized in the `repository_url` wire field.
    public var repositoryUrl: String
    /// Required `date-time`-formatted value serialized in the `updated_at` wire field.
    public var updatedAt: Date
    /// Required object value serialized in the `user` wire field.
    public var user: WebhooksAnswerUser?
    /// Optional object value serialized in the `reactions` wire field.
    public var reactions: WebhooksAnswerReactions?

    enum CodingKeys: String, CodingKey {
        case authorAssociation = "author_association"
        case body
        case childCommentCount = "child_comment_count"
        case createdAt = "created_at"
        case discussionId = "discussion_id"
        case htmlUrl = "html_url"
        case id
        case nodeId = "node_id"
        case parentId = "parent_id"
        case repositoryUrl = "repository_url"
        case updatedAt = "updated_at"
        case user
        case reactions
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhooksAnswer {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        authorAssociation = try container.sdkDecodeRequired(.authorAssociation)
        body = try container.sdkDecodeRequired(.body)
        childCommentCount = try container.sdkDecodeRequired(.childCommentCount)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        discussionId = try container.sdkDecodeRequired(.discussionId)
        htmlUrl = try container.sdkDecodeRequired(.htmlUrl)
        id = try container.sdkDecodeRequired(.id)
        nodeId = try container.sdkDecodeRequired(.nodeId)
        parentId = try container.sdkDecodeIfPresent(.parentId)
        repositoryUrl = try container.sdkDecodeRequired(.repositoryUrl)
        updatedAt = try container.sdkDecodeRequired(.updatedAt)
        user = try container.sdkDecodeIfPresent(.user)
        reactions = try container.sdkDecodeIfPresent(.reactions)
        try sdkValidateDateTime("created_at", sdkWireString(createdAt))
        try sdkValidateDateTime("updated_at", sdkWireString(updatedAt))
    }
}

public extension WebhooksAnswer {
    init(
        authorAssociation: WebhooksAnswerAuthorAssociation,
        body: String,
        childCommentCount: Int,
        createdAt: Date,
        discussionId: Int,
        htmlUrl: String,
        id: Int,
        nodeId: String,
        parentId: JSONValue?,
        repositoryUrl: String,
        updatedAt: Date,
        user: WebhooksAnswerUser?,
        reactions: WebhooksAnswerReactions? = nil
    ) throws {
        (self.authorAssociation, self.body) = (authorAssociation, body)
        (self.childCommentCount, self.createdAt) = (childCommentCount, createdAt)
        (self.discussionId, self.htmlUrl) = (discussionId, htmlUrl)
        (self.id, self.nodeId) = (id, nodeId)
        (self.parentId, self.repositoryUrl) = (parentId, repositoryUrl)
        (self.updatedAt, self.user) = (updatedAt, user)
        self.reactions = reactions
        try sdkValidateDateTime("created_at", sdkWireString(self.createdAt))
        try sdkValidateDateTime("updated_at", sdkWireString(self.updatedAt))
    }
}

/// Optional object value serialized in the `reactions` wire field.
public struct WebhooksAnswerReactions: Codable {
    /// Required `integer` value serialized in the `+1` wire field.
    public var plus1: Int
    /// Required `integer` value serialized in the `-1` wire field.
    public var minus1: Int
    /// Required `integer` value serialized in the `confused` wire field.
    public var confused: Int
    /// Required `integer` value serialized in the `eyes` wire field.
    public var eyes: Int
    /// Required `integer` value serialized in the `heart` wire field.
    public var heart: Int
    /// Required `integer` value serialized in the `hooray` wire field.
    public var hooray: Int
    /// Required `integer` value serialized in the `laugh` wire field.
    public var laugh: Int
    /// Required `integer` value serialized in the `rocket` wire field.
    public var rocket: Int
    /// Required `integer` value serialized in the `total_count` wire field.
    public var totalCount: Int
    /// Required `uri`-formatted value serialized in the `url` wire field.
    public var url: String

    enum CodingKeys: String, CodingKey {
        case plus1 = "+1"
        case minus1 = "-1"
        case confused
        case eyes
        case heart
        case hooray
        case laugh
        case rocket
        case totalCount = "total_count"
        case url
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhooksAnswerReactions {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        plus1 = try container.sdkDecodeRequired(.plus1)
        minus1 = try container.sdkDecodeRequired(.minus1)
        confused = try container.sdkDecodeRequired(.confused)
        eyes = try container.sdkDecodeRequired(.eyes)
        heart = try container.sdkDecodeRequired(.heart)
        hooray = try container.sdkDecodeRequired(.hooray)
        laugh = try container.sdkDecodeRequired(.laugh)
        rocket = try container.sdkDecodeRequired(.rocket)
        totalCount = try container.sdkDecodeRequired(.totalCount)
        url = try container.sdkDecodeRequired(.url)
        try sdkValidateUri("url", url)
    }
}

public extension WebhooksAnswerReactions {
    init(
        plus1: Int,
        minus1: Int,
        confused: Int,
        eyes: Int,
        heart: Int,
        hooray: Int,
        laugh: Int,
        rocket: Int,
        totalCount: Int,
        url: String
    ) throws {
        (self.plus1, self.minus1) = (plus1, minus1)
        (self.confused, self.eyes) = (confused, eyes)
        (self.heart, self.hooray) = (heart, hooray)
        (self.laugh, self.rocket) = (laugh, rocket)
        (self.totalCount, self.url) = (totalCount, url)
        try sdkValidateUri("url", self.url)
    }
}

/// Required object value serialized in the `user` wire field.
public struct WebhooksAnswerUser: Codable {
    /// Required `int64`-formatted value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `login` wire field.
    public var login: String
    /// Optional `uri`-formatted value serialized in the `avatar_url` wire field.
    public var avatarUrl: String?
    /// Optional `boolean` value serialized in the `deleted` wire field.
    public var deleted: Bool?
    /// Optional `string` value serialized in the `email` wire field.
    public var email: String?
    /// Optional `uri-template`-formatted value serialized in the `events_url` wire field.
    public var eventsUrl: String?
    /// Optional `uri`-formatted value serialized in the `followers_url` wire field.
    public var followersUrl: String?
    /// Optional `uri-template`-formatted value serialized in the `following_url` wire field.
    public var followingUrl: String?
    /// Optional `uri-template`-formatted value serialized in the `gists_url` wire field.
    public var gistsUrl: String?
    /// Optional `string` value serialized in the `gravatar_id` wire field.
    public var gravatarId: String?
    /// Optional `uri`-formatted value serialized in the `html_url` wire field.
    public var htmlUrl: String?
    /// Optional `string` value serialized in the `name` wire field.
    public var name: String?
    /// Optional `string` value serialized in the `node_id` wire field.
    public var nodeId: String?
    /// Optional `uri`-formatted value serialized in the `organizations_url` wire field.
    public var organizationsUrl: String?
    /// Optional `uri`-formatted value serialized in the `received_events_url` wire field.
    public var receivedEventsUrl: String?
    /// Optional `uri`-formatted value serialized in the `repos_url` wire field.
    public var reposUrl: String?
    /// Optional `boolean` value serialized in the `site_admin` wire field.
    public var siteAdmin: Bool?
    /// Optional `uri-template`-formatted value serialized in the `starred_url` wire field.
    public var starredUrl: String?
    /// Optional `uri`-formatted value serialized in the `subscriptions_url` wire field.
    public var subscriptionsUrl: String?
    /// Optional enumerated value serialized in the `type` wire field.
    public var type: WebhooksAnswerUserType?
    /// Optional `uri`-formatted value serialized in the `url` wire field.
    public var url: String?
    /// Optional `string` value serialized in the `user_view_type` wire field.
    public var userViewType: String?

    enum CodingKeys: String, CodingKey {
        case id
        case login
        case avatarUrl = "avatar_url"
        case deleted
        case email
        case eventsUrl = "events_url"
        case followersUrl = "followers_url"
        case followingUrl = "following_url"
        case gistsUrl = "gists_url"
        case gravatarId = "gravatar_id"
        case htmlUrl = "html_url"
        case name
        case nodeId = "node_id"
        case organizationsUrl = "organizations_url"
        case receivedEventsUrl = "received_events_url"
        case reposUrl = "repos_url"
        case siteAdmin = "site_admin"
        case starredUrl = "starred_url"
        case subscriptionsUrl = "subscriptions_url"
        case type
        case url
        case userViewType = "user_view_type"
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhooksAnswerUser {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(
                field: "id",
                code: "required",
                message: "Validation failed for 'id': value is required"
            )
        }
        guard container.contains(.login) else {
            throw SdkValidationError(
                field: "login",
                code: "required",
                message: "Validation failed for 'login': value is required"
            )
        }
        id = try container.sdkDecodeRequired(.id)
        login = try container.sdkDecodeRequired(.login)
        avatarUrl = try container.sdkDecodeIfPresent(.avatarUrl)
        deleted = try container.sdkDecodeIfPresent(.deleted)
        email = try container.sdkDecodeIfPresent(.email)
        eventsUrl = try container.sdkDecodeIfPresent(.eventsUrl)
        followersUrl = try container.sdkDecodeIfPresent(.followersUrl)
        followingUrl = try container.sdkDecodeIfPresent(.followingUrl)
        gistsUrl = try container.sdkDecodeIfPresent(.gistsUrl)
        gravatarId = try container.sdkDecodeIfPresent(.gravatarId)
        htmlUrl = try container.sdkDecodeIfPresent(.htmlUrl)
        name = try container.sdkDecodeIfPresent(.name)
        nodeId = try container.sdkDecodeIfPresent(.nodeId)
        organizationsUrl = try container.sdkDecodeIfPresent(.organizationsUrl)
        receivedEventsUrl = try container.sdkDecodeIfPresent(.receivedEventsUrl)
        reposUrl = try container.sdkDecodeIfPresent(.reposUrl)
        siteAdmin = try container.sdkDecodeIfPresent(.siteAdmin)
        starredUrl = try container.sdkDecodeIfPresent(.starredUrl)
        subscriptionsUrl = try container.sdkDecodeIfPresent(.subscriptionsUrl)
        type = try container.sdkDecodeIfPresent(.type)
        url = try container.sdkDecodeIfPresent(.url)
        userViewType = try container.sdkDecodeIfPresent(.userViewType)
        try sdkValidateConstraints()
    }
}
