// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// WebhookIssuesReopened domain models
/// Optional enumerated value serialized in the `workflows` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsWorkflows: RawRepresentable, Hashable, Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsWorkflows(rawValue: "read")
    public static let write = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsWorkflows(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Required enumerated value serialized in the `active_lock_reason` wire field.
public struct WebhookIssuesReopenedIssueActiveLockReason: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let resolved = WebhookIssuesReopenedIssueActiveLockReason(rawValue: "resolved")
    public static let offTopic = WebhookIssuesReopenedIssueActiveLockReason(rawValue: "off-topic")
    public static let tooHeated = WebhookIssuesReopenedIssueActiveLockReason(rawValue: "too heated")
    public static let spam = WebhookIssuesReopenedIssueActiveLockReason(rawValue: "spam")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `organization_administration` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgX0626ea730a: RawRepresentable, Hashable,
    Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgX0626ea730a(rawValue: "read")
    public static let write =
        WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgX0626ea730a(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `organization_projects` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgX1b44bd468d: RawRepresentable, Hashable,
    Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgX1b44bd468d(rawValue: "read")
    public static let write =
        WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgX1b44bd468d(rawValue: "write")
    public static let admin =
        WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgX1b44bd468d(rawValue: "admin")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `type` wire field.
public struct WebhookIssuesReopenedIssueAssigneesItemType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let bot = WebhookIssuesReopenedIssueAssigneesItemType(rawValue: "Bot")
    public static let user = WebhookIssuesReopenedIssueAssigneesItemType(rawValue: "User")
    public static let organization = WebhookIssuesReopenedIssueAssigneesItemType(rawValue: "Organization")
    public static let mannequin = WebhookIssuesReopenedIssueAssigneesItemType(rawValue: "Mannequin")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// How the author is associated with the repository.
public struct WebhookIssuesReopenedIssueAuthorAssociation: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let collaborator = WebhookIssuesReopenedIssueAuthorAssociation(rawValue: "COLLABORATOR")
    public static let contributor = WebhookIssuesReopenedIssueAuthorAssociation(rawValue: "CONTRIBUTOR")
    public static let firstTimer = WebhookIssuesReopenedIssueAuthorAssociation(rawValue: "FIRST_TIMER")
    public static let firstTimeContributor =
        WebhookIssuesReopenedIssueAuthorAssociation(rawValue: "FIRST_TIME_CONTRIBUTOR")
    public static let mannequin = WebhookIssuesReopenedIssueAuthorAssociation(rawValue: "MANNEQUIN")
    public static let member = WebhookIssuesReopenedIssueAuthorAssociation(rawValue: "MEMBER")
    public static let none = WebhookIssuesReopenedIssueAuthorAssociation(rawValue: "NONE")
    public static let owner = WebhookIssuesReopenedIssueAuthorAssociation(rawValue: "OWNER")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `pull_requests` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsPullRequests: RawRepresentable, Hashable,
    Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsPullRequests(rawValue: "read")
    public static let write = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsPullRequests(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// State of the issue; either 'open' or 'closed'
public struct WebhookIssuesReopenedIssueState: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let open = WebhookIssuesReopenedIssueState(rawValue: "open")
    public static let closed = WebhookIssuesReopenedIssueState(rawValue: "closed")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `content_references` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsConX8c9cf56f0c: RawRepresentable, Hashable,
    Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsConX8c9cf56f0c(rawValue: "read")
    public static let write =
        WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsConX8c9cf56f0c(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `organization_secrets` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgXd7cd696083: RawRepresentable, Hashable,
    Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgXd7cd696083(rawValue: "read")
    public static let write =
        WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgXd7cd696083(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `organization_packages` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgX57a29c9788: RawRepresentable, Hashable,
    Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgX57a29c9788(rawValue: "read")
    public static let write =
        WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgX57a29c9788(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `organization_plan` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgXae82a01526: RawRepresentable, Hashable,
    Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgXae82a01526(rawValue: "read")
    public static let write =
        WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsOrgXae82a01526(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `statuses` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsStatuses: RawRepresentable, Hashable, Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsStatuses(rawValue: "read")
    public static let write = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsStatuses(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `members` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsMembers: RawRepresentable, Hashable, Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsMembers(rawValue: "read")
    public static let write = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsMembers(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `deployments` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsDeployments: RawRepresentable, Hashable,
    Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsDeployments(rawValue: "read")
    public static let write = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsDeployments(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// The state of the milestone.
public struct WebhookIssuesReopenedIssueMilestoneState: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let open = WebhookIssuesReopenedIssueMilestoneState(rawValue: "open")
    public static let closed = WebhookIssuesReopenedIssueMilestoneState(rawValue: "closed")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `type` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppOwnerType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let bot = WebhookIssuesReopenedIssuePerformedViaGithubAppOwnerType(rawValue: "Bot")
    public static let user = WebhookIssuesReopenedIssuePerformedViaGithubAppOwnerType(rawValue: "User")
    public static let organization = WebhookIssuesReopenedIssuePerformedViaGithubAppOwnerType(rawValue: "Organization")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `administration` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsAdministration: RawRepresentable, Hashable,
    Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsAdministration(rawValue: "read")
    public static let write =
        WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsAdministration(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `emails` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsEmails: RawRepresentable, Hashable, Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsEmails(rawValue: "read")
    public static let write = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsEmails(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `contents` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsContents: RawRepresentable, Hashable, Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsContents(rawValue: "read")
    public static let write = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsContents(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `checks` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsChecks: RawRepresentable, Hashable, Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsChecks(rawValue: "read")
    public static let write = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsChecks(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `security_events` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsSecurityEvents: RawRepresentable, Hashable,
    Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsSecurityEvents(rawValue: "read")
    public static let write =
        WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsSecurityEvents(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `single_file` wire field.
public struct WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsSingleFile: RawRepresentable, Hashable, Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let read = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsSingleFile(rawValue: "read")
    public static let write = WebhookIssuesReopenedIssuePerformedViaGithubAppPermissionsSingleFile(rawValue: "write")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
