// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// WebhookPullRequestReviewRequested domain models
public extension WebhookPullRequestReviewRequestedVariant0PullRequestMilestoneCreator {
    init(
        id: Int,
        login: String,
        avatarUrl: String? = nil,
        deleted: Bool? = nil,
        email: String? = nil,
        eventsUrl: String? = nil,
        followersUrl: String? = nil,
        followingUrl: String? = nil,
        gistsUrl: String? = nil,
        gravatarId: String? = nil,
        htmlUrl: String? = nil,
        name: String? = nil,
        nodeId: String? = nil,
        organizationsUrl: String? = nil,
        receivedEventsUrl: String? = nil,
        reposUrl: String? = nil,
        siteAdmin: Bool? = nil,
        starredUrl: String? = nil,
        subscriptionsUrl: String? = nil,
        type: WebhookPullRequestReviewRequestedVariant0PullRequestMilestoneCreatorType? = nil,
        url: String? = nil,
        userViewType: String? = nil
    ) throws {
        (self.id, self.login) = (id, login)
        (self.avatarUrl, self.deleted) = (avatarUrl, deleted)
        (self.email, self.eventsUrl) = (email, eventsUrl)
        (self.followersUrl, self.followingUrl) = (followersUrl, followingUrl)
        (self.gistsUrl, self.gravatarId) = (gistsUrl, gravatarId)
        (self.htmlUrl, self.name) = (htmlUrl, name)
        (self.nodeId, self.organizationsUrl) = (nodeId, organizationsUrl)
        (self.receivedEventsUrl, self.reposUrl) = (receivedEventsUrl, reposUrl)
        (self.siteAdmin, self.starredUrl) = (siteAdmin, starredUrl)
        (self.subscriptionsUrl, self.type) = (subscriptionsUrl, type)
        (self.url, self.userViewType) = (url, userViewType)
        try sdkValidateConstraints()
    }
}

extension WebhookPullRequestReviewRequestedVariant0PullRequestMilestoneCreator {
    func sdkValidateConstraints() throws {
        if let value = avatarUrl {
            try sdkValidateUri("avatar_url", value)
        }
        if let value = followersUrl {
            try sdkValidateUri("followers_url", value)
        }
        if let value = htmlUrl {
            try sdkValidateUri("html_url", value)
        }
        if let value = organizationsUrl {
            try sdkValidateUri("organizations_url", value)
        }
        if let value = receivedEventsUrl {
            try sdkValidateUri("received_events_url", value)
        }
        if let value = reposUrl {
            try sdkValidateUri("repos_url", value)
        }
        if let value = subscriptionsUrl {
            try sdkValidateUri("subscriptions_url", value)
        }
        if let value = url {
            try sdkValidateUri("url", value)
        }
    }
}

public enum WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX0cdce265c4 {
    case webhookPullRequestReviewRequestedVariant0PullRequestRequestedX262e9a9d0e(
        WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX262e9a9d0e
    )
    case webhookPullRequestReviewRequestedVariant0PullRequestRequestedXac20b0f837(
        WebhookPullRequestReviewRequestedVariant0PullRequestRequestedXac20b0f837
    )
}

extension WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX0cdce265c4: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX0cdce265c4"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX262e9a9d0e.self
        ) {
            return .webhookPullRequestReviewRequestedVariant0PullRequestRequestedX262e9a9d0e(value)
        }
        if let value = try? container.decode(
            WebhookPullRequestReviewRequestedVariant0PullRequestRequestedXac20b0f837.self
        ) {
            return .webhookPullRequestReviewRequestedVariant0PullRequestRequestedXac20b0f837(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .webhookPullRequestReviewRequestedVariant0PullRequestRequestedX262e9a9d0e(value): try container
            .encode(value); return true
        case let .webhookPullRequestReviewRequestedVariant0PullRequestRequestedXac20b0f837(value): try container
            .encode(value); return true
        }
    }
}

public struct WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX262e9a9d0e: Codable {
    public var id: Int
    public var login: String
    public var avatarUrl: String?
    public var deleted: Bool?
    public var email: String?
    public var eventsUrl: String?
    public var followersUrl: String?
    public var followingUrl: String?
    public var gistsUrl: String?
    public var gravatarId: String?
    public var htmlUrl: String?
    public var name: String?
    public var nodeId: String?
    public var organizationsUrl: String?
    public var receivedEventsUrl: String?
    public var reposUrl: String?
    public var siteAdmin: Bool?
    public var starredUrl: String?
    public var subscriptionsUrl: String?
    public var type: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX5177f61575?
    public var url: String?
    public var userViewType: String?

    enum CodingKeys: String, CodingKey {
        case id
        case login
        case avatarUrl = "avatar_url"
        case deleted
        case email
        case eventsUrl = "events_url"
        case followersUrl = "followers_url"
        case followingUrl = "following_url"
        case gistsUrl = "gists_url"
        case gravatarId = "gravatar_id"
        case htmlUrl = "html_url"
        case name
        case nodeId = "node_id"
        case organizationsUrl = "organizations_url"
        case receivedEventsUrl = "received_events_url"
        case reposUrl = "repos_url"
        case siteAdmin = "site_admin"
        case starredUrl = "starred_url"
        case subscriptionsUrl = "subscriptions_url"
        case type
        case url
        case userViewType = "user_view_type"
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX262e9a9d0e {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(
                field: "id",
                code: "required",
                message: "Validation failed for 'id': value is required"
            )
        }
        guard container.contains(.login) else {
            throw SdkValidationError(
                field: "login",
                code: "required",
                message: "Validation failed for 'login': value is required"
            )
        }
        id = try container.sdkDecodeRequired(.id)
        login = try container.sdkDecodeRequired(.login)
        avatarUrl = try container.sdkDecodeIfPresent(.avatarUrl)
        deleted = try container.sdkDecodeIfPresent(.deleted)
        email = try container.sdkDecodeIfPresent(.email)
        eventsUrl = try container.sdkDecodeIfPresent(.eventsUrl)
        followersUrl = try container.sdkDecodeIfPresent(.followersUrl)
        followingUrl = try container.sdkDecodeIfPresent(.followingUrl)
        gistsUrl = try container.sdkDecodeIfPresent(.gistsUrl)
        gravatarId = try container.sdkDecodeIfPresent(.gravatarId)
        htmlUrl = try container.sdkDecodeIfPresent(.htmlUrl)
        name = try container.sdkDecodeIfPresent(.name)
        nodeId = try container.sdkDecodeIfPresent(.nodeId)
        organizationsUrl = try container.sdkDecodeIfPresent(.organizationsUrl)
        receivedEventsUrl = try container.sdkDecodeIfPresent(.receivedEventsUrl)
        reposUrl = try container.sdkDecodeIfPresent(.reposUrl)
        siteAdmin = try container.sdkDecodeIfPresent(.siteAdmin)
        starredUrl = try container.sdkDecodeIfPresent(.starredUrl)
        subscriptionsUrl = try container.sdkDecodeIfPresent(.subscriptionsUrl)
        type = try container.sdkDecodeIfPresent(.type)
        url = try container.sdkDecodeIfPresent(.url)
        userViewType = try container.sdkDecodeIfPresent(.userViewType)
        try sdkValidateConstraints()
    }
}

public extension WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX262e9a9d0e {
    init(
        id: Int,
        login: String,
        avatarUrl: String? = nil,
        deleted: Bool? = nil,
        email: String? = nil,
        eventsUrl: String? = nil,
        followersUrl: String? = nil,
        followingUrl: String? = nil,
        gistsUrl: String? = nil,
        gravatarId: String? = nil,
        htmlUrl: String? = nil,
        name: String? = nil,
        nodeId: String? = nil,
        organizationsUrl: String? = nil,
        receivedEventsUrl: String? = nil,
        reposUrl: String? = nil,
        siteAdmin: Bool? = nil,
        starredUrl: String? = nil,
        subscriptionsUrl: String? = nil,
        type: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX5177f61575? = nil,
        url: String? = nil,
        userViewType: String? = nil
    ) throws {
        (self.id, self.login) = (id, login)
        (self.avatarUrl, self.deleted) = (avatarUrl, deleted)
        (self.email, self.eventsUrl) = (email, eventsUrl)
        (self.followersUrl, self.followingUrl) = (followersUrl, followingUrl)
        (self.gistsUrl, self.gravatarId) = (gistsUrl, gravatarId)
        (self.htmlUrl, self.name) = (htmlUrl, name)
        (self.nodeId, self.organizationsUrl) = (nodeId, organizationsUrl)
        (self.receivedEventsUrl, self.reposUrl) = (receivedEventsUrl, reposUrl)
        (self.siteAdmin, self.starredUrl) = (siteAdmin, starredUrl)
        (self.subscriptionsUrl, self.type) = (subscriptionsUrl, type)
        (self.url, self.userViewType) = (url, userViewType)
        try sdkValidateConstraints()
    }
}

extension WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX262e9a9d0e {
    func sdkValidateConstraints() throws {
        if let value = avatarUrl {
            try sdkValidateUri("avatar_url", value)
        }
        if let value = followersUrl {
            try sdkValidateUri("followers_url", value)
        }
        if let value = htmlUrl {
            try sdkValidateUri("html_url", value)
        }
        if let value = organizationsUrl {
            try sdkValidateUri("organizations_url", value)
        }
        if let value = receivedEventsUrl {
            try sdkValidateUri("received_events_url", value)
        }
        if let value = reposUrl {
            try sdkValidateUri("repos_url", value)
        }
        if let value = subscriptionsUrl {
            try sdkValidateUri("subscriptions_url", value)
        }
        if let value = url {
            try sdkValidateUri("url", value)
        }
    }
}

/// Groups of organization members that gives permissions on specified repositories.
public struct WebhookPullRequestReviewRequestedVariant0PullRequestRequestedXac20b0f837: Codable {
    /// Description of the team
    public var description: String?
    public var htmlUrl: String
    /// Unique identifier of the team
    public var id: Int
    public var membersUrl: String
    /// Name of the team
    public var name: String
    public var nodeId: String
    /// Permission that the team will have for its repositories
    public var permission: String
    public var privacy: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX26567f40db
    public var repositoriesUrl: String
    public var slug: String
    /// URL for the team
    public var url: String
    public var deleted: Bool?
    public var parent: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedXf2473eedbd?

    enum CodingKeys: String, CodingKey {
        case description
        case htmlUrl = "html_url"
        case id
        case membersUrl = "members_url"
        case name
        case nodeId = "node_id"
        case permission
        case privacy
        case repositoriesUrl = "repositories_url"
        case slug
        case url
        case deleted
        case parent
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhookPullRequestReviewRequestedVariant0PullRequestRequestedXac20b0f837 {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        description = try container.sdkDecodeIfPresent(.description)
        htmlUrl = try container.sdkDecodeRequired(.htmlUrl)
        id = try container.sdkDecodeRequired(.id)
        membersUrl = try container.sdkDecodeRequired(.membersUrl)
        name = try container.sdkDecodeRequired(.name)
        nodeId = try container.sdkDecodeRequired(.nodeId)
        permission = try container.sdkDecodeRequired(.permission)
        privacy = try container.sdkDecodeRequired(.privacy)
        repositoriesUrl = try container.sdkDecodeRequired(.repositoriesUrl)
        slug = try container.sdkDecodeRequired(.slug)
        url = try container.sdkDecodeRequired(.url)
        deleted = try container.sdkDecodeIfPresent(.deleted)
        parent = try container.sdkDecodeIfPresent(.parent)
        try sdkValidateUri("html_url", htmlUrl)
        try sdkValidateUri("repositories_url", repositoriesUrl)
        try sdkValidateUri("url", url)
    }
}

public extension WebhookPullRequestReviewRequestedVariant0PullRequestRequestedXac20b0f837 {
    init(
        description: String?,
        htmlUrl: String,
        id: Int,
        membersUrl: String,
        name: String,
        nodeId: String,
        permission: String,
        privacy: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX26567f40db,
        repositoriesUrl: String,
        slug: String,
        url: String,
        deleted: Bool? = nil,
        parent: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedXf2473eedbd? = nil
    ) throws {
        (self.description, self.htmlUrl) = (description, htmlUrl)
        (self.id, self.membersUrl) = (id, membersUrl)
        (self.name, self.nodeId) = (name, nodeId)
        (self.permission, self.privacy) = (permission, privacy)
        (self.repositoriesUrl, self.slug) = (repositoriesUrl, slug)
        (self.url, self.deleted) = (url, deleted)
        self.parent = parent
        try sdkValidateUri("html_url", self.htmlUrl)
        try sdkValidateUri("repositories_url", self.repositoriesUrl)
        try sdkValidateUri("url", self.url)
    }
}

public struct WebhookPullRequestReviewRequestedVariant0PullRequestRequestedXf2473eedbd: Codable {
    /// Description of the team
    public var description: String?
    public var htmlUrl: String
    /// Unique identifier of the team
    public var id: Int
    public var membersUrl: String
    /// Name of the team
    public var name: String
    public var nodeId: String
    /// Permission that the team will have for its repositories
    public var permission: String
    public var privacy: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX42edbb26dd
    public var repositoriesUrl: String
    public var slug: String
    /// URL for the team
    public var url: String

    enum CodingKeys: String, CodingKey {
        case description
        case htmlUrl = "html_url"
        case id
        case membersUrl = "members_url"
        case name
        case nodeId = "node_id"
        case permission
        case privacy
        case repositoriesUrl = "repositories_url"
        case slug
        case url
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhookPullRequestReviewRequestedVariant0PullRequestRequestedXf2473eedbd {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        description = try container.sdkDecodeIfPresent(.description)
        htmlUrl = try container.sdkDecodeRequired(.htmlUrl)
        id = try container.sdkDecodeRequired(.id)
        membersUrl = try container.sdkDecodeRequired(.membersUrl)
        name = try container.sdkDecodeRequired(.name)
        nodeId = try container.sdkDecodeRequired(.nodeId)
        permission = try container.sdkDecodeRequired(.permission)
        privacy = try container.sdkDecodeRequired(.privacy)
        repositoriesUrl = try container.sdkDecodeRequired(.repositoriesUrl)
        slug = try container.sdkDecodeRequired(.slug)
        url = try container.sdkDecodeRequired(.url)
        try sdkValidateUri("html_url", htmlUrl)
        try sdkValidateUri("repositories_url", repositoriesUrl)
        try sdkValidateUri("url", url)
    }
}

public extension WebhookPullRequestReviewRequestedVariant0PullRequestRequestedXf2473eedbd {
    init(
        description: String?,
        htmlUrl: String,
        id: Int,
        membersUrl: String,
        name: String,
        nodeId: String,
        permission: String,
        privacy: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX42edbb26dd,
        repositoriesUrl: String,
        slug: String,
        url: String
    ) throws {
        (self.description, self.htmlUrl) = (description, htmlUrl)
        (self.id, self.membersUrl) = (id, membersUrl)
        (self.name, self.nodeId) = (name, nodeId)
        (self.permission, self.privacy) = (permission, privacy)
        (self.repositoriesUrl, self.slug) = (repositoriesUrl, slug)
        self.url = url
        try sdkValidateUri("html_url", self.htmlUrl)
        try sdkValidateUri("repositories_url", self.repositoriesUrl)
        try sdkValidateUri("url", self.url)
    }
}

/// Groups of organization members that gives permissions on specified repositories.
public struct WebhookPullRequestReviewRequestedVariant0PullRequestRequestedTeamsItem: Codable {
    /// Unique identifier of the team
    public var id: Int
    /// Name of the team
    public var name: String
    public var deleted: Bool?
    /// Description of the team
    public var description: String?
    public var htmlUrl: String?
    public var membersUrl: String?
    public var nodeId: String?
    public var parent: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX284e32f947?
    /// Permission that the team will have for its repositories
    public var permission: String?
    public var privacy: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedXe691f9513d?
    public var repositoriesUrl: String?
    public var slug: String?
    /// URL for the team
    public var url: String?

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case deleted
        case description
        case htmlUrl = "html_url"
        case membersUrl = "members_url"
        case nodeId = "node_id"
        case parent
        case permission
        case privacy
        case repositoriesUrl = "repositories_url"
        case slug
        case url
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhookPullRequestReviewRequestedVariant0PullRequestRequestedTeamsItem {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(
                field: "id",
                code: "required",
                message: "Validation failed for 'id': value is required"
            )
        }
        guard container.contains(.name) else {
            throw SdkValidationError(
                field: "name",
                code: "required",
                message: "Validation failed for 'name': value is required"
            )
        }
        id = try container.sdkDecodeRequired(.id)
        name = try container.sdkDecodeRequired(.name)
        deleted = try container.sdkDecodeIfPresent(.deleted)
        description = try container.sdkDecodeIfPresent(.description)
        htmlUrl = try container.sdkDecodeIfPresent(.htmlUrl)
        membersUrl = try container.sdkDecodeIfPresent(.membersUrl)
        nodeId = try container.sdkDecodeIfPresent(.nodeId)
        parent = try container.sdkDecodeIfPresent(.parent)
        permission = try container.sdkDecodeIfPresent(.permission)
        privacy = try container.sdkDecodeIfPresent(.privacy)
        repositoriesUrl = try container.sdkDecodeIfPresent(.repositoriesUrl)
        slug = try container.sdkDecodeIfPresent(.slug)
        url = try container.sdkDecodeIfPresent(.url)
        if let value = htmlUrl {
            try sdkValidateUri("html_url", value)
        }
        if let value = repositoriesUrl {
            try sdkValidateUri("repositories_url", value)
        }
        if let value = url {
            try sdkValidateUri("url", value)
        }
    }
}

public extension WebhookPullRequestReviewRequestedVariant0PullRequestRequestedTeamsItem {
    init(
        id: Int,
        name: String,
        deleted: Bool? = nil,
        description: String? = nil,
        htmlUrl: String? = nil,
        membersUrl: String? = nil,
        nodeId: String? = nil,
        parent: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX284e32f947? = nil,
        permission: String? = nil,
        privacy: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedXe691f9513d? = nil,
        repositoriesUrl: String? = nil,
        slug: String? = nil,
        url: String? = nil
    ) throws {
        (self.id, self.name) = (id, name)
        (self.deleted, self.description) = (deleted, description)
        (self.htmlUrl, self.membersUrl) = (htmlUrl, membersUrl)
        (self.nodeId, self.parent) = (nodeId, parent)
        (self.permission, self.privacy) = (permission, privacy)
        (self.repositoriesUrl, self.slug) = (repositoriesUrl, slug)
        self.url = url
        if let value = self.htmlUrl {
            try sdkValidateUri("html_url", value)
        }
        if let value = self.repositoriesUrl {
            try sdkValidateUri("repositories_url", value)
        }
        if let value = self.url {
            try sdkValidateUri("url", value)
        }
    }
}

public struct WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX284e32f947: Codable {
    /// Description of the team
    public var description: String?
    public var htmlUrl: String
    /// Unique identifier of the team
    public var id: Int
    public var membersUrl: String
    /// Name of the team
    public var name: String
    public var nodeId: String
    /// Permission that the team will have for its repositories
    public var permission: String
    public var privacy: WebhookPullRequestReviewRequestedVariant0PullRequestRequestedX5793e9a656
    public var repositoriesUrl: String
    public var slug: String
    /// URL for the team
    public var url: String

    enum CodingKeys: String, CodingKey {
        case description
        case htmlUrl = "html_url"
        case id
        case membersUrl = "members_url"
        case name
        case nodeId = "node_id"
        case permission
        case privacy
        case repositoriesUrl = "repositories_url"
        case slug
        case url
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}
