// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// WebhookWorkflowRunRequested domain models
/// Optional enumerated value serialized in the `type` wire field.
public struct WebhookWorkflowRunRequestedWorkflowRunRepositoryOwnerType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let bot = WebhookWorkflowRunRequestedWorkflowRunRepositoryOwnerType(rawValue: "Bot")
    public static let user = WebhookWorkflowRunRequestedWorkflowRunRepositoryOwnerType(rawValue: "User")
    public static let organization = WebhookWorkflowRunRequestedWorkflowRunRepositoryOwnerType(rawValue: "Organization")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Required enumerated value serialized in the `status` wire field.
public struct WebhookWorkflowRunRequestedWorkflowRunStatus: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let requested = WebhookWorkflowRunRequestedWorkflowRunStatus(rawValue: "requested")
    public static let inProgress = WebhookWorkflowRunRequestedWorkflowRunStatus(rawValue: "in_progress")
    public static let completed = WebhookWorkflowRunRequestedWorkflowRunStatus(rawValue: "completed")
    public static let queued = WebhookWorkflowRunRequestedWorkflowRunStatus(rawValue: "queued")
    public static let pending = WebhookWorkflowRunRequestedWorkflowRunStatus(rawValue: "pending")
    public static let waiting = WebhookWorkflowRunRequestedWorkflowRunStatus(rawValue: "waiting")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
