// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// WebhookDiscussionCategoryChanged domain models
/// Typed representation of the `WebhookDiscussionCategoryChanged` API schema.
public struct WebhookDiscussionCategoryChanged: Codable {
    /// Required enumerated value serialized in the `action` wire field.
    public var action: WebhookDiscussionCategoryChangedAction
    /// Required object value serialized in the `changes` wire field.
    public var changes: WebhookDiscussionCategoryChangedChanges
    /// A Discussion in a repository.
    public var discussion: Discussion
    /// The repository on GitHub where the event occurred. Webhook payloads contain the `repository` property when
    /// the event occurs from activity in a repository.
    public var repository: RepositoryWebhooks
    /// A GitHub user.
    public var sender: SimpleUser
    /// An enterprise on GitHub. Webhook payloads contain the `enterprise` property when the webhook is configured
    /// on an enterprise account or an organization that's part of an enterprise account. For more information, see
    /// "About enterprise accounts."
    public var enterprise: EnterpriseWebhooks?
    /// The GitHub App installation. Webhook payloads contain the `installation` property when the event is
    /// configured for and sent to a GitHub App. For more information, see "Using webhooks with GitHub Apps."
    public var installation: SimpleInstallation?
    /// A GitHub organization. Webhook payloads contain the `organization` property when the webhook is configured
    /// for an organization, or when the event occurs from activity in a repository owned by an organization.
    public var organization: OrganizationSimpleWebhooks?

    enum CodingKeys: String, CodingKey {
        case action
        case changes
        case discussion
        case repository
        case sender
        case enterprise
        case installation
        case organization
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhookDiscussionCategoryChanged {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.action) else {
            throw SdkValidationError(
                field: "action",
                code: "required",
                message: "Validation failed for 'action': value is required"
            )
        }
        guard container.contains(.changes) else {
            throw SdkValidationError(
                field: "changes",
                code: "required",
                message: "Validation failed for 'changes': value is required"
            )
        }
        guard container.contains(.discussion) else {
            throw SdkValidationError(
                field: "discussion",
                code: "required",
                message: "Validation failed for 'discussion': value is required"
            )
        }
        guard container.contains(.repository) else {
            throw SdkValidationError(
                field: "repository",
                code: "required",
                message: "Validation failed for 'repository': value is required"
            )
        }
        guard container.contains(.sender) else {
            throw SdkValidationError(
                field: "sender",
                code: "required",
                message: "Validation failed for 'sender': value is required"
            )
        }
        action = try container.sdkDecodeRequired(.action)
        changes = try container.sdkDecodeRequired(.changes)
        discussion = try container.sdkDecodeRequired(.discussion)
        repository = try container.sdkDecodeRequired(.repository)
        sender = try container.sdkDecodeRequired(.sender)
        enterprise = try container.sdkDecodeIfPresent(.enterprise)
        installation = try container.sdkDecodeIfPresent(.installation)
        organization = try container.sdkDecodeIfPresent(.organization)
    }
}

public extension WebhookDiscussionCategoryChanged {
    init(
        action: WebhookDiscussionCategoryChangedAction,
        changes: WebhookDiscussionCategoryChangedChanges,
        discussion: Discussion,
        repository: RepositoryWebhooks,
        sender: SimpleUser,
        enterprise: EnterpriseWebhooks? = nil,
        installation: SimpleInstallation? = nil,
        organization: OrganizationSimpleWebhooks? = nil
    ) {
        (self.action, self.changes) = (action, changes)
        (self.discussion, self.repository) = (discussion, repository)
        (self.sender, self.enterprise) = (sender, enterprise)
        (self.installation, self.organization) = (installation, organization)
    }
}

/// Required object value serialized in the `changes` wire field.
public struct WebhookDiscussionCategoryChangedChanges: Codable {
    /// Required object value serialized in the `category` wire field.
    public var category: WebhookDiscussionCategoryChangedChangesCategory

    enum CodingKeys: String, CodingKey {
        case category
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhookDiscussionCategoryChangedChanges {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.category) else {
            throw SdkValidationError(
                field: "category",
                code: "required",
                message: "Validation failed for 'category': value is required"
            )
        }
        category = try container.sdkDecodeRequired(.category)
    }
}

public extension WebhookDiscussionCategoryChangedChanges {
    init(category: WebhookDiscussionCategoryChangedChangesCategory) {
        self.category = category
    }
}

/// Required object value serialized in the `category` wire field.
public struct WebhookDiscussionCategoryChangedChangesCategory: Codable {
    /// Required object value serialized in the `from` wire field.
    public var from: WebhookDiscussionCategoryChangedChangesCategoryFrom

    enum CodingKeys: String, CodingKey {
        case from
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhookDiscussionCategoryChangedChangesCategory {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.from) else {
            throw SdkValidationError(
                field: "from",
                code: "required",
                message: "Validation failed for 'from': value is required"
            )
        }
        from = try container.sdkDecodeRequired(.from)
    }
}

public extension WebhookDiscussionCategoryChangedChangesCategory {
    init(from: WebhookDiscussionCategoryChangedChangesCategoryFrom) {
        self.from = from
    }
}

/// Required object value serialized in the `from` wire field.
public struct WebhookDiscussionCategoryChangedChangesCategoryFrom: Codable {
    /// Required `date-time`-formatted value serialized in the `created_at` wire field.
    public var createdAt: Date
    /// Required `string` value serialized in the `description` wire field.
    public var description: String
    /// Required `string` value serialized in the `emoji` wire field.
    public var emoji: String
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `boolean` value serialized in the `is_answerable` wire field.
    public var isAnswerable: Bool
    /// Required `string` value serialized in the `name` wire field.
    public var name: String
    /// Required `integer` value serialized in the `repository_id` wire field.
    public var repositoryId: Int
    /// Required `string` value serialized in the `slug` wire field.
    public var slug: String
    /// Required `string` value serialized in the `updated_at` wire field.
    public var updatedAt: String
    /// Optional `string` value serialized in the `node_id` wire field.
    public var nodeId: String?

    enum CodingKeys: String, CodingKey {
        case createdAt = "created_at"
        case description
        case emoji
        case id
        case isAnswerable = "is_answerable"
        case name
        case repositoryId = "repository_id"
        case slug
        case updatedAt = "updated_at"
        case nodeId = "node_id"
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension WebhookDiscussionCategoryChangedChangesCategoryFrom {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        createdAt = try container.sdkDecodeRequired(.createdAt)
        description = try container.sdkDecodeRequired(.description)
        emoji = try container.sdkDecodeRequired(.emoji)
        id = try container.sdkDecodeRequired(.id)
        isAnswerable = try container.sdkDecodeRequired(.isAnswerable)
        name = try container.sdkDecodeRequired(.name)
        repositoryId = try container.sdkDecodeRequired(.repositoryId)
        slug = try container.sdkDecodeRequired(.slug)
        updatedAt = try container.sdkDecodeRequired(.updatedAt)
        nodeId = try container.sdkDecodeIfPresent(.nodeId)
        try sdkValidateDateTime("created_at", sdkWireString(createdAt))
    }
}

public extension WebhookDiscussionCategoryChangedChangesCategoryFrom {
    init(
        createdAt: Date,
        description: String,
        emoji: String,
        id: Int,
        isAnswerable: Bool,
        name: String,
        repositoryId: Int,
        slug: String,
        updatedAt: String,
        nodeId: String? = nil
    ) throws {
        (self.createdAt, self.description) = (createdAt, description)
        (self.emoji, self.id) = (emoji, id)
        (self.isAnswerable, self.name) = (isAnswerable, name)
        (self.repositoryId, self.slug) = (repositoryId, slug)
        (self.updatedAt, self.nodeId) = (updatedAt, nodeId)
        try sdkValidateDateTime("created_at", sdkWireString(self.createdAt))
    }
}

/// Required enumerated value serialized in the `action` wire field.
public struct WebhookDiscussionCategoryChangedAction: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let categoryChanged = WebhookDiscussionCategoryChangedAction(rawValue: "category_changed")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
