// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

// WebhookDeploymentReviewRequested domain models
extension WebhookDeploymentReviewRequestedWorkflowRunHeadRepository {
    mutating func sdkDecodeFieldsPart3(_ container: KeyedDecodingContainer<CodingKeys>) throws {
        self.issueEventsUrl = try container.sdkDecodeIfPresent(.issueEventsUrl)
        self.issuesUrl = try container.sdkDecodeIfPresent(.issuesUrl)
        self.keysUrl = try container.sdkDecodeIfPresent(.keysUrl)
        self.labelsUrl = try container.sdkDecodeIfPresent(.labelsUrl)
        self.languagesUrl = try container.sdkDecodeIfPresent(.languagesUrl)
        self.mergesUrl = try container.sdkDecodeIfPresent(.mergesUrl)
        self.milestonesUrl = try container.sdkDecodeIfPresent(.milestonesUrl)
        self.name = try container.sdkDecodeIfPresent(.name)
        self.nodeId = try container.sdkDecodeIfPresent(.nodeId)
        self.notificationsUrl = try container.sdkDecodeIfPresent(.notificationsUrl)
        self.owner = try container.sdkDecodeIfPresent(.owner)
        self.`private` = try container.sdkDecodeIfPresent(.`private`)
    }
}

extension WebhookDeploymentReviewRequestedWorkflowRunHeadRepository {
    mutating func sdkDecodeFieldsPart4(_ container: KeyedDecodingContainer<CodingKeys>) throws {
        self.pullsUrl = try container.sdkDecodeIfPresent(.pullsUrl)
        self.releasesUrl = try container.sdkDecodeIfPresent(.releasesUrl)
        self.stargazersUrl = try container.sdkDecodeIfPresent(.stargazersUrl)
        self.statusesUrl = try container.sdkDecodeIfPresent(.statusesUrl)
        self.subscribersUrl = try container.sdkDecodeIfPresent(.subscribersUrl)
        self.subscriptionUrl = try container.sdkDecodeIfPresent(.subscriptionUrl)
        self.tagsUrl = try container.sdkDecodeIfPresent(.tagsUrl)
        self.teamsUrl = try container.sdkDecodeIfPresent(.teamsUrl)
        self.treesUrl = try container.sdkDecodeIfPresent(.treesUrl)
        self.url = try container.sdkDecodeIfPresent(.url)
    }
}

/// Optional object value serialized in the `owner` wire field.
public struct WebhookDeploymentReviewRequestedWorkflowRunHeadRepositoryOwner: Codable {
    /// Optional `string` value serialized in the `avatar_url` wire field.
    public var avatarUrl: String?
    /// Optional `string` value serialized in the `events_url` wire field.
    public var eventsUrl: String?
    /// Optional `string` value serialized in the `followers_url` wire field.
    public var followersUrl: String?
    /// Optional `string` value serialized in the `following_url` wire field.
    public var followingUrl: String?
    /// Optional `string` value serialized in the `gists_url` wire field.
    public var gistsUrl: String?
    /// Optional `string` value serialized in the `gravatar_id` wire field.
    public var gravatarId: String?
    /// Optional `string` value serialized in the `html_url` wire field.
    public var htmlUrl: String?
    /// Optional `integer` value serialized in the `id` wire field.
    public var id: Int?
    /// Optional `string` value serialized in the `login` wire field.
    public var login: String?
    /// Optional `string` value serialized in the `node_id` wire field.
    public var nodeId: String?
    /// Optional `string` value serialized in the `organizations_url` wire field.
    public var organizationsUrl: String?
    /// Optional `string` value serialized in the `received_events_url` wire field.
    public var receivedEventsUrl: String?
    /// Optional `string` value serialized in the `repos_url` wire field.
    public var reposUrl: String?
    /// Optional `boolean` value serialized in the `site_admin` wire field.
    public var siteAdmin: Bool?
    /// Optional `string` value serialized in the `starred_url` wire field.
    public var starredUrl: String?
    /// Optional `string` value serialized in the `subscriptions_url` wire field.
    public var subscriptionsUrl: String?
    /// Optional `string` value serialized in the `type` wire field.
    public var type: String?
    /// Optional `string` value serialized in the `url` wire field.
    public var url: String?
    /// Optional `string` value serialized in the `user_view_type` wire field.
    public var userViewType: String?

    enum CodingKeys: String, CodingKey {
        case avatarUrl = "avatar_url"
        case eventsUrl = "events_url"
        case followersUrl = "followers_url"
        case followingUrl = "following_url"
        case gistsUrl = "gists_url"
        case gravatarId = "gravatar_id"
        case htmlUrl = "html_url"
        case id
        case login
        case nodeId = "node_id"
        case organizationsUrl = "organizations_url"
        case receivedEventsUrl = "received_events_url"
        case reposUrl = "repos_url"
        case siteAdmin = "site_admin"
        case starredUrl = "starred_url"
        case subscriptionsUrl = "subscriptions_url"
        case type
        case url
        case userViewType = "user_view_type"
    }

    init() {
        (self.avatarUrl, self.eventsUrl, self.followersUrl, self.followingUrl, self.gistsUrl) = (nil, nil, nil, nil, nil)
        (self.gravatarId, self.htmlUrl, self.id, self.login, self.nodeId) = (nil, nil, nil, nil, nil)
        (self.organizationsUrl, self.receivedEventsUrl, self.reposUrl, self.siteAdmin, self.starredUrl) = (nil, nil, nil, nil, nil)
        (self.subscriptionsUrl, self.type, self.url, self.userViewType) = (nil, nil, nil, nil)
    }
}

extension WebhookDeploymentReviewRequestedWorkflowRunHeadRepositoryOwner {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.avatarUrl = try container.sdkDecodeIfPresent(.avatarUrl)
        self.eventsUrl = try container.sdkDecodeIfPresent(.eventsUrl)
        self.followersUrl = try container.sdkDecodeIfPresent(.followersUrl)
        self.followingUrl = try container.sdkDecodeIfPresent(.followingUrl)
        self.gistsUrl = try container.sdkDecodeIfPresent(.gistsUrl)
        self.gravatarId = try container.sdkDecodeIfPresent(.gravatarId)
        self.htmlUrl = try container.sdkDecodeIfPresent(.htmlUrl)
        self.id = try container.sdkDecodeIfPresent(.id)
        self.login = try container.sdkDecodeIfPresent(.login)
        self.nodeId = try container.sdkDecodeIfPresent(.nodeId)
        self.organizationsUrl = try container.sdkDecodeIfPresent(.organizationsUrl)
        self.receivedEventsUrl = try container.sdkDecodeIfPresent(.receivedEventsUrl)
        self.reposUrl = try container.sdkDecodeIfPresent(.reposUrl)
        self.siteAdmin = try container.sdkDecodeIfPresent(.siteAdmin)
        self.starredUrl = try container.sdkDecodeIfPresent(.starredUrl)
        self.subscriptionsUrl = try container.sdkDecodeIfPresent(.subscriptionsUrl)
        self.type = try container.sdkDecodeIfPresent(.type)
        self.url = try container.sdkDecodeIfPresent(.url)
        self.userViewType = try container.sdkDecodeIfPresent(.userViewType)
    }
}

extension WebhookDeploymentReviewRequestedWorkflowRunHeadRepositoryOwner {
    public init(avatarUrl: String? = nil, eventsUrl: String? = nil, followersUrl: String? = nil, followingUrl: String? = nil, gistsUrl: String? = nil, gravatarId: String? = nil, htmlUrl: String? = nil, id: Int? = nil, login: String? = nil, nodeId: String? = nil, organizationsUrl: String? = nil, receivedEventsUrl: String? = nil, reposUrl: String? = nil, siteAdmin: Bool? = nil, starredUrl: String? = nil, subscriptionsUrl: String? = nil, type: String? = nil, url: String? = nil, userViewType: String? = nil) {
        self.init()
        (self.avatarUrl, self.eventsUrl) = (avatarUrl, eventsUrl)
        (self.followersUrl, self.followingUrl) = (followersUrl, followingUrl)
        (self.gistsUrl, self.gravatarId) = (gistsUrl, gravatarId)
        (self.htmlUrl, self.id) = (htmlUrl, id)
        (self.login, self.nodeId) = (login, nodeId)
        (self.organizationsUrl, self.receivedEventsUrl) = (organizationsUrl, receivedEventsUrl)
        (self.reposUrl, self.siteAdmin) = (reposUrl, siteAdmin)
        (self.starredUrl, self.subscriptionsUrl) = (starredUrl, subscriptionsUrl)
        (self.type, self.url) = (type, url)
        self.userViewType = userViewType
    }
}

/// Required object value serialized in the `pull_requests[]` wire field.
public struct WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItem: Codable {
    /// Required object value serialized in the `base` wire field.
    public var base: WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemBase
    /// Required object value serialized in the `head` wire field.
    public var head: WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemHead
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `integer` value serialized in the `number` wire field.
    public var number: Int
    /// Required `uri`-formatted value serialized in the `url` wire field.
    public var url: String

    enum CodingKeys: String, CodingKey {
        case base
        case head
        case id
        case number
        case url
    }

    private init(sdkCopy value: Self) { self = value }
}

extension WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItem {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.base) else {
            throw SdkValidationError(field: "base", code: "required", message: "Validation failed for 'base': value is required")
        }
        guard container.contains(.head) else {
            throw SdkValidationError(field: "head", code: "required", message: "Validation failed for 'head': value is required")
        }
        guard container.contains(.id) else {
            throw SdkValidationError(field: "id", code: "required", message: "Validation failed for 'id': value is required")
        }
        guard container.contains(.number) else {
            throw SdkValidationError(field: "number", code: "required", message: "Validation failed for 'number': value is required")
        }
        guard container.contains(.url) else {
            throw SdkValidationError(field: "url", code: "required", message: "Validation failed for 'url': value is required")
        }
        self.base = try container.sdkDecodeRequired(.base)
        self.head = try container.sdkDecodeRequired(.head)
        self.id = try container.sdkDecodeRequired(.id)
        self.number = try container.sdkDecodeRequired(.number)
        self.url = try container.sdkDecodeRequired(.url)
            try sdkValidateUri("url", self.url)
    }
}

extension WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItem {
    public init(base: WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemBase, head: WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemHead, id: Int, number: Int, url: String) throws {
        (self.base, self.head) = (base, head)
        (self.id, self.number) = (id, number)
        self.url = url
            try sdkValidateUri("url", self.url)
    }
}

/// Required object value serialized in the `base` wire field.
public struct WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemBase: Codable {
    /// Required `string` value serialized in the `ref` wire field.
    public var ref: String
    /// Required object value serialized in the `repo` wire field.
    public var repo: WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemBaseRepo
    /// Required `string` value serialized in the `sha` wire field.
    public var sha: String

    enum CodingKeys: String, CodingKey {
        case ref
        case repo
        case sha
    }

    private init(sdkCopy value: Self) { self = value }
}

extension WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemBase {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.ref) else {
            throw SdkValidationError(field: "ref", code: "required", message: "Validation failed for 'ref': value is required")
        }
        guard container.contains(.repo) else {
            throw SdkValidationError(field: "repo", code: "required", message: "Validation failed for 'repo': value is required")
        }
        guard container.contains(.sha) else {
            throw SdkValidationError(field: "sha", code: "required", message: "Validation failed for 'sha': value is required")
        }
        self.ref = try container.sdkDecodeRequired(.ref)
        self.repo = try container.sdkDecodeRequired(.repo)
        self.sha = try container.sdkDecodeRequired(.sha)
    }
}

extension WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemBase {
    public init(ref: String, repo: WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemBaseRepo, sha: String) {
        (self.ref, self.repo) = (ref, repo)
        self.sha = sha
    }
}

/// Required object value serialized in the `repo` wire field.
public struct WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemBaseRepo: Codable {
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `name` wire field.
    public var name: String
    /// Required `uri`-formatted value serialized in the `url` wire field.
    public var url: String

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case url
    }

    private init(sdkCopy value: Self) { self = value }
}

extension WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemBaseRepo {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(field: "id", code: "required", message: "Validation failed for 'id': value is required")
        }
        guard container.contains(.name) else {
            throw SdkValidationError(field: "name", code: "required", message: "Validation failed for 'name': value is required")
        }
        guard container.contains(.url) else {
            throw SdkValidationError(field: "url", code: "required", message: "Validation failed for 'url': value is required")
        }
        self.id = try container.sdkDecodeRequired(.id)
        self.name = try container.sdkDecodeRequired(.name)
        self.url = try container.sdkDecodeRequired(.url)
            try sdkValidateUri("url", self.url)
    }
}

extension WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemBaseRepo {
    public init(id: Int, name: String, url: String) throws {
        (self.id, self.name) = (id, name)
        self.url = url
            try sdkValidateUri("url", self.url)
    }
}

/// Required object value serialized in the `head` wire field.
public struct WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemHead: Codable {
    /// Required `string` value serialized in the `ref` wire field.
    public var ref: String
    /// Required object value serialized in the `repo` wire field.
    public var repo: WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemHeadRepo
    /// Required `string` value serialized in the `sha` wire field.
    public var sha: String

    enum CodingKeys: String, CodingKey {
        case ref
        case repo
        case sha
    }

    private init(sdkCopy value: Self) { self = value }
}

extension WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemHead {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.ref) else {
            throw SdkValidationError(field: "ref", code: "required", message: "Validation failed for 'ref': value is required")
        }
        guard container.contains(.repo) else {
            throw SdkValidationError(field: "repo", code: "required", message: "Validation failed for 'repo': value is required")
        }
        guard container.contains(.sha) else {
            throw SdkValidationError(field: "sha", code: "required", message: "Validation failed for 'sha': value is required")
        }
        self.ref = try container.sdkDecodeRequired(.ref)
        self.repo = try container.sdkDecodeRequired(.repo)
        self.sha = try container.sdkDecodeRequired(.sha)
    }
}

extension WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemHead {
    public init(ref: String, repo: WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemHeadRepo, sha: String) {
        (self.ref, self.repo) = (ref, repo)
        self.sha = sha
    }
}

/// Required object value serialized in the `repo` wire field.
public struct WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemHeadRepo: Codable {
    /// Required `integer` value serialized in the `id` wire field.
    public var id: Int
    /// Required `string` value serialized in the `name` wire field.
    public var name: String
    /// Required `uri`-formatted value serialized in the `url` wire field.
    public var url: String

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case url
    }

    private init(sdkCopy value: Self) { self = value }
}

extension WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemHeadRepo {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.id) else {
            throw SdkValidationError(field: "id", code: "required", message: "Validation failed for 'id': value is required")
        }
        guard container.contains(.name) else {
            throw SdkValidationError(field: "name", code: "required", message: "Validation failed for 'name': value is required")
        }
        guard container.contains(.url) else {
            throw SdkValidationError(field: "url", code: "required", message: "Validation failed for 'url': value is required")
        }
        self.id = try container.sdkDecodeRequired(.id)
        self.name = try container.sdkDecodeRequired(.name)
        self.url = try container.sdkDecodeRequired(.url)
            try sdkValidateUri("url", self.url)
    }
}

extension WebhookDeploymentReviewRequestedWorkflowRunPullRequestsItemHeadRepo {
    public init(id: Int, name: String, url: String) throws {
        (self.id, self.name) = (id, name)
        self.url = url
            try sdkValidateUri("url", self.url)
    }
}

/// Required object value serialized in the `referenced_workflows[]` wire field.
public struct WebhookDeploymentReviewRequestedWorkflowRunReferencedWorkflowsItem: Codable {
    /// Required `string` value serialized in the `path` wire field.
    public var path: String
    /// Required `string` value serialized in the `sha` wire field.
    public var sha: String
    /// Optional `string` value serialized in the `ref` wire field.
    public var ref: String?

    enum CodingKeys: String, CodingKey {
        case path
        case sha
        case ref
    }

    private init(sdkCopy value: Self) { self = value }
}

extension WebhookDeploymentReviewRequestedWorkflowRunReferencedWorkflowsItem {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.path) else {
            throw SdkValidationError(field: "path", code: "required", message: "Validation failed for 'path': value is required")
        }
        guard container.contains(.sha) else {
            throw SdkValidationError(field: "sha", code: "required", message: "Validation failed for 'sha': value is required")
        }
        self.path = try container.sdkDecodeRequired(.path)
        self.sha = try container.sdkDecodeRequired(.sha)
        self.ref = try container.sdkDecodeIfPresent(.ref)
    }
}

extension WebhookDeploymentReviewRequestedWorkflowRunReferencedWorkflowsItem {
    public init(path: String, sha: String, ref: String? = nil) {
        (self.path, self.sha) = (path, sha)
        self.ref = ref
    }
}
