// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// WebhookPullRequestLocked domain models
/// The default value for a merge commit message. - `PR_TITLE` - default to the pull request's title. -
/// `PR_BODY` - default to the pull request's body. - `BLANK` - default to a blank commit message.
public struct WebhookPullRequestLockedPullRequestBaseRepoMergeCommitMessage: RawRepresentable, Hashable, Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let prBody = WebhookPullRequestLockedPullRequestBaseRepoMergeCommitMessage(rawValue: "PR_BODY")
    public static let prTitle = WebhookPullRequestLockedPullRequestBaseRepoMergeCommitMessage(rawValue: "PR_TITLE")
    public static let blank = WebhookPullRequestLockedPullRequestBaseRepoMergeCommitMessage(rawValue: "BLANK")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `type` wire field.
public struct WebhookPullRequestLockedPullRequestUserType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let bot = WebhookPullRequestLockedPullRequestUserType(rawValue: "Bot")
    public static let user = WebhookPullRequestLockedPullRequestUserType(rawValue: "User")
    public static let organization = WebhookPullRequestLockedPullRequestUserType(rawValue: "Organization")
    public static let mannequin = WebhookPullRequestLockedPullRequestUserType(rawValue: "Mannequin")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `type` wire field.
public struct WebhookPullRequestLockedPullRequestRequestedReviewersItemVariant0Type: RawRepresentable, Hashable,
    Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let bot = WebhookPullRequestLockedPullRequestRequestedReviewersItemVariant0Type(rawValue: "Bot")
    public static let user = WebhookPullRequestLockedPullRequestRequestedReviewersItemVariant0Type(rawValue: "User")
    public static let organization =
        WebhookPullRequestLockedPullRequestRequestedReviewersItemVariant0Type(rawValue: "Organization")
    public static let mannequin =
        WebhookPullRequestLockedPullRequestRequestedReviewersItemVariant0Type(rawValue: "Mannequin")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `type` wire field.
public struct WebhookPullRequestLockedPullRequestHeadUserType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let bot = WebhookPullRequestLockedPullRequestHeadUserType(rawValue: "Bot")
    public static let user = WebhookPullRequestLockedPullRequestHeadUserType(rawValue: "User")
    public static let organization = WebhookPullRequestLockedPullRequestHeadUserType(rawValue: "Organization")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `type` wire field.
public struct WebhookPullRequestLockedPullRequestMergedByType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let bot = WebhookPullRequestLockedPullRequestMergedByType(rawValue: "Bot")
    public static let user = WebhookPullRequestLockedPullRequestMergedByType(rawValue: "User")
    public static let organization = WebhookPullRequestLockedPullRequestMergedByType(rawValue: "Organization")
    public static let mannequin = WebhookPullRequestLockedPullRequestMergedByType(rawValue: "Mannequin")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Required enumerated value serialized in the `visibility` wire field.
public struct WebhookPullRequestLockedPullRequestHeadRepoVisibility: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let `public` = WebhookPullRequestLockedPullRequestHeadRepoVisibility(rawValue: "public")
    public static let `private` = WebhookPullRequestLockedPullRequestHeadRepoVisibility(rawValue: "private")
    public static let `internal` = WebhookPullRequestLockedPullRequestHeadRepoVisibility(rawValue: "internal")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `type` wire field.
public struct WebhookPullRequestLockedPullRequestAssigneeType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let bot = WebhookPullRequestLockedPullRequestAssigneeType(rawValue: "Bot")
    public static let user = WebhookPullRequestLockedPullRequestAssigneeType(rawValue: "User")
    public static let organization = WebhookPullRequestLockedPullRequestAssigneeType(rawValue: "Organization")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Required enumerated value serialized in the `privacy` wire field.
public struct WebhookPullRequestLockedPullRequestRequestedTeamsItemParentPrivacy: RawRepresentable, Hashable, Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let open = WebhookPullRequestLockedPullRequestRequestedTeamsItemParentPrivacy(rawValue: "open")
    public static let closed = WebhookPullRequestLockedPullRequestRequestedTeamsItemParentPrivacy(rawValue: "closed")
    public static let secret = WebhookPullRequestLockedPullRequestRequestedTeamsItemParentPrivacy(rawValue: "secret")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// How the author is associated with the repository.
public struct WebhookPullRequestLockedPullRequestAuthorAssociation: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let collaborator = WebhookPullRequestLockedPullRequestAuthorAssociation(rawValue: "COLLABORATOR")
    public static let contributor = WebhookPullRequestLockedPullRequestAuthorAssociation(rawValue: "CONTRIBUTOR")
    public static let firstTimer = WebhookPullRequestLockedPullRequestAuthorAssociation(rawValue: "FIRST_TIMER")
    public static let firstTimeContributor =
        WebhookPullRequestLockedPullRequestAuthorAssociation(rawValue: "FIRST_TIME_CONTRIBUTOR")
    public static let mannequin = WebhookPullRequestLockedPullRequestAuthorAssociation(rawValue: "MANNEQUIN")
    public static let member = WebhookPullRequestLockedPullRequestAuthorAssociation(rawValue: "MEMBER")
    public static let none = WebhookPullRequestLockedPullRequestAuthorAssociation(rawValue: "NONE")
    public static let owner = WebhookPullRequestLockedPullRequestAuthorAssociation(rawValue: "OWNER")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// The default value for a squash merge commit title: - `PR_TITLE` - default to the pull request's title. -
/// `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when
/// more than one commit).
public struct WebhookPullRequestLockedPullRequestHeadRepoSquashMergeCommitTitle: RawRepresentable, Hashable, Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let prTitle = WebhookPullRequestLockedPullRequestHeadRepoSquashMergeCommitTitle(rawValue: "PR_TITLE")
    public static let commitOrPrTitle =
        WebhookPullRequestLockedPullRequestHeadRepoSquashMergeCommitTitle(rawValue: "COMMIT_OR_PR_TITLE")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// The default value for a merge commit title. - `PR_TITLE` - default to the pull request's title. -
/// `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from
/// branch-name).
public struct WebhookPullRequestLockedPullRequestBaseRepoMergeCommitTitle: RawRepresentable, Hashable, Codable,
    Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let prTitle = WebhookPullRequestLockedPullRequestBaseRepoMergeCommitTitle(rawValue: "PR_TITLE")
    public static let mergeMessage =
        WebhookPullRequestLockedPullRequestBaseRepoMergeCommitTitle(rawValue: "MERGE_MESSAGE")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Required enumerated value serialized in the `active_lock_reason` wire field.
public struct WebhookPullRequestLockedPullRequestActiveLockReason: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let resolved = WebhookPullRequestLockedPullRequestActiveLockReason(rawValue: "resolved")
    public static let offTopic = WebhookPullRequestLockedPullRequestActiveLockReason(rawValue: "off-topic")
    public static let tooHeated = WebhookPullRequestLockedPullRequestActiveLockReason(rawValue: "too heated")
    public static let spam = WebhookPullRequestLockedPullRequestActiveLockReason(rawValue: "spam")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `type` wire field.
public struct WebhookPullRequestLockedPullRequestAutoMergeEnabledByType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let bot = WebhookPullRequestLockedPullRequestAutoMergeEnabledByType(rawValue: "Bot")
    public static let user = WebhookPullRequestLockedPullRequestAutoMergeEnabledByType(rawValue: "User")
    public static let organization = WebhookPullRequestLockedPullRequestAutoMergeEnabledByType(rawValue: "Organization")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Required enumerated value serialized in the `action` wire field.
public struct WebhookPullRequestLockedAction: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let locked = WebhookPullRequestLockedAction(rawValue: "locked")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `type` wire field.
public struct WebhookPullRequestLockedPullRequestBaseUserType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let bot = WebhookPullRequestLockedPullRequestBaseUserType(rawValue: "Bot")
    public static let user = WebhookPullRequestLockedPullRequestBaseUserType(rawValue: "User")
    public static let organization = WebhookPullRequestLockedPullRequestBaseUserType(rawValue: "Organization")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// The default value for a squash merge commit message: - `PR_BODY` - default to the pull request's body. -
/// `COMMIT_MESSAGES` - default to the branch's commit messages. - `BLANK` - default to a blank commit message.
public struct WebhookPullRequestLockedPullRequestHeadRepoSquashMergeCommitMessage: RawRepresentable, Hashable, Codable,
    Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let prBody = WebhookPullRequestLockedPullRequestHeadRepoSquashMergeCommitMessage(rawValue: "PR_BODY")
    public static let commitMessages =
        WebhookPullRequestLockedPullRequestHeadRepoSquashMergeCommitMessage(rawValue: "COMMIT_MESSAGES")
    public static let blank = WebhookPullRequestLockedPullRequestHeadRepoSquashMergeCommitMessage(rawValue: "BLANK")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// The default value for a merge commit title. - `PR_TITLE` - default to the pull request's title. -
/// `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from
/// branch-name).
public struct WebhookPullRequestLockedPullRequestHeadRepoMergeCommitTitle: RawRepresentable, Hashable, Codable,
    Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let prTitle = WebhookPullRequestLockedPullRequestHeadRepoMergeCommitTitle(rawValue: "PR_TITLE")
    public static let mergeMessage =
        WebhookPullRequestLockedPullRequestHeadRepoMergeCommitTitle(rawValue: "MERGE_MESSAGE")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// State of this Pull Request. Either `open` or `closed`.
public struct WebhookPullRequestLockedPullRequestState: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let open = WebhookPullRequestLockedPullRequestState(rawValue: "open")
    public static let closed = WebhookPullRequestLockedPullRequestState(rawValue: "closed")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Optional enumerated value serialized in the `type` wire field.
public struct WebhookPullRequestLockedPullRequestBaseRepoOwnerType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let bot = WebhookPullRequestLockedPullRequestBaseRepoOwnerType(rawValue: "Bot")
    public static let user = WebhookPullRequestLockedPullRequestBaseRepoOwnerType(rawValue: "User")
    public static let organization = WebhookPullRequestLockedPullRequestBaseRepoOwnerType(rawValue: "Organization")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
