// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

// WebhookProjectDeleted domain models
/// Typed representation of the `WebhookProjectDeleted` API schema.
public struct WebhookProjectDeleted: Codable {
    /// Required enumerated value serialized in the `action` wire field.
    public var action: WebhookProjectDeletedAction
    /// Required object value serialized in the `project` wire field.
    public var project: WebhooksProject
    /// An enterprise on GitHub. Webhook payloads contain the `enterprise` property when the webhook is configured
    /// on an enterprise account or an organization that's part of an enterprise account. For more information, see
    /// "About enterprise accounts."
    public var enterprise: EnterpriseWebhooks?
    /// The GitHub App installation. Webhook payloads contain the `installation` property when the event is
    /// configured for and sent to a GitHub App. For more information, see "Using webhooks with GitHub Apps."
    public var installation: SimpleInstallation?
    /// A GitHub organization. Webhook payloads contain the `organization` property when the webhook is configured
    /// for an organization, or when the event occurs from activity in a repository owned by an organization.
    public var organization: OrganizationSimpleWebhooks?
    /// The repository on GitHub where the event occurred. Webhook payloads contain the `repository` property when
    /// the event occurs from activity in a repository.
    public var repository: NullableRepositoryWebhooks?
    /// A GitHub user.
    public var sender: SimpleUser?

    enum CodingKeys: String, CodingKey {
        case action
        case project
        case enterprise
        case installation
        case organization
        case repository
        case sender
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension WebhookProjectDeleted {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.action) else {
            throw SdkValidationError(field: "action", code: "required", message: "Validation failed for 'action': value is required")
        }
        guard container.contains(.project) else {
            throw SdkValidationError(field: "project", code: "required", message: "Validation failed for 'project': value is required")
        }
        self.action = try container.sdkDecodeRequired(.action)
        self.project = try container.sdkDecodeRequired(.project)
        self.enterprise = try container.sdkDecodeIfPresent(.enterprise)
        self.installation = try container.sdkDecodeIfPresent(.installation)
        self.organization = try container.sdkDecodeIfPresent(.organization)
        self.repository = try container.sdkDecodeIfPresent(.repository)
        self.sender = try container.sdkDecodeIfPresent(.sender)
    }
}

public extension WebhookProjectDeleted {
    public init(action: WebhookProjectDeletedAction, project: WebhooksProject, enterprise: EnterpriseWebhooks? = nil, installation: SimpleInstallation? = nil, organization: OrganizationSimpleWebhooks? = nil, repository: NullableRepositoryWebhooks? = nil, sender: SimpleUser? = nil) {
        (self.action, self.project) = (action, project)
        (self.enterprise, self.installation) = (enterprise, installation)
        (self.organization, self.repository) = (organization, repository)
        self.sender = sender
    }
}

/// Required enumerated value serialized in the `action` wire field.
public struct WebhookProjectDeletedAction: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let deleted = WebhookProjectDeletedAction(rawValue: "deleted")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
