// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif
extension ClassroomMethods {
    /// Retrieves a classroom assignment by its unique identifier. This operation is closing down and will be removed on August 28, 2026.
    ///
    /// > [!WARNING] > **Closed notice:** This operation is no longer available as of August 28, 2026. > For more information, see the [GitHub Classroom sunset notice](https://gh.io/classroom-sunset).
    ///
    /// - Parameters:
    /// - assignmentId: The unique identifier of the classroom assignment.
    ///
    /// - Warning: This operation is deprecated and may be removed in a future release.
    public static func classroomGetAnAssignment(config: ClientConfig, assignmentId: Int) async throws -> SdkEmptyResponse {
        return try (await sdkRequest("GET", ["/assignments/", sdkEncodePathSegment(sdkWireString(assignmentId))].joined(), config: config, decoder: .empty, operationId: "classroomGetAnAssignment")).data
    }

    /// Lists the accepted assignments associated with a classroom assignment. This operation is closing down and will be removed on August 28, 2026.
    ///
    /// > [!WARNING] > **Closed notice:** This operation is no longer available as of August 28, 2026. > For more information, see the [GitHub Classroom sunset notice](https://gh.io/classroom-sunset).
    ///
    /// - Parameters:
    /// - assignmentId: The unique identifier of the classroom assignment.
    ///
    /// - Warning: This operation is deprecated and may be removed in a future release.
    public static func classroomListAcceptedAssignmentsForAnAssignment(config: ClientConfig, assignmentId: Int) async throws -> SdkEmptyResponse {
        return try (await sdkRequest("GET", ["/assignments/", sdkEncodePathSegment(sdkWireString(assignmentId)), "/accepted_assignments"].joined(), config: config, decoder: .empty, operationId: "classroomListAcceptedAssignmentsForAnAssignment")).data
    }
}
