// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif
public extension CodeScanningMethods {
    struct CodeScanningUpdateDefaultSetupOptions: Codable {
        public var owner: String
        public var repo: String
        public var state: CodeScanningDefaultSetupUpdateState?
        public var runnerType: CodeScanningDefaultSetupUpdateRunnerType?
        public var runnerLabel: SdkOptional<String>?
        public var querySuite: CodeScanningDefaultSetupUpdateQuerySuite?
        public var threatModel: CodeScanningDefaultSetupUpdateThreatModel?
        public var languages: [CodeScanningDefaultSetupUpdateLanguagesItem]?

        public init(owner: String, repo: String) {
            self.owner = owner
            self.repo = repo
        }
    }

    /// Updates a code scanning default setup configuration. OAuth app tokens and personal access tokens (classic) need
    /// the `repo` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use
    /// this endpoint with only public repositories.
    ///
    /// - Parameters:
    /// - owner: The account owner of the repository. The name is not case
    ///   sensitive.
    /// - repo: The name of the repository without the `.git` extension. The name is
    ///   not case sensitive.
    /// - state: The desired state of code scanning default setup.
    /// - runnerType: Runner type to be used.
    /// - runnerLabel: Runner label to be used if the runner type is labeled.
    /// - querySuite: CodeQL query suite to be used.
    /// - threatModel: Threat model to be used for code scanning analysis. Use
    ///   `remote` to analyze only network sources and `remote_and_local` to include
    ///   local sources like filesystem access, command-line arguments, database
    ///   reads, environment variable and standard input.
    /// - languages: CodeQL languages to be analyzed.
    static func codeScanningUpdateDefaultSetup(
        config: ClientConfig,
        options: CodeScanningUpdateDefaultSetupOptions
    ) async throws -> EmptyObject {
        let requestBody = CodeScanningUpdateDefaultSetupRequestBody(options: options)

        return try await (sdkRequest(
            "PATCH",
            [
                "/repos/",
                sdkEncodePathSegment(sdkWireString(options.owner)),
                "/",
                sdkEncodePathSegment(sdkWireString(options.repo)),
                "/code-scanning/default-setup",
            ].joined(),
            config: config,
            body: requestBody,
            decoder: .json,
            operationId: "codeScanningUpdateDefaultSetup"
        )).data
    }
}
