// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif
extension ReposMethods {
    /// List public repositories
    ///
    /// Lists all public repositories in the order that they were created. Note: - For GitHub Enterprise Server, this endpoint will only list repositories available to all users on the enterprise. - Pagination is powered exclusively by the `since` parameter. Use the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers) to get the URL for the next page of repositories.
    ///
    /// - Parameters:
    /// - since: A repository ID. Only return repositories with an ID greater than
    ///   this ID.
    public static func reposListPublic(config: ClientConfig, since: Int?) async throws -> [MinimalRepository] {
        return try (await sdkRequest("GET", "/repositories", config: config, query: [
            SdkQueryParameter("since", value: since),
        ], decoder: .json, operationId: "reposListPublic")).data
    }
}
