// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif
public extension ReposMethods {
    struct ReposCreateOrUpdateFileContentsOptions: Codable {
        public var owner: String
        public var repo: String
        public var path: String
        public var message: String
        public var content: String
        public var sha: String?
        public var branch: String?
        public var committer: ReposCreateOrUpdateFileContentsRequestBodyCommitter?
        public var author: ReposCreateOrUpdateFileContentsRequestBodyAuthor?

        public init(owner: String, repo: String, path: String, message: String, content: String) {
            self.owner = owner
            self.repo = repo
            self.path = path
            self.message = message
            self.content = content
        }
    }

    /// Creates a new file or replaces an existing file in a repository. > [!NOTE] > If you use this endpoint and the
    /// "[Delete a file](https://docs.github.com/rest/repos/contents/#delete-a-file)" endpoint in parallel, the
    /// concurrent requests will conflict and you will receive errors. You must use these endpoints serially instead.
    /// OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint. The `workflow`
    /// scope is also required in order to modify files in the `.github/workflows` directory.
    ///
    /// - Parameters:
    /// - owner: The account owner of the repository. The name is not case
    ///   sensitive.
    /// - repo: The name of the repository without the `.git` extension. The name is
    ///   not case sensitive.
    /// - path: path parameter
    /// - message: The commit message.
    /// - content: The new file content, using Base64 encoding.
    /// - sha: **Required if you are updating a file**. The blob SHA of the file
    ///   being replaced.
    /// - branch: The branch name. Default: the repository’s default branch.
    /// - committer: The person that committed the file. Default: the authenticated
    ///   user.
    /// - author: The author of the file. Default: The `committer` or the
    ///   authenticated user if you omit `committer`.
    static func reposCreateOrUpdateFileContents(
        config: ClientConfig,
        options: ReposCreateOrUpdateFileContentsOptions
    ) async throws -> FileCommit {
        let requestBody = ReposCreateOrUpdateFileContentsRequestBody(options: options)

        return try await (sdkRequest(
            "PUT",
            [
                "/repos/",
                sdkEncodePathSegment(sdkWireString(options.owner)),
                "/",
                sdkEncodePathSegment(sdkWireString(options.repo)),
                "/contents/",
                sdkEncodePathSegment(sdkWireString(options.path)),
            ].joined(),
            config: config,
            body: requestBody,
            decoder: .json,
            operationId: "reposCreateOrUpdateFileContents"
        )).data
    }
}
