// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif
extension SecurityAdvisoriesMethods {
    public struct SecurityAdvisoriesListRepositoryAdvisoriesOptions: Codable {
        public var owner: String
        public var repo: String
        public var direction: SecurityAdvisoriesListGlobalAdvisoriesParameter?
        public var sort: SecurityAdvisoriesListRepositoryAdvisoriesParameter?
        public var before: String?
        public var after: String?
        public var perPage: Int?
        public var state: SecurityAdvisoriesListRepositoryAdvisoriesParameterXb40a7661?

        public init(owner: String, repo: String) {
            self.owner = owner
            self.repo = repo
        }
    }

    /// List repository security advisories
    ///
    /// Lists security advisories in a repository. The authenticated user can access unpublished security advisories from a repository if they are a security manager or administrator of that repository, or if they are a collaborator on any security advisory. OAuth app tokens and personal access tokens (classic) need the `repo` or `repository_advisories:read` scope to to get a published security advisory in a private repository, or any unpublished security advisory that the authenticated user has access to.
    ///
    /// - Parameters:
    /// - owner: The account owner of the repository. The name is not case
    ///   sensitive.
    /// - repo: The name of the repository without the `.git` extension. The name is
    ///   not case sensitive.
    /// - direction: The direction to sort the results by.
    /// - sort: The property to sort the results by.
    /// - before: A cursor, as given in the [Link
    ///   header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api
    ///   #using-link-headers). If specified, the query only searches for results
    ///   before this cursor. For more information, see "[Using pagination in the REST
    ///   API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the
    ///   -rest-api)."
    /// - after: A cursor, as given in the [Link
    ///   header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api
    ///   #using-link-headers). If specified, the query only searches for results
    ///   after this cursor. For more information, see "[Using pagination in the REST
    ///   API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the
    ///   -rest-api)."
    /// - perPage: The number of advisories to return per page. For more
    ///   information, see "[Using pagination in the REST
    ///   API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the
    ///   -rest-api)."
    /// - state: Filter by state of the repository advisories. Only advisories of
    ///   this state will be returned.
    public static func securityAdvisoriesListRepositoryAdvisories(config: ClientConfig, options: SecurityAdvisoriesListRepositoryAdvisoriesOptions) async throws -> [RepositoryAdvisory] {
        if let perPage = options.perPage {
            try validateRange("per_page", Double(perPage), min: 1, max: 100)
        }

        return try (await sdkRequest("GET", ["/repos/", sdkEncodePathSegment(sdkWireString(options.owner)), "/", sdkEncodePathSegment(sdkWireString(options.repo)), "/security-advisories"].joined(), config: config, query: [
            SdkQueryParameter("direction", value: options.direction),
            SdkQueryParameter("sort", value: options.sort),
            SdkQueryParameter("before", value: options.before),
            SdkQueryParameter("after", value: options.after),
            SdkQueryParameter("per_page", value: options.perPage),
            SdkQueryParameter("state", value: options.state),
        ], decoder: .json, operationId: "securityAdvisoriesListRepositoryAdvisories")).data
    }
}
