// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif
struct ActionsSetAllowedActionsRepositoryRequestBody: Encodable {
    var githubOwnedAllowed: Bool?
    var verifiedAllowed: Bool?
    var patternsAllowed: [String]?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encodeIfPresent(githubOwnedAllowed, forKey: SdkCodingKey("github_owned_allowed"))
        try keyedContainer.encodeIfPresent(verifiedAllowed, forKey: SdkCodingKey("verified_allowed"))
        try keyedContainer.encodeIfPresent(patternsAllowed, forKey: SdkCodingKey("patterns_allowed"))
    }
}

struct ActionsSetGithubActionsDefaultWorkflowPermissionsRepositoryRequestBody: Encodable {
    var defaultWorkflowPermissions: ActionsDefaultWorkflowPermissions?
    var canApprovePullRequestReviews: ActionsCanApprovePullRequestReviews?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encodeIfPresent(
            defaultWorkflowPermissions,
            forKey: SdkCodingKey("default_workflow_permissions")
        )
        try keyedContainer.encodeIfPresent(
            canApprovePullRequestReviews,
            forKey: SdkCodingKey("can_approve_pull_request_reviews")
        )
    }
}

struct ActionsGenerateRunnerJitconfigForRepoRequestBody: Encodable {
    let name: String
    let runnerGroupId: Int
    let labels: [String]
    var workFolder: String?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(name, forKey: SdkCodingKey("name"))
        try keyedContainer.encode(runnerGroupId, forKey: SdkCodingKey("runner_group_id"))
        try keyedContainer.encode(labels, forKey: SdkCodingKey("labels"))
        try keyedContainer.encodeIfPresent(workFolder, forKey: SdkCodingKey("work_folder"))
    }
}

struct ActionsAddCustomLabelsToSelfHostedRunnerForRepoRequestBody: Encodable {
    let labels: [String]

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(labels, forKey: SdkCodingKey("labels"))
    }
}

struct ActionsSetCustomLabelsForSelfHostedRunnerForRepoRequestBody: Encodable {
    let labels: [String]

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(labels, forKey: SdkCodingKey("labels"))
    }
}

struct ActionsReviewPendingDeploymentsForRunRequestBody: Encodable {
    let environmentIds: [Int]
    let state: ActionsReviewPendingDeploymentsForRunRequestBodyState
    let comment: String

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(environmentIds, forKey: SdkCodingKey("environment_ids"))
        try keyedContainer.encode(state, forKey: SdkCodingKey("state"))
        try keyedContainer.encode(comment, forKey: SdkCodingKey("comment"))
    }
}

struct ActionsReRunWorkflowRequestBody: Encodable {
    var enableDebugLogging: Bool?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encodeIfPresent(enableDebugLogging, forKey: SdkCodingKey("enable_debug_logging"))
    }
}

struct ActionsReRunWorkflowFailedJobsRequestBody: Encodable {
    var enableDebugLogging: Bool?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encodeIfPresent(enableDebugLogging, forKey: SdkCodingKey("enable_debug_logging"))
    }
}

struct ActionsCreateOrUpdateRepoSecretRequestBody: Encodable {
    let encryptedValue: String
    let keyId: String

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(encryptedValue, forKey: SdkCodingKey("encrypted_value"))
        try keyedContainer.encode(keyId, forKey: SdkCodingKey("key_id"))
    }
}

struct ActionsCreateRepoVariableRequestBody: Encodable {
    let name: String
    let value: String

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(name, forKey: SdkCodingKey("name"))
        try keyedContainer.encode(value, forKey: SdkCodingKey("value"))
    }
}

struct ActionsUpdateRepoVariableRequestBody: Encodable {
    var name2: String?
    var value: String?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encodeIfPresent(name2, forKey: SdkCodingKey("name"))
        try keyedContainer.encodeIfPresent(value, forKey: SdkCodingKey("value"))
    }
}

struct ActionsCreateWorkflowDispatchRequestBody: Encodable {
    let ref: String
    var inputs: [String: JSONValue]?
    var returnRunDetails: Bool?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(ref, forKey: SdkCodingKey("ref"))
        try keyedContainer.encodeIfPresent(inputs, forKey: SdkCodingKey("inputs"))
        try keyedContainer.encodeIfPresent(returnRunDetails, forKey: SdkCodingKey("return_run_details"))
    }
}

struct ActionsCreateOrUpdateEnvironmentSecretRequestBody: Encodable {
    let encryptedValue: String
    let keyId: String

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(encryptedValue, forKey: SdkCodingKey("encrypted_value"))
        try keyedContainer.encode(keyId, forKey: SdkCodingKey("key_id"))
    }
}

struct ActionsCreateEnvironmentVariableRequestBody: Encodable {
    let name: String
    let value: String

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(name, forKey: SdkCodingKey("name"))
        try keyedContainer.encode(value, forKey: SdkCodingKey("value"))
    }
}

struct ActionsUpdateEnvironmentVariableRequestBody: Encodable {
    var name2: String?
    var value: String?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encodeIfPresent(name2, forKey: SdkCodingKey("name"))
        try keyedContainer.encodeIfPresent(value, forKey: SdkCodingKey("value"))
    }
}

struct OidcCreateOidcCustomPropertyInclusionForEnterpriseRequestBody: Encodable {
    let customPropertyName: String

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(customPropertyName, forKey: SdkCodingKey("custom_property_name"))
    }
}

struct OidcCreateOidcCustomPropertyInclusionForOrgRequestBody: Encodable {
    let customPropertyName: String

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(customPropertyName, forKey: SdkCodingKey("custom_property_name"))
    }
}

struct OidcUpdateOidcCustomSubTemplateForOrgRequestBody: Encodable {
    var includeClaimKeys: [String]?
    var useImmutableSubject: Bool?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encodeIfPresent(includeClaimKeys, forKey: SdkCodingKey("include_claim_keys"))
        try keyedContainer.encodeIfPresent(useImmutableSubject, forKey: SdkCodingKey("use_immutable_subject"))
    }
}
