// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif
struct PullRequestStacksAddRequestBody: Encodable {
    let pullRequests: [Int]

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(pullRequests, forKey: SdkCodingKey("pull_requests"))
    }
}

struct UsersUpdateAuthenticatedRequestBody: Encodable {
    var name: String?
    var email: String?
    var blog: String?
    var twitterUsername: SdkOptional<String>?
    var company: String?
    var location: String?
    var hireable: Bool?
    var bio: String?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encodeIfPresent(name, forKey: SdkCodingKey("name"))
        try keyedContainer.encodeIfPresent(email, forKey: SdkCodingKey("email"))
        try keyedContainer.encodeIfPresent(blog, forKey: SdkCodingKey("blog"))
        try keyedContainer.encodeIfPresent(twitterUsername, forKey: SdkCodingKey("twitter_username"))
        try keyedContainer.encodeIfPresent(company, forKey: SdkCodingKey("company"))
        try keyedContainer.encodeIfPresent(location, forKey: SdkCodingKey("location"))
        try keyedContainer.encodeIfPresent(hireable, forKey: SdkCodingKey("hireable"))
        try keyedContainer.encodeIfPresent(bio, forKey: SdkCodingKey("bio"))
    }

    init(options: UsersMethods.UsersUpdateAuthenticatedOptions) {
        name = options.name
        email = options.email
        blog = options.blog
        twitterUsername = options.twitterUsername
        company = options.company
        location = options.location
        hireable = options.hireable
        bio = options.bio
    }
}

struct UsersSetPrimaryEmailVisibilityForAuthenticatedUserRequestBody: Encodable {
    let visibility: UsersSetPrimaryEmailVisibilityForAuthenticatedUserRequestBodyVisibility

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(visibility, forKey: SdkCodingKey("visibility"))
    }
}

struct UsersCreateGpgKeyForAuthenticatedUserRequestBody: Encodable {
    let armoredPublicKey: String
    var name: String?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(armoredPublicKey, forKey: SdkCodingKey("armored_public_key"))
        try keyedContainer.encodeIfPresent(name, forKey: SdkCodingKey("name"))
    }
}

struct UsersCreatePublicSshKeyForAuthenticatedUserRequestBody: Encodable {
    let key: String
    var title: String?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(key, forKey: SdkCodingKey("key"))
        try keyedContainer.encodeIfPresent(title, forKey: SdkCodingKey("title"))
    }
}

struct UsersAddSocialAccountForAuthenticatedUserRequestBody: Encodable {
    let accountUrls: [String]

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(accountUrls, forKey: SdkCodingKey("account_urls"))
    }
}

struct UsersDeleteSocialAccountForAuthenticatedUserRequestBody: Encodable {
    let accountUrls: [String]

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(accountUrls, forKey: SdkCodingKey("account_urls"))
    }
}

struct UsersCreateSshSigningKeyForAuthenticatedUserRequestBody: Encodable {
    let key: String
    var title: String?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(key, forKey: SdkCodingKey("key"))
        try keyedContainer.encodeIfPresent(title, forKey: SdkCodingKey("title"))
    }
}

struct UsersListAttestationsBulkRequestBody: Encodable {
    let subjectDigests: [String]
    var predicateType: String?

    func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: SdkCodingKey.self)
        try keyedContainer.encode(subjectDigests, forKey: SdkCodingKey("subject_digests"))
        try keyedContainer.encodeIfPresent(predicateType, forKey: SdkCodingKey("predicate_type"))
    }
}
