// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

// Canonical repos operation model declarations
public enum ReposAddTeamAccessRestrictionsRequestBody {
    case reposAddTeamAccessRestrictionsRequestBodyVariant0(ReposAddTeamAccessRestrictionsRequestBodyVariant0)
    case stringList([String])
}

extension ReposAddTeamAccessRestrictionsRequestBody: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for ReposAddTeamAccessRestrictionsRequestBody")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            ReposAddTeamAccessRestrictionsRequestBodyVariant0.self
        ) {
            return             .reposAddTeamAccessRestrictionsRequestBodyVariant0(value)
        }
        if let value = try? container.decode([String].self) { return .stringList(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .reposAddTeamAccessRestrictionsRequestBodyVariant0(value): try container.encode(value); return true
        case let .stringList(value): try container.encode(value); return true
        }
    }

}

/// Allow specific users, teams, or apps to bypass pull request requirements.
public struct ReposUpdatePullRequestReviewProtectionRequestBodyBypassPullReX4b5a4bd7de: Codable {
    /// The list of user `login`s allowed to bypass pull request requirements.
    public var users: [String]?
    /// The list of team `slug`s allowed to bypass pull request requirements.
    public var teams: [String]?
    /// The list of app `slug`s allowed to bypass pull request requirements.
    public var apps: [String]?

    enum CodingKeys: String, CodingKey {
        case users
        case teams
        case apps
    }

    init() {
        (self.users, self.teams, self.apps) = (nil, nil, nil)
    }
}

public extension ReposUpdatePullRequestReviewProtectionRequestBodyBypassPullReX4b5a4bd7de {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.users = try container.sdkDecodeIfPresent(.users)
        self.teams = try container.sdkDecodeIfPresent(.teams)
        self.apps = try container.sdkDecodeIfPresent(.apps)
    }
}

public extension ReposUpdatePullRequestReviewProtectionRequestBodyBypassPullReX4b5a4bd7de {
    public init(users: [String]? = nil, teams: [String]? = nil, apps: [String]? = nil) {
        self.init()
        (self.users, self.teams) = (users, teams)
        self.apps = apps
    }
}

public struct ReposSetStatusCheckContextsRequestBodyVariant0: Codable {
    /// The name of the status checks
    public var contexts: [String]

    enum CodingKeys: String, CodingKey {
        case contexts
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension ReposSetStatusCheckContextsRequestBodyVariant0 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.contexts) else {
            throw SdkValidationError(field: "contexts", code: "required", message: "Validation failed for 'contexts': value is required")
        }
        self.contexts = try container.sdkDecodeRequired(.contexts)
    }
}

public extension ReposSetStatusCheckContextsRequestBodyVariant0 {
    public init(contexts: [String]) {
        self.contexts = contexts
    }
}

/// The person that committed the file. Default: the authenticated user.
public struct ReposCreateOrUpdateFileContentsRequestBodyCommitter: Codable {
    /// The name of the author or committer of the commit. You'll receive a `422` status code if `name` is omitted.
    public var name: String
    /// The email of the author or committer of the commit. You'll receive a `422` status code if `email` is
    /// omitted.
    public var email: String
    /// - Example: "\"2013-01-05T13:13:22+05:00\""
    public var date: String?

    enum CodingKeys: String, CodingKey {
        case name
        case email
        case date
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension ReposCreateOrUpdateFileContentsRequestBodyCommitter {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.name) else {
            throw SdkValidationError(field: "name", code: "required", message: "Validation failed for 'name': value is required")
        }
        guard container.contains(.email) else {
            throw SdkValidationError(field: "email", code: "required", message: "Validation failed for 'email': value is required")
        }
        self.name = try container.sdkDecodeRequired(.name)
        self.email = try container.sdkDecodeRequired(.email)
        self.date = try container.sdkDecodeIfPresent(.date)
    }
}

public extension ReposCreateOrUpdateFileContentsRequestBodyCommitter {
    public init(name: String, email: String, date: String? = nil) {
        (self.name, self.email) = (name, email)
        self.date = date
    }
}

/// Use the `status` property to enable or disable secret scanning non-provider patterns for this repository. For
/// more information, see "Supported secret scanning patterns."
public struct ReposUpdateRequestBodySecurityAndAnalysisSecretScanningNonProX6b7f229ea0: Codable {
    /// Can be `enabled` or `disabled`.
    public var status: String?

    enum CodingKeys: String, CodingKey {
        case status
    }

    init() {
        self.status = nil
    }
}

public extension ReposUpdateRequestBodySecurityAndAnalysisSecretScanningNonProX6b7f229ea0 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.status = try container.sdkDecodeIfPresent(.status)
    }
}

public extension ReposUpdateRequestBodySecurityAndAnalysisSecretScanningNonProX6b7f229ea0 {
    public init(status: String? = nil) {
        self.init()
        self.status = status
    }
}

public struct ReposCreateAttestationRequestBodyBundleVerificationMaterial: Codable {

    private init(sdkCopy value: Self) { self = value }
}

public extension ReposCreateAttestationRequestBodyBundleVerificationMaterial {
    public init() {
    }
}

public struct ReposRemoveStatusCheckContextsRequestBodyVariant0: Codable {
    /// The name of the status checks
    public var contexts: [String]

    enum CodingKeys: String, CodingKey {
        case contexts
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension ReposRemoveStatusCheckContextsRequestBodyVariant0 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.contexts) else {
            throw SdkValidationError(field: "contexts", code: "required", message: "Validation failed for 'contexts': value is required")
        }
        self.contexts = try container.sdkDecodeRequired(.contexts)
    }
}

public extension ReposRemoveStatusCheckContextsRequestBodyVariant0 {
    public init(contexts: [String]) {
        self.contexts = contexts
    }
}

public enum ReposSetTeamAccessRestrictionsRequestBody {
    case reposSetTeamAccessRestrictionsRequestBodyVariant0(ReposSetTeamAccessRestrictionsRequestBodyVariant0)
    case stringList([String])
}

extension ReposSetTeamAccessRestrictionsRequestBody: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for ReposSetTeamAccessRestrictionsRequestBody")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            ReposSetTeamAccessRestrictionsRequestBodyVariant0.self
        ) {
            return             .reposSetTeamAccessRestrictionsRequestBodyVariant0(value)
        }
        if let value = try? container.decode([String].self) { return .stringList(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .reposSetTeamAccessRestrictionsRequestBodyVariant0(value): try container.encode(value); return true
        case let .stringList(value): try container.encode(value); return true
        }
    }

}

/// Use the `status` property to enable or disable secret scanning delegated alert dismissal for this repository.
public struct ReposUpdateRequestBodySecurityAndAnalysisSecretScanningDelegaXf6ccecd8e2: Codable {
    /// Can be `enabled` or `disabled`.
    public var status: String?

    enum CodingKeys: String, CodingKey {
        case status
    }

    init() {
        self.status = nil
    }
}

public extension ReposUpdateRequestBodySecurityAndAnalysisSecretScanningDelegaXf6ccecd8e2 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.status = try container.sdkDecodeIfPresent(.status)
    }
}

public extension ReposUpdateRequestBodySecurityAndAnalysisSecretScanningDelegaXf6ccecd8e2 {
    public init(status: String? = nil) {
        self.init()
        self.status = status
    }
}

public enum ReposCreateDeploymentRequestBodyPayload {
    case jsonValue([String: JSONValue])
    case stringValue(String)
}

extension ReposCreateDeploymentRequestBodyPayload: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for ReposCreateDeploymentRequestBodyPayload")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode([String: JSONValue].self) { return .jsonValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .jsonValue(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum ReposGetContentResponse {
    case contentDirectory(ContentDirectory)
    case contentFile(ContentFile)
    case contentSymlink(ContentSymlink)
    case contentSubmodule(ContentSubmodule)
}

extension ReposGetContentResponse: Codable {

    private enum CodingKeys: String, CodingKey {
        case discriminator = "type"
    }

    public init(from decoder: Decoder) throws {
        let tagged = try decoder.container(keyedBy: CodingKeys.self)
        let discriminator = try tagged.decode(String.self, forKey: .discriminator)
        if let value = try Self.decodeGroup1(discriminator, from: decoder) { self = value; return }
        throw DecodingError.dataCorruptedError(forKey: .discriminator, in: tagged, debugDescription: "Unknown discriminator for ReposGetContentResponse")
    }

    private static func decodeGroup1(_ discriminator: String, from decoder: Decoder) throws -> Self? {
        switch discriminator {
        case "array": return .contentDirectory(try ContentDirectory(from: decoder))
        case "file": return .contentFile(try ContentFile(from: decoder))
        case "symlink": return .contentSymlink(try ContentSymlink(from: decoder))
        case "submodule": return .contentSubmodule(try ContentSubmodule(from: decoder))
        default: return nil
        }
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .contentDirectory(value): try container.encode(value); return true
        case let .contentFile(value): try container.encode(value); return true
        case let .contentSymlink(value): try container.encode(value); return true
        case let .contentSubmodule(value): try container.encode(value); return true
        }
    }

}

public struct ReposListCustomDeploymentRuleIntegrationsResponse: Codable {
    /// The total number of custom deployment protection rule integrations available for this environment.
    /// - Example: 35
    public var totalCount: Int?
    public var availableCustomDeploymentProtectionRuleIntegrations: [CustomDeploymentRuleApp]?

    enum CodingKeys: String, CodingKey {
        case totalCount = "total_count"
        case availableCustomDeploymentProtectionRuleIntegrations = "available_custom_deployment_protection_rule_integrations"
    }

    init() {
        (self.totalCount, self.availableCustomDeploymentProtectionRuleIntegrations) = (nil, nil)
    }
}

public extension ReposListCustomDeploymentRuleIntegrationsResponse {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.totalCount = try container.sdkDecodeIfPresent(.totalCount)
        self.availableCustomDeploymentProtectionRuleIntegrations = try container.sdkDecodeIfPresent(.availableCustomDeploymentProtectionRuleIntegrations)
    }
}

public extension ReposListCustomDeploymentRuleIntegrationsResponse {
    public init(totalCount: Int? = nil, availableCustomDeploymentProtectionRuleIntegrations: [CustomDeploymentRuleApp]? = nil) {
        self.init()
        self.totalCount = totalCount
        self.availableCustomDeploymentProtectionRuleIntegrations = availableCustomDeploymentProtectionRuleIntegrations
    }
}

/// Require at least one approving review on a pull request, before merging. Set to `null` to disable.
public struct ReposUpdateBranchProtectionRequestBodyRequiredPullRequestReviews: Codable {
    /// Specify which users, teams, and apps can dismiss pull request reviews. Pass an empty
    /// `dismissal_restrictions` object to disable. User and team `dismissal_restrictions` are only available for
    /// organization-owned repositories. Omit this parameter for personal repositories.
    public var dismissalRestrictions: ReposUpdateBranchProtectionRequestBodyRequiredPullRequestReviXb9ecd088d9?
    /// Set to `true` if you want to automatically dismiss approving reviews when someone pushes a new commit.
    public var dismissStaleReviews: Bool?
    /// Blocks merging pull requests until code owners review them.
    public var requireCodeOwnerReviews: Bool?
    /// Specify the number of reviewers required to approve pull requests. Use a number between 1 and 6 or 0 to not
    /// require reviewers.
    public var requiredApprovingReviewCount: Int?
    /// Whether the most recent push must be approved by someone other than the person who pushed it. Default:
    /// `false`.
    public var requireLastPushApproval: Bool?
    /// Allow specific users, teams, or apps to bypass pull request requirements.
    public var bypassPullRequestAllowances: ReposUpdateBranchProtectionRequestBodyRequiredPullRequestReviX0b92821648?

    enum CodingKeys: String, CodingKey {
        case dismissalRestrictions = "dismissal_restrictions"
        case dismissStaleReviews = "dismiss_stale_reviews"
        case requireCodeOwnerReviews = "require_code_owner_reviews"
        case requiredApprovingReviewCount = "required_approving_review_count"
        case requireLastPushApproval = "require_last_push_approval"
        case bypassPullRequestAllowances = "bypass_pull_request_allowances"
    }

    init() {
        (self.dismissalRestrictions, self.dismissStaleReviews, self.requireCodeOwnerReviews, self.requiredApprovingReviewCount, self.requireLastPushApproval) = (nil, nil, nil, nil, nil)
        self.bypassPullRequestAllowances = nil
    }
}

public extension ReposUpdateBranchProtectionRequestBodyRequiredPullRequestReviews {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.dismissalRestrictions = try container.sdkDecodeIfPresent(.dismissalRestrictions)
        self.dismissStaleReviews = try container.sdkDecodeIfPresent(.dismissStaleReviews)
        self.requireCodeOwnerReviews = try container.sdkDecodeIfPresent(.requireCodeOwnerReviews)
        self.requiredApprovingReviewCount = try container.sdkDecodeIfPresent(.requiredApprovingReviewCount)
        self.requireLastPushApproval = try container.sdkDecodeIfPresent(.requireLastPushApproval)
        self.bypassPullRequestAllowances = try container.sdkDecodeIfPresent(.bypassPullRequestAllowances)
    }
}

public extension ReposUpdateBranchProtectionRequestBodyRequiredPullRequestReviews {
    public init(dismissalRestrictions: ReposUpdateBranchProtectionRequestBodyRequiredPullRequestReviXb9ecd088d9? = nil, dismissStaleReviews: Bool? = nil, requireCodeOwnerReviews: Bool? = nil, requiredApprovingReviewCount: Int? = nil, requireLastPushApproval: Bool? = nil, bypassPullRequestAllowances: ReposUpdateBranchProtectionRequestBodyRequiredPullRequestReviX0b92821648? = nil) {
        self.init()
        self.dismissalRestrictions = dismissalRestrictions
        self.dismissStaleReviews = dismissStaleReviews
        self.requireCodeOwnerReviews = requireCodeOwnerReviews
        self.requiredApprovingReviewCount = requiredApprovingReviewCount
        self.requireLastPushApproval = requireLastPushApproval
        self.bypassPullRequestAllowances = bypassPullRequestAllowances
    }
}

/// The attestation's Sigstore Bundle. Refer to the Sigstore Bundle Specification for more information.
public struct ReposCreateAttestationRequestBodyBundle: Codable {
    public var mediaType: String?
    public var verificationMaterial: ReposCreateAttestationRequestBodyBundleVerificationMaterial?
    public var dsseEnvelope: ReposCreateAttestationRequestBodyBundleDsseEnvelope?

    enum CodingKeys: String, CodingKey {
        case mediaType
        case verificationMaterial
        case dsseEnvelope
    }

    init() {
        (self.mediaType, self.verificationMaterial, self.dsseEnvelope) = (nil, nil, nil)
    }
}

public extension ReposCreateAttestationRequestBodyBundle {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.mediaType = try container.sdkDecodeIfPresent(.mediaType)
        self.verificationMaterial = try container.sdkDecodeIfPresent(.verificationMaterial)
        self.dsseEnvelope = try container.sdkDecodeIfPresent(.dsseEnvelope)
    }
}

public extension ReposCreateAttestationRequestBodyBundle {
    public init(mediaType: String? = nil, verificationMaterial: ReposCreateAttestationRequestBodyBundleVerificationMaterial? = nil, dsseEnvelope: ReposCreateAttestationRequestBodyBundleDsseEnvelope? = nil) {
        self.init()
        (self.mediaType, self.verificationMaterial) = (mediaType, verificationMaterial)
        self.dsseEnvelope = dsseEnvelope
    }
}

public struct ReposAddTeamAccessRestrictionsRequestBodyVariant0: Codable {
    /// The slug values for teams
    public var teams: [String]

    enum CodingKeys: String, CodingKey {
        case teams
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension ReposAddTeamAccessRestrictionsRequestBodyVariant0 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.teams) else {
            throw SdkValidationError(field: "teams", code: "required", message: "Validation failed for 'teams': value is required")
        }
        self.teams = try container.sdkDecodeRequired(.teams)
    }
}

public extension ReposAddTeamAccessRestrictionsRequestBodyVariant0 {
    public init(teams: [String]) {
        self.teams = teams
    }
}

public enum ReposUpdateInformationAboutPagesSiteRequestBodySource {
    case stringValue(String)
    case reposUpdateInformationAboutPagesSiteRequestBodySourceVariant1(ReposUpdateInformationAboutPagesSiteRequestBodySourceVariant1)
}

extension ReposUpdateInformationAboutPagesSiteRequestBodySource: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for ReposUpdateInformationAboutPagesSiteRequestBodySource")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        if let value = try? container.decode(
            ReposUpdateInformationAboutPagesSiteRequestBodySourceVariant1.self
        ) {
            return             .reposUpdateInformationAboutPagesSiteRequestBodySourceVariant1(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .reposUpdateInformationAboutPagesSiteRequestBodySourceVariant1(value): try container.encode(value); return true
        }
    }

}
